Fix coverity issues
pmem/pmemkv pull request #1016
Opened 2021-07-09 13:42 UTC by KFilipek

- [pmemobj_engine] Handle exceptions thrown in destructor
- [tests] iterator_basic: add check after put

2021-07-09 14:26 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[src/pmemobj_engine.h, line 101 at r1](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeAeLC_CzznaFQcqf1Q:-MeAeLC_CzznaFQcqf1R:b-khuw1n) ([raw file](https://github.com/pmem/pmemkv/blob/26bbbfe4f0dcdd497959fed06f3e23c728b81151/src/pmemobj_engine.h#L101)):*
> ```objc
> 				pmpool.close();
> 		} catch (const std::logic_error &e) {
> 		}
> ```

Why not std::terminate()? Can this happen normally/


<!-- Sent from Reviewable.io -->

2021-07-09 15:53 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[src/pmemobj_engine.h, line 101 at r1](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeAeLC_CzznaFQcqf1Q:-MeAxodc01hshs0pb8LG:bs8yq1t) ([raw file](https://github.com/pmem/pmemkv/blob/26bbbfe4f0dcdd497959fed06f3e23c728b81151/src/pmemobj_engine.h#L101)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why not std::terminate()? Can this happen normally/
</blockquote></details>

Done. I've added std::terminate() to the catch clause. Previously I thought that pmpool can be closed in derivated class also, then this empty catch block would avoid crashing.


<!-- Sent from Reviewable.io -->

2021-07-12 06:17 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/pmemobj_engine.h, line 97 at r2](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeOLiXwDjYDc2aiztxg:-MeOLiXwDjYDc2aiztxh:b-t6mxz) ([raw file](https://github.com/pmem/pmemkv/blob/97f09c2bf6881d66098cf0481b458d3684cccbd6/src/pmemobj_engine.h#L97)):*
> ```objc
> 	~pmemobj_engine_base()
> 	{
> 		try {
> ```

why not try-catch only `pmpool.close();` (instead of the `if` clause)
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeOLxXd7ytJQ5FwzBEJ:-MeOLxXd7ytJQ5FwzBEK:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv/blob/97f09c2bf6881d66098cf0481b458d3684cccbd6/tests/engine_scenarios/all/iterator_basic.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

-2021


<!-- Sent from Reviewable.io -->

2021-07-12 08:26 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/pmemobj_engine.h, line 97 at r2](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeOLiXwDjYDc2aiztxg:-MeOohGf6Aafyuv-TwWh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/97f09c2bf6881d66098cf0481b458d3684cccbd6/src/pmemobj_engine.h#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why not try-catch only `pmpool.close();` (instead of the `if` clause)
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv/1016#-MeOLxXd7ytJQ5FwzBEJ:-MeOok-oDOWUkzLwYmJF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/97f09c2bf6881d66098cf0481b458d3684cccbd6/tests/engine_scenarios/all/iterator_basic.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-12 09:15 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-07-12 12:13 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/1016#-:-MePciB4-AsQ-a-SYzTg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-07-12 12:14 UTC, merged