jenkins: Add Jenkins scripts for running tests for pmemkv
pmem/pmemkv pull request #709
Opened 2020-06-09 10:56 UTC by nedved1

TODO: add README

Signed-off-by: pniedzwx <pawelx.niedzwiecki@intel.com>

2020-07-17 07:55 UTC, karczex commented
___
*[utils/jenkins/lib/api.groovy, line 170 at r1](https://reviewable.io/reviews/pmem/pmemkv/709#-M9SGpg040yBCtCyFwBH:-MBDKNq06DQmYK2iNywo:b-zcrpvy) ([raw file](https://github.com/pmem/pmemkv/blob/935c5991d0a40630032016cebf3cc8bd479b4bab/utils/jenkins/lib/api.groovy#L170)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

I think it would be possible that if remove groovy's echo, bash echo will be still visible in jenkins log. Is that what you mean?
</blockquote></details>

Exactly opposite :) I mean, to remove bash echo, and redirect all groovy outputs to log as well as to console 


<!-- Sent from Reviewable.io -->

2020-07-17 07:55 UTC, karczex commented
___
*[utils/jenkins/Jenkinsfile, line 143 at r1](https://reviewable.io/reviews/pmem/pmemkv/709#-M9O8Q1P64Hs5dMTMKL7:-MBD_O0X0UpahLPMuWbw:b-g2ierw) ([raw file](https://github.com/pmem/pmemkv/blob/935c5991d0a40630032016cebf3cc8bd479b4bab/utils/jenkins/Jenkinsfile#L143)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Hmm, do you want me to change "pmemkv_linux" and "pmemkv_linux_matrix" to "linux" and "linux_matrix"? This name will be displayed on Jenkins dashboard.
</blockquote></details>

IMO it's ok this way. 


<!-- Sent from Reviewable.io -->

2020-07-17 07:55 UTC, karczex commented
___
*[utils/jenkins/Jenkinsfile, line 171 at r1](https://reviewable.io/reviews/pmem/pmemkv/709#-M9O8ufD1-D41DvU3SD6:-MCLo_C_9x9cT2HXz08Y:byf1m5u) ([raw file](https://github.com/pmem/pmemkv/blob/935c5991d0a40630032016cebf3cc8bd479b4bab/utils/jenkins/Jenkinsfile#L171)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

For now I believe we can start with the 3 you have right now.
Unless @karczex, do you have something else in mind?
</blockquote></details>

Those 3 are enough for now. 


<!-- Sent from Reviewable.io -->

2020-07-17 08:23 UTC, karczex commented
___
*[utils/jenkins/scripts/banner, line 8 at r2](https://reviewable.io/reviews/pmem/pmemkv/709#-MCQrJeyEMhPWVJ2QC87:-MCQrJeyEMhPWVJ2QC88:bhud5zb) ([raw file](https://github.com/pmem/pmemkv/blob/b241a35535ca8e2180087924d5600b24affa7352/utils/jenkins/scripts/banner#L8)):*
> ```
>  https://pmem-val-jenkins.pact.intel.com/
> ```
This page is not public. If someone wants to setup it on his own jenkins instance, he will get improper link. 


<!-- Sent from Reviewable.io -->

2020-08-12 16:49 UTC, lukaszstolarczuk commented on utils/jenkins/Jenkinsfile
> +	choiceParam('COVERAGE', ['yes', 'no'], 'Enable code coverage')
please make this default to "no"

2020-08-12 16:50 UTC, lukaszstolarczuk commented on utils/jenkins/Jenkinsfile
> +		description('description')
I'd say we should extend this description ;) I'd write something like: "Optional description for this execution."

2020-08-12 16:52 UTC, lukaszstolarczuk commented on utils/jenkins/Jenkinsfile
> +		defaultValue('fedora')
can we extend the default value to have all our currently supported OSes - I say at least "fedora,ubuntu" ...?

2020-08-12 16:57 UTC, lukaszstolarczuk commented on utils/jenkins/scripts/common.sh
> +	echo "libpmemobj++,: $(pkg-config --modversion libpmemob++j || echo 'libpmemobj not found')"
there are also two issues next to "libpmemobj++":
1. there's weird "," at the beginning, and
2. there's definitely unnecessary "j" in pkg-config command param

2020-08-20 18:06 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @karczex, @lukaszstolarczuk, and @nedved1)

___
*[utils/jenkins/scripts/common.sh, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMfSUO6G9SRJCSl-r6-19:-MFC23Mx6I-AWSBIQnGJ:b-viuxkx) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there are also two issues next to "libpmemobj++":
1. there's weird "," at the beginning, and
2. there's definitely unnecessary "j" in pkg-config command param
</blockquote></details>

ok, the "j" was missing in the first part of the name - "--modversion libpmemob**j**++" ;)


<!-- Sent from Reviewable.io -->

2020-08-25 14:17 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/709#-MDnSxel31ynNIws8tw0:-MF_y4Fb4-6KDi2zl59e:b-iemisn) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and there's still no README ;)
</blockquote></details>

ok, added README now

---
___
*[utils/jenkins/Jenkinsfile, line 12 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMes4wKwVsvN229-r6-12:-MFAzDWoEydEcfetJZDP:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/Jenkinsfile#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd say we should extend this description ;) I'd write something like: "Optional description for this execution."
</blockquote></details>

done
___
*[utils/jenkins/Jenkinsfile, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMes4wKwVsvN229-r6-19:-MFAvkWf2hN67TzCp7R_:b36ayz8) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/Jenkinsfile#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can we extend the default value to have all our currently supported OSes - I say at least "fedora,ubuntu" ...?
</blockquote></details>

What is purpose of this? We can copy os name that is listed in description field.
___
*[utils/jenkins/Jenkinsfile, line 48 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMes4wKwVsvN229-r6-48:-MFAzwco85kD42J2SjJ6:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/Jenkinsfile#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please make this default to "no"
</blockquote></details>

done
___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MF_y9DU3xsBYYnHWnqe:b-6os3i1) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually, since you want to run it every time before run-bindings.sh, you can just skip it. We use it once in a while, when re-building our docker image.
Please remove execution of `install-bindings-dependencies.sh` and hence you can omit these extensive checks below (I guess)
</blockquote></details>

I've removed install-bindings-dependencies.sh but leaved these cleanup below. unfortunately binding.sh installs libpmemkv, which will conflict with "normal" tests.
___
*[utils/jenkins/scripts/common.sh, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMfSUO6G9SRJCSl-r6-19:-MFB-fqaAhH2evhhsNgs:b-zd56p7) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there are also two issues next to "libpmemobj++":
1. there's weird "," at the beginning, and
2. there's definitely unnecessary "j" in pkg-config command param
</blockquote></details>

fixed, thanks!
___
*[utils/jenkins/scripts/common.sh, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-MDnSQL84P81BEtnB0b-:-MFB-aq677NEvIugI1Xi:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`echo 'libpmemobj++ not found'` - you've missed "++" part
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-08-31 15:15 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 143 at r1](https://reviewable.io/reviews/pmem/pmemkv/709#-M9O8Q1P64Hs5dMTMKL7:-MG43aTg7Fd70Jv3pT2k:b-64rbv6) ([raw file](https://github.com/pmem/pmemkv/blob/935c5991d0a40630032016cebf3cc8bd479b4bab/utils/jenkins/Jenkinsfile#L143)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

not sure now if remove or not :p
</blockquote></details>

please leave it as is :) 


<!-- Sent from Reviewable.io -->

2020-09-01 08:32 UTC, karczex commented
___
*[utils/jenkins/pmemkv_linux.jenkins, line 105 at r8](https://reviewable.io/reviews/pmem/pmemkv/709#-MG7lnd07EMjvj24_Mqg:-MG7lnd07EMjvj24_Mqh:b-e572ve) ([raw file](https://github.com/pmem/pmemkv/blob/2b3e619291c2b596b73e4049dc37eb575c79817b/utils/jenkins/pmemkv_linux.jenkins#L105)):*
Options in run-build.sh may vary between branches (and BRANCH is parameter) 
> ```
> (tests_gcc_debug_cpp11 tests_gcc_debug_cpp14 test_release_installation tests_clang_release_cpp20
> ```


<!-- Sent from Reviewable.io -->

2020-09-01 09:19 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 143 at r1](https://reviewable.io/reviews/pmem/pmemkv/709#-M9O8Q1P64Hs5dMTMKL7:-MG7x4nh1UOLwuK-XVbu:b32wtd) ([raw file](https://github.com/pmem/pmemkv/blob/935c5991d0a40630032016cebf3cc8bd479b4bab/utils/jenkins/Jenkinsfile#L143)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

please leave it as is :) 
</blockquote></details>

ok
___
*[utils/jenkins/pmemkv_linux.jenkins, line 105 at r8](https://reviewable.io/reviews/pmem/pmemkv/709#-MG7lnd07EMjvj24_Mqg:-MG7xMKVA64GWQuz5OZ-:b-hiekii) ([raw file](https://github.com/pmem/pmemkv/blob/2b3e619291c2b596b73e4049dc37eb575c79817b/utils/jenkins/pmemkv_linux.jenkins#L105)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Options in run-build.sh may vary between branches (and BRANCH is parameter) 
> ```
> (tests_gcc_debug_cpp11 tests_gcc_debug_cpp14 test_release_installation tests_clang_release_cpp20
> ```



</blockquote></details>

hmm, how to handle this? Set it as parameter?


<!-- Sent from Reviewable.io -->

2020-09-01 14:47 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMes4wKwVsvN229-r6-19:-MG97ZNE8LREYkq8JZf0:b-7j4avj) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/Jenkinsfile#L19)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

What is purpose of this? We can copy os name that is listed in description field.
</blockquote></details>

Please leave it as is.
___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MG96jGz0ms2C2GJ5QOJ:b7t4ied) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

I've removed install-bindings-dependencies.sh but leaved these cleanup below. unfortunately binding.sh installs libpmemkv, which will conflict with "normal" tests.
</blockquote></details>

I suggest to remove binding tests (at least for this PR), as it should simplify environment setup. If needed in the future, we may do some separate jobs in bindings repositories. 


<!-- Sent from Reviewable.io -->

2020-09-10 11:37 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 2 of 5 files reviewed, 23 unresolved discussions (waiting on @karczex, @lukaszstolarczuk, and @nedved1)

___
*[utils/jenkins/Jenkinsfile, line 48 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrmq_j6T5UrV5fFvbH:-MGrmq_j6T5UrV5fFvbI:bov28y3) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/Jenkinsfile#L48)):*
> ```Groovy
> 		defaultValue('tests_gcc_debug_cpp11 tests_gcc_debug_cpp14 test_release_installation tests_clang_release_cpp20')
> 		trim(true)
> 		description("Test options from run-buil.sh. Used in 'normal' test-type")
> ```

I'd re-write it like, e.g.
`Test builds, as defined in run-build.sh`

The rest of this description does not make sense. However, you can point out, that the default value was taken from "normal" tests, if you feel like it.
___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MGrnZZgAY0bE8yeaDFP:b8kkktr) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

I suggest to remove binding tests (at least for this PR), as it should simplify environment setup. If needed in the future, we may do some separate jobs in bindings repositories. 
</blockquote></details>

Since they work for now, maybe it's not worth removing it, after all...?
___
*[utils/jenkins/README.md, line 4 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrhnilAIu4YChmP9rW:-MGrhnilAIu4YChmP9rX:brgux3v) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L4)):*
> ```Markdown
> 
> ## Overview
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. It's functionality can be expanded thru installing plugins.
> ```

`It's functionality` -> `Its functionality`
___
*[utils/jenkins/README.md, line 4 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrhuhQ9S7I-Cap113Q:-MGrhuhRBvGag2qFXaaV:bnyhvxe) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L4)):*
> ```Markdown
> 
> ## Overview
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. It's functionality can be expanded thru installing plugins.
> ```

`thru`? -> `expanded by`
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriHx77ydgjj8itPW1:-MGriHx77ydgjj8itPW2:b8fz7ub) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. It's functionality can be expanded thru installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is lunched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which are called Nodes. Jenkinsfile and pipeline are located in utils/jenkins/ folder.
> ```

`launched`
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriUnC4Tr-alXn7bhd:-MGriUnC4Tr-alXn7bhe:b-15pomp) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. It's functionality can be expanded thru installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is lunched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which are called Nodes. Jenkinsfile and pipeline are located in utils/jenkins/ folder.
> ```

DUT is singular, so `which is called: Node.`
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriaL22oeBP99Z9Mvo:-MGriaL22oeBP99Z9Mvp:bfrpqmc) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. It's functionality can be expanded thru installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is lunched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which are called Nodes. Jenkinsfile and pipeline are located in utils/jenkins/ folder.
> ```

pls drop: `Jenkinsfile and pipeline are located in utils/jenkins/ folder.`, it's obvious
___
*[utils/jenkins/README.md, line 13 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrikil5l224mcTzZL7:-MGrikil5l224mcTzZL8:b-em98m3) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L13)):*
> ```Markdown
> - Blue Ocean
> - Branch API
> - Command Agent Launcher	
> ```

redaundant tab at the end of the line
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGritYR-hnj2ENxN5Wm:-MGritYR-hnj2ENxN5Wn:b-6wddrj) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
> ```Markdown
> 
> ### Overivew
> Jenkins can be configurated and manages "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add job that download jobs from remote repository and configure Jenkins. Instructions below allows to manually trigger creating/updating jobs but it is possible to trigger this job automatically with each push to target repository.
> ```

`configured and managed`
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrj2Y90j3hEcrH93iV:-MGrj2Y90j3hEcrH93iW:b-gb01ch) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
> ```Markdown
> 
> ### Overivew
> Jenkins can be configurated and manages "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add job that download jobs from remote repository and configure Jenkins. Instructions below allows to manually trigger creating/updating jobs but it is possible to trigger this job automatically with each push to target repository.
> ```

to add **a** job that download**s** jobs **definitions** from... and configure**s**
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrjLfs7KQrx910um_n:-MGrjLfs7KQrx910um_o:b-kdddjq) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
> ```Markdown
> 
> ### Overivew
> Jenkins can be configurated and manages "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add job that download jobs from remote repository and configure Jenkins [...]

2020-09-15 12:00 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 2 of 7 files reviewed, 23 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 48 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrmq_j6T5UrV5fFvbH:-MHGVTkh1BH1BqCBDpFU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/Jenkinsfile#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd re-write it like, e.g.
`Test builds, as defined in run-build.sh`

The rest of this description does not make sense. However, you can point out, that the default value was taken from "normal" tests, if you feel like it.
</blockquote></details>

Done.
___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MHGWMpy0P79hLqtMRIK:b-1wdplv) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Since they work for now, maybe it's not worth removing it, after all...?
</blockquote></details>

I've removed bindings and coverity tests for now, as it was agreed upon with @karczex. I've also removed checks in post build stage as it's now not needed.
___
*[utils/jenkins/README.md, line 4 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrhnilAIu4YChmP9rW:-MHGXo0B0j0NA4MxkZjw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`It's functionality` -> `Its functionality`
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 4 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrhuhQ9S7I-Cap113Q:-MHGXtTN4CeCjaKWfTZg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`thru`? -> `expanded by`
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriUnC4Tr-alXn7bhd:-MHGY2q_6L0pV-5CIfW-:bb7p5e3) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

DUT is singular, so `which is called: Node.`
</blockquote></details>

thx
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriaL22oeBP99Z9Mvo:-MHGYA7h9hIlO9ReY9n4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop: `Jenkinsfile and pipeline are located in utils/jenkins/ folder.`, it's obvious
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 6 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGriHx77ydgjj8itPW1:-MHGcZMkE7e8WQyf0Jn1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`launched`
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 13 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrikil5l224mcTzZL7:-MHGYLje9GhSBKLE1Rj8:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redaundant tab at the end of the line
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGritYR-hnj2ENxN5Wm:-MHGYexl1OtKOTEfi_zY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`configured and managed`
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrj2Y90j3hEcrH93iV:-MHGYfYZ9ae_D_Hm-opj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to add **a** job that download**s** jobs **definitions** from... and configure**s**
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrjLfs7KQrx910um_n:-MHGZ9vi61qAmjgh8Hlr:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**,** but it is possible
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 46 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrjlL62NkM_LZwCmjT:-MHGZJBeBamN4TENGogY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pipeline will **be executed** on **the** node specified by **the** "LABEL" field.
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 52 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrjx0oDdM7I8fcBnAO:-MHGZUMq81IIw7qnuepR:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Select**:** "mas**t**er" node.
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 57 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrlNioBhIsF_rOq9Nr:-MHGZd_w1Hxp1RR5k2oc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

generating job**s**
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 58 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrk8re6nAxrQaJrN2E:-MHGZfH-60vS116idxpi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

To add **a j**ob that generate**s**
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 69 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrkK7H1ObWir-rb0QQ:-MHGZjlB7PjGlzggziaT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`for eg.` -> `e.g.`
</blockquote></details>

Done.
___
*[utils/jenkins/README.md, line 77 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrkUalBwAYAsocFU_n:-MHG_-hD4daU_duzSE9z:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop `field`
</blockquote></details>

Done [...]

2020-09-15 12:02 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 2 of 7 files reviewed, 23 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMes4wKwVsvN229-r6-19:-MHGcyhF9V5W85LJ0xcr:b32wtd) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/Jenkinsfile#L19)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Please leave it as is.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2020-09-17 11:29 UTC, lukaszstolarczuk requested changes
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: all files reviewed, 4 unresolved discussions (waiting on @nedved1)

___
*[utils/jenkins/README.md, line 69 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrkK7H1ObWir-rb0QQ:-MHQodK93rJFcB8pqihd:bck9g2h) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L69)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`for` is redundant; **for example** == **e.g.**
___
*[utils/jenkins/scripts/createNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlHsX0DJbB_MSrC0B:-MHQlHsX0DJbB_MSrC0C:bwkh1ko) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L5)):*
> ```Shell
> # Copyright 2019-2020, Intel Corporation
> 
> # createNamespace.sh - Remove old namespaces and create new for pmemkv tests.
> ```

There's no script like this on the gitlab repo? I guess it'd be useful for all our repositories, not only pmemkv
___
*[utils/jenkins/scripts/createNamespace.sh, line 25 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlcE2-xCV-vUj-q6B:-MHQlcE2-xCV-vUj-q6C:bpn78wd) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L25)):*
> ```Shell
> 	echo "-h, --help       Print help and exit"
> 	echo "-d, --dax        Create dax device."
> 	echo "-p, --pmem       Create fsdax devixe and create mountpoint."
> ```

fsdax devi**c**e
___
*[utils/jenkins/scripts/removeNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQn49xBJXb08BbYyd9:-MHQn49xBJXb08BbYydA:bck5ika) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/removeNamespace.sh#L5)):*
> ```Shell
> # Copyright 2019-2020, Intel Corporation
> 
> # removeNamespace.sh - clear all existing namespaces.
> ```

if it removes all namespaces, pls rename to `removeNamespaces.sh`


<!-- Sent from Reviewable.io -->

2020-09-17 15:45 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MHGiWUD6Z8SgJUGdF-G:bp29nun) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

I've removed bindings and coverity tests for now, as it was agreed upon with @karczex. I've also removed checks in post build stage as it's now not needed.
</blockquote></details>

run-build.sh also installs pmemkv and won't be unninstalled
___
*[utils/jenkins/README.md, line 69 at r9](https://reviewable.io/reviews/pmem/pmemkv/709#-MGrkK7H1ObWir-rb0QQ:-MHRf5rdBBG3x4KFVhG7:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/f64f6b7dde087b6998413af02ed22cf24dd16567/utils/jenkins/README.md#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`for` is redundant; **for example** == **e.g.**
</blockquote></details>

done
___
*[utils/jenkins/scripts/common.sh, line 19 at r6](https://reviewable.io/reviews/pmem/pmemkv/709#-M9NiHMfSUO6G9SRJCSl-r6-19:-MHRfIK35EfnA1aZ7_wV:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv/blob/a4daec6ec8d65519cce5fc8ecf0ada1504b86be0/utils/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still not right:
`libpmemob++`
</blockquote></details>

done
___
*[utils/jenkins/scripts/createNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlHsX0DJbB_MSrC0B:-MHRfJrg3cQANM2-p1_C:b-bkd5sa) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

There's no script like this on the gitlab repo? I guess it'd be useful for all our repositories, not only pmemkv
</blockquote></details>

This is modified script for PMDK tests, stripped from all PMDK related stuff
___
*[utils/jenkins/scripts/createNamespace.sh, line 25 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlcE2-xCV-vUj-q6B:-MHRgW0_Ex6izHHj7Q0V:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

fsdax devi**c**e
</blockquote></details>

Done.
___
*[utils/jenkins/scripts/removeNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQn49xBJXb08BbYyd9:-MHRgyjI9V4CRRm15Dvd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/removeNamespace.sh#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if it removes all namespaces, pls rename to `removeNamespaces.sh`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-17 17:06 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MHS07jh4X_XpHLkkzvU:b-1ek4hv) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
> run-build.sh also installs pmemkv and won't be unninstalled

there were some changes along with this comment? I'm not sure what you meant by saying this...
___
*[utils/jenkins/scripts/createNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlHsX0DJbB_MSrC0B:-MHS0FzZ6-3ZuBFH1vEI:b-dktc9e) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

This is modified script for PMDK tests, stripped from all PMDK related stuff
</blockquote></details>

Let's mark this as done, but **I don't like the idea** of keeping these functions here and separately on other repositories (e.g. for libpmemobj-cpp or pmemkv-java, etc). PMDK part should be just excluded from this script on gitlab repo and PMDK's (or pmemkv's, if needed) part should be in a separate script(s), also there, on gitlab repo.


<!-- Sent from Reviewable.io -->

2020-09-18 11:30 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MHVwhQTEu2pHJuLKlhE:b-uxh0y1) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> run-build.sh also installs pmemkv and won't be unninstalled

there were some changes along with this comment? I'm not sure what you meant by saying this...
</blockquote></details>

I've removed the "/* Make sure to uninstall pmemkv from the DUT. */" section but put it back when I realized that  tests were failing without it.
___
*[utils/jenkins/scripts/createNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlHsX0DJbB_MSrC0B:-MHVxNEN4B4pM-4UZnvq:bhzdy0m) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Let's mark this as done, but **I don't like the idea** of keeping these functions here and separately on other repositories (e.g. for libpmemobj-cpp or pmemkv-java, etc). PMDK part should be just excluded from this script on gitlab repo and PMDK's (or pmemkv's, if needed) part should be in a separate script(s), also there, on gitlab repo.
</blockquote></details>

Gitlab repo is inside corporate network so these scripts won't be available to every pmemkv user. If you thin that these scripts should be common among other projects, why not store them in pmemkv? Anyway I think this is beyond the scope of this commit.


<!-- Sent from Reviewable.io -->

2020-09-18 11:38 UTC, lukaszstolarczuk approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[utils/jenkins/pmemkv_linux.jenkins, line 161 at r5](https://reviewable.io/reviews/pmem/pmemkv/709#-MDU_1N6-juGyHiQplRG:-MHW-L9S5Ji9N-iabO66:bb6o92h) ([raw file](https://github.com/pmem/pmemkv/blob/b4a54f726827edc9d578f242359555e693cf554d/utils/jenkins/pmemkv_linux.jenkins#L161)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

I've removed the "/* Make sure to uninstall pmemkv from the DUT. */" section but put it back when I realized that  tests were failing without it.
</blockquote></details>

:ok:
___
*[utils/jenkins/scripts/createNamespace.sh, line 5 at r10](https://reviewable.io/reviews/pmem/pmemkv/709#-MHQlHsX0DJbB_MSrC0B:-MHW-R-q-QOMBXPawdWL:bb6mt9b) ([raw file](https://github.com/pmem/pmemkv/blob/35d0e02a32bffb572ce515fd0e73686d7af1112b/utils/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Gitlab repo is inside corporate network so these scripts won't be available to every pmemkv user. If you thin that these scripts should be common among other projects, why not store them in pmemkv? Anyway I think this is beyond the scope of this commit.
</blockquote></details>

:+1:


<!-- Sent from Reviewable.io -->

2020-09-22 11:35 UTC, karczex reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/709#-:-MHpaGVg-eT1Z3_F0eez:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 11:39 UTC, merged