Config setters
pmem/pmemkv pull request #722
Opened 2020-07-07 15:26 UTC by karczex

2020-07-09 07:23 UTC, karczex commented
___
*[examples/pmemkv_basic_c/pmemkv_basic.c, line 49 at r3](https://reviewable.io/reviews/pmem/pmemkv/722#-MBmQLU60-GU-VijnI-2:-MBmS8dA4p-jUSCyC2Mn:bpe0rr1) ([raw file](https://github.com/pmem/pmemkv/blob/3beb8c33b7a7e6b6c5080aab31182931dc906dcf/examples/pmemkv_basic_c/pmemkv_basic.c#L49)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You did you change it back to assert? config puts can also fail
</blockquote></details>

I just fail rebasing. 


<!-- Sent from Reviewable.io -->

2020-08-18 12:00 UTC, lukaszstolarczuk commented
ref.  #440

2020-08-20 09:13 UTC, igchor reviewed
> Reviewed 8 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722)* status: 19 of 24 files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-08-20 17:38 UTC, lukaszstolarczuk requested changes
> Reviewed 1 of 9 files at r3, 1 of 4 files at r4, 4 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722)* status: 21 of 24 files reviewed, 41 unresolved discussions (waiting on @igchor and @karczex)

___
*[doc/CMakeLists.txt, line 4 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBknWN6BPCmTEoHUYk:-MFBknWN6BPCmTEoHUYl:b-eiyrwz) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/CMakeLists.txt#L4)):*
> ```CMake
> # Copyright 2019-2020, Intel Corporation
> 
> function(strip_example PATH  VAL)
> ```

double space between `PATH` and `VAL`
___
*[doc/CMakeLists.txt, line 6 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBkqqW8CNuZ2cmqbmE:-MFBkqqW8CNuZ2cmqbmF:bxfkjgm) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/CMakeLists.txt#L6)):*
> ```CMake
> function(strip_example PATH  VAL)
> 	# Prepare C_EXAMPLE content to inject, based on the code
> 	# of the 'examples/pmemkv_basic_c/pmemkv_basic.c' example;
> ```

pls update this comment
___
*[doc/libpmemkv.7.md, line 53 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnVQhAm5GL8hP522W:-MFBnVQhAm5GL8hP522X:b-hq52fk) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L53)):*
> ```Markdown
> Each engine can be manually turned on and off at build time, using CMake options. All engines listed here are enabled and ready to use.
> 
> To configure an engine, pmemkv_config is used (**libpmemkv_config**(3)). Below is a list of engines along with config parameters they expect. Each parameter has corresponding function (pmemkv_config_put_path, pmemkv_config_put_comparator, etc.), which guarantee type safety. For example to insert `path` parameter to the config, user should call pmemkv_config_put_path().
> ```

guarantee**s**
___
*[doc/libpmemkv.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnEc42wZIwIaA67ij:-MFBnEc42wZIwIaA67ik:b-47wecy) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L54)):*
> ```Markdown
> 
> To configure an engine, pmemkv_config is used (**libpmemkv_config**(3)). Below is a list of engines along with config parameters they expect. Each parameter has corresponding function (pmemkv_config_put_path, pmemkv_config_put_comparator, etc.), which guarantee type safety. For example to insert `path` parameter to the config, user should call pmemkv_config_put_path().
> For some use cases, like creating config from parsed input file, more convenient may be inserting parameters by its type instead of name. Each paramter has a certain type and may be inserted to a config using appropriate function (pmemkv_config_put_string, pmemkv_config_put_int64, etc.). For example, to insert a parameter of type `string`, `pmemkv_config_put_string` function may be used.
> ```

`parsed input file` -> `parsed input`
___
*[doc/libpmemkv.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnIyi0x507LYyXTUc:-MFBnIyjCkU-K5faB1f6:b-lcjj0q) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L54)):*
> ```Markdown
> 
> To configure an engine, pmemkv_config is used (**libpmemkv_config**(3)). Below is a list of engines along with config parameters they expect. Each parameter has corresponding function (pmemkv_config_put_path, pmemkv_config_put_comparator, etc.), which guarantee type safety. For example to insert `path` parameter to the config, user should call pmemkv_config_put_path().
> For some use cases, like creating config from parsed input file, more convenient may be inserting parameters by its type instead of name. Each paramter has a certain type and may be inserted to a config using appropriate function (pmemkv_config_put_string, pmemkv_config_put_int64, etc.). For example, to insert a parameter of type `string`, `pmemkv_config_put_string` function may be used.
> ```

`, more convenient may be inserting` -> `, it may be more convenient to insert`
___
*[doc/libpmemkv.7.md, line 55 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnuqn64_oDEapuejt:-MFBnuqn64_oDEapueju:bsxk3py) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L55)):*
> ```Markdown
> To configure an engine, pmemkv_config is used (**libpmemkv_config**(3)). Below is a list of engines along with config parameters they expect. Each parameter has corresponding function (pmemkv_config_put_path, pmemkv_config_put_comparator, etc.), which guarantee type safety. For example to insert `path` parameter to the config, user should call pmemkv_config_put_path().
> For some use cases, like creating config from parsed input file, more convenient may be inserting parameters by its type instead of name. Each paramter has a certain type and may be inserted to a config using appropriate function (pmemkv_config_put_string, pmemkv_config_put_int64, etc.). For example, to insert a parameter of type `string`, `pmemkv_config_put_string` function may be used.
> Those two ways of inserting parameters into config may be used together or interchangeably.
> ```

aren't `together` and `interchangeably` synonyms in this context?
___
*[doc/libpmemkv.7.md, line 56 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnkR746VuSgX1kHyP:-MFBnkR746VuSgX1kHyQ:b8czlfu) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L56)):*
> ```Markdown
> For some use cases, like creating config from parsed input file, more convenient may be inserting parameters by its type instead of name. Each paramter has a certain type and may be inserted to a config using appropriate function (pmemkv_config_put_string, pmemkv_config_put_int64, etc.). For example, to insert a parameter of type `string`, `pmemkv_config_put_string` function may be used.
> Those two ways of inserting parameters into config may be used together or interchangeably.
> For description of pmemkv core API see **libpmemkv**(3).
> ```

add one empty line before this one
___
*[doc/libpmemkv_config.3.md.in, line 96 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoFNeDYYBkVFJpEID:-MFBoFNeDYYBkVFJpEIE:b2lkprh) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L96)):*
> ```
> `int pmemkv_config_put_size(pmemkv_config *config, uint64_t value);`
> 
> :	Puts `value` value to a config at key `size`. This function provide type
> ```

drop second "value", perhaps..?
___
*[doc/libpmemkv_config.3.md.in, line 96 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoM7c3Tw-KaiLPLAX:-MFBoM7c3Tw-KaiLPLAY:bz8d43s) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L96)):*
> ```
> `int pmemkv_config_put_size(pmemkv_config *config, uint64_t value);`
> 
> :	Puts `value` value to a config at key `size`. This function provide type
> ```

provide**s** (please fix all occurrences)
___
*[doc/libpmemkv_config.3.md.in, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoVlF-wZJTBvmlaDL:-MFBoVlF-wZJTBvmlaDM:bwa5se7) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L97)):*
> ```
> 
> :	Puts `value` value to a config at key `size`. This function provide type
> 	safety for size parameter
> ```

put full-stop at the end of the sentence; pls fix in all sentences
___
*[doc/libpmemkv_config.3.md.in, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBolXc4wUz4css0Jwu:-MFBolXc4wUz4css0Jwv:bgppr63) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L97)):*
> ```
> 
> :	Puts `value` value to a config at key `size`. This function provide type
> 	safety for size parameter
> ```

perhaps `**size**`
___
*[doc/libpmemkv_confi [...]

2020-08-25 07:59 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722)* status: 17 of 24 files reviewed, 41 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[doc/CMakeLists.txt, line 4 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBknWN6BPCmTEoHUYk:-MFEymxO-Lpw7V4CMMyn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/CMakeLists.txt#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

double space between `PATH` and `VAL`
</blockquote></details>

Done.
___
*[doc/CMakeLists.txt, line 6 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBkqqW8CNuZ2cmqbmE:-MFF-CA3BKTgJf9BGn0Q:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/CMakeLists.txt#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update this comment
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 53 at r2](https://reviewable.io/reviews/pmem/pmemkv/722#-MBhtzL3DAfaCDpEAOby:-MFF-WN9Dla5E4rnQDm8:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/da25e020f17578bdf672c4672d63e3a0466d3e3f/doc/libpmemkv.7.md#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please update this info. Say something like - to set path, pmemkv_config_put_path should be used.
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 53 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnVQhAm5GL8hP522W:-MFF-WC6DiesfLumm7qf:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

guarantee**s**
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnEc42wZIwIaA67ij:-MFF-apcAGEuew2Ke5Ys:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`parsed input file` -> `parsed input`
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 54 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnIyi0x507LYyXTUc:-MFF-mgL6abGOLgrNNrC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`, more convenient may be inserting` -> `, it may be more convenient to insert`
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 55 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnuqn64_oDEapuejt:-MFF-vfM0JoV_3Eibi6A:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

aren't `together` and `interchangeably` synonyms in this context?
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 56 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBnkR746VuSgX1kHyP:-MFF-yIT9z4t2CSTl5X5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv.7.md#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add one empty line before this one
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 96 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoFNeDYYBkVFJpEID:-MFF6kNO7WKkb55qadyg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop second "value", perhaps..?
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 96 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoM7c3Tw-KaiLPLAX:-MFF6qMu6GfRhC7DNcJV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

provide**s** (please fix all occurrences)
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoVlF-wZJTBvmlaDL:-MFF763d6Fhs8U26Z6CX:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put full-stop at the end of the sentence; pls fix in all sentences
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBolXc4wUz4css0Jwu:-MFF7JHX4SIlHiC_SLa3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps `**size**`
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 102 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBooaU8dKjxZV5Shmh:-MFF7aAu-kUBOw3zrYOV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps also `**path**` (without the \`)
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 106 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBp6IU9yiWBqsQjRf0:-MFF7oKv1x4EzIzPfOM5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L106)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`config,` ->  `config.` (full-stop instead of comma)
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 106 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBpFmR7oEaxGASO7lI:-MFF7wG9-DBKvnHKYnXu:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L106)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`For supporting engines If...` -> `In engines which supports this parameter, if...`
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 107 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBpRAm8FFdAqzIGPk7:-MFF82ZnELbgarZ7mZib:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L107)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

opens **the** file
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 111 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBpibrA8pCvs29cdSB:-MFF8DfPBcYdN34zLEaO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L111)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`pmemkv_comaprator` (misspell) -> _comparator
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 111 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBpqsjBUz_a6jyRsE6:-MFF8OqV6PvUK2Q-cznw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7 [...]

2020-08-27 13:18 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722)* status: 15 of 24 files reviewed, 41 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[doc/libpmemkv.7.md, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv/722#-MBhu6Ug0p-5PbeYUDMK:-MFjyBrRCrPpKAhEEPo-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/da25e020f17578bdf672c4672d63e3a0466d3e3f/doc/libpmemkv.7.md#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please update also libpmemkv_config.3

At least:
- Add those new methods there and describe them (at the top of the manpage?)
- Update code examples (putting comparator)
- Add info, that put_size/path/... should be preffered over the put_object etc.
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBoI5Y0q7RXQDMq1Hy:-MFjuXkZ35zsnzIX0X8G:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (x2)
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 232 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBtWYDEAk0is0TW1rI:-MFjvJh19Eiop_lAs47R:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L232)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps similar description as I suggest in the comment below
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 236 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBlzHE9FHiwLXrpkWC:-MFjsa-P2cumh0hyYAtG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L236)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps rename to something like `CONFIG_BASIC_EXAMPLE`
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 241 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBqSAI3IPrfipdmMLv:-MFjt1lP6b_WJwIchIPn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L241)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we don't use `pmemkv_config_put_string` or `_put_uint64` methods in this example ;) perhaps just say something like: "Usage of config functions to set and get data based on their data type, e.g. 'pmemkv_config_put_int64()' or 'pmemkv_config_put_object()'."
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 244 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBlr7b3_72s9LZ3G0X:-MFk3SIi5VNlND2LN08f:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/doc/libpmemkv_config.3.md.in#L244)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps rename to something like `CONFIG_TYPE_BASED_EXAMPLE`
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBrUfC1nNPs9eo-UTD:-MFk3TIlBnWNIfU0Mw5E:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls extend the comment a little bit; and consider renaming these config's examples
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 47 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBriQJ8Dy-kOkPuenA:-MFjtJT223YMZ1pQxwrJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

engine (misspell)
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 48 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBrk775PYISdYf_zra:-MFjtTPv0XBAYHp4_bqv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it is **a** path
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 49 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBrnCJ-ufNOiO975WU:-MFjtXEt8K5a0QP7TY5h:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a path
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 53 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBrvaqAQ7fnODKGQci:-MFjtaKv9GnvzdwJ1pF2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

start with upper case (`Specifies`
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 68 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBsAkv5JELsgKOfA73:-MFju2a47BsIMvjHGGoq:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Add**s** **p**ointer
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 68 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBsI__9LV-a5loa1Wi:-MFju2z80p50I_LXtbEv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (same reference as in my prev. comment)
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_basic_config.c, line 69 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBsS8U4gyw88jU-cQm:-MFk25hK4V14HhN1T7yi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_basic_config.c#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this sentence is a little complicated...? "adds pointer to oid .. which points to engine data to config" something is no-yes ;)
</blockquote></details>

Done.
___
*[examples/pmemkv_config_c/pmemkv_config.c, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBrXbz59OcWb07Xt40:-MFk28eF1Qde64fMnXkO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/examples/pmemkv_config_c/pmemkv_config.c#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 694 at r6](https://reviewable.io/reviews/pmem/pmemkv/722#-MFBuKjJ3I3ulEjJXzam:-MFjxxGwB4uw_CMa9yx0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7a16372f87d827c0c11ba7cf558d426742286732/src/libpmemkv.hpp#L694)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockq [...]

2020-08-31 11:07 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r7, 3 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722#-:-MG3BjIc99jHgCCr5ccS:bnfp4nl)* status: 19 of 24 files reviewed, 39 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-09-02 06:26 UTC, szyrom approved these changes
> Reviewed 5 of 19 files at r1, 2 of 9 files at r3, 3 of 4 files at r4, 5 of 13 files at r5, 1 of 1 files at r6, 4 of 6 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/722)* status: all files reviewed, 39 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-09-02 06:27 UTC, merged