Update CMake files
pmem/pmemkv pull request #808
Opened 2020-10-05 19:31 UTC by lukaszstolarczuk

- set min required version to lower values than there were (for top-level and examples' CMake) - it's arbitrarily set to 3.3,
- fix comparator's example project's language,
- set compatibility test's CMake to higher value of min cmake required version (3.13) - it uses 'target_link_directories'.

2020-10-06 08:31 UTC, igchor requested changes
Did you check that it actually works for 3.3? The built-in cmake check is not always reliable.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/808#-:-MIx1IeL1cYK5ohF5vAF:bhyhtbg)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 08:56 UTC, karczex reviewed
it's probably a good moment to check out this tool https://github.com/nlohmann/cmake_min_version

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/808#-:-MIx6j-B49lP-7A_iUcX:b-xla925)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 08:58 UTC, lukaszstolarczuk reviewed
@igchor - check with many options turned on/off - seems to work just fine

@karczex - see commit message of the first commit :wink: 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/808#-:-MIx7Ki197xd92K8NXQy:b-5bo8gk)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-07 07:54 UTC, szyrom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/808#-:-MJ12Y8J0B5OQY57xtfY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-08 05:52 UTC, igchor approved these changes
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/808)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-08 05:52 UTC, merged