WIP: Implement generic transaction class and expose it through C API
pmem/pmemkv pull request #830
Opened 2020-10-19 13:21 UTC by igchor

Also, add transactional support for csmap.

2020-11-16 12:03 UTC, KFilipek reviewed
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-19 08:58 UTC, szyrom reviewed
we need examples and a documented policy for transactions by concurrent engines (optimistic or pessimistic concurrency control).

> Reviewed 8 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MMUhMWq9QIyT8zMwqp2:byb0mx3)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[src/libpmemkv.hpp, line 202 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUai9i-CkdAboSftst:-MMUai9i-CkdAboSftsu:b-doxu0z) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/libpmemkv.hpp#L202)):*
> ```cpp
> 	\brief Pmemkv transaction handle.
> 
> 	This class allows grouping several operations into one atomic action.
> ```

how about adding tx::remove as a tx API.
RocksDB transactionDB provides put, delete, merge. I think put and remove in our case will be enough. In this case, we can rephrase a class description and mention these two methods 
___
*[src/engines-experimental/radix.h, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUflK26bBuyFmg9wZq:-MMUflK26bBuyFmg9wZr:b-m7x1zo) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.h#L52)):*
> ```objc
> 	pmem::obj::pool_base &pop;
> 	std::vector<std::pair<std::string, std::string>> v;
> 	map_type *container;
> ```

can we move these private fields to base class?
___
*[src/engines-experimental/radix.cc, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUgpMd6xUV-O0Y5ktr:-MMUgpMeCqJ2i9tu_gzD:b-7cz2n4) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.cc#L22)):*
> ```cpp
> status transaction::put(string_view key, string_view value)
> {
> 	v.emplace_back(std::piecewise_construct,
> ```

maybe we should try v.emplace_back and eventually catch std::bad_alloc?
I can imagine a use-case when a user tries to batch put plenty of data/records atomically


<!-- Sent from Reviewable.io -->

2020-11-19 14:09 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)

___
*[src/libpmemkv.hpp, line 202 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUai9i-CkdAboSftst:-MMVpI3p47I_a0ecFGdw:b-ufkkc8) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/libpmemkv.hpp#L202)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

how about adding tx::remove as a tx API.
RocksDB transactionDB provides put, delete, merge. I think put and remove in our case will be enough. In this case, we can rephrase a class description and mention these two methods 
</blockquote></details>

Right, I'll add this. Initially I didn't want to do that because csmap cannot support it (since we would have to take global, unique lock in each iterator) but I guess csmap can just return not_supported.
___
*[src/engines-experimental/radix.h, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUflK26bBuyFmg9wZq:-MMVSmCFEK9x1sKV-olw:b-scnrmg) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.h#L52)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

can we move these private fields to base class?
</blockquote></details>

not really, this is an implementation detail of radix transaction
___
*[src/engines-experimental/radix.cc, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUgpMd6xUV-O0Y5ktr:-MMVSuYQAdiZEQ48Pyh7:bc3vfbu) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.cc#L22)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

maybe we should try v.emplace_back and eventually catch std::bad_alloc?
I can imagine a use-case when a user tries to batch put plenty of data/records atomically
</blockquote></details>

We're already catching bad_alloc at libpmemkb.cc level in catch_and_return status - it will be translated to PMEMKV_STATUS_OUT_OF_MEMORY.


<!-- Sent from Reviewable.io -->

2020-11-20 10:56 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @szyrom)

___
*[src/libpmemkv.hpp, line 202 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUai9i-CkdAboSftst:-MM_HuQM2mwjkUV7kTbD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/libpmemkv.hpp#L202)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, I'll add this. Initially I didn't want to do that because csmap cannot support it (since we would have to take global, unique lock in each iterator) but I guess csmap can just return not_supported.
</blockquote></details>

Done.
___
*[src/engines-experimental/radix.h, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUflK26bBuyFmg9wZq:-MM_Hvot1xdVPD3G8u3V:bq6mush) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.h#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not really, this is an implementation detail of radix transaction
</blockquote></details>

Actually, I refactored it a bit.


<!-- Sent from Reviewable.io -->

2020-11-20 16:04 UTC, szyrom reviewed
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/engines-experimental/radix.h, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUflK26bBuyFmg9wZq:-MMaO7hd7t9jyyKkdep1:b-ogndf0) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.h#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually, I refactored it a bit.
</blockquote></details>

hm, now when you've provided an additional abstraction dram_log, maybe it should be in a base class? Will there be an engine, for which we will be logging batch operation somewhere else? 


<!-- Sent from Reviewable.io -->

2020-11-23 10:32 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 1 unresolved discussion (waiting on @szyrom)

___
*[src/engines-experimental/radix.h, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv/830#-MMUflK26bBuyFmg9wZq:-MMoe4M01gMRsaoFeHJi:b-tqy6c1) ([raw file](https://github.com/pmem/pmemkv/blob/543be2876711e3304010b09d5dd5e653c0cf6545/src/engines-experimental/radix.h#L52)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

hm, now when you've provided an additional abstraction dram_log, maybe it should be in a base class? Will there be an engine, for which we will be logging batch operation somewhere else? 
</blockquote></details>

In future, I believe yes - we can use independent txs to just directly allocate data on pmem. dram_log would then only be used by volatile engines. Besides, the implementation of commit() will be different for all engines so I believe it's better to have dram_log where the implementation is.


<!-- Sent from Reviewable.io -->

2020-11-30 11:34 UTC, pbalcer reviewed
I'm still unconvinced as to whether or not this should be called a "transaction" if there's no way to perform a read. Maybe let's call this "batch", and then expand it to a "transaction" once we are certain we can make a fully featured implementation.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MNNvGCADZM84fQHR5ug:b-65lzrg)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @igchor and @szyrom)

___
*[src/engines-experimental/radix.cc, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNNunKq-oSE_-Kou1_R:-MNNunKrBdayjegyv_kb:b-1s6yfw) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/src/engines-experimental/radix.cc#L20)):*
> ```cpp
> }
> 
> status transaction::put(string_view key, string_view value)
> ```

this implementation will make another copy of the objects, right?

Can't you just start the obj transaction immediately, and just insert elements? That way we don't have the extra copy.


<!-- Sent from Reviewable.io -->

2020-12-01 10:38 UTC, igchor reviewed
Right, I can change it for now. I basically wanted to make each iterator by default be it's own transaction.

So, basically, you could do:
it.read_for_update()
it.write_range()
it.commit() // this commit depends on read_for_update

or
it.read_for_udate()
it2.write_range()
// it2.commit() // does NOT depend on read_for_update
auto tx = db.tx_begin();
tx.add(it);
tx.add(it2);
tx.commit() // this commit depends on read_for_update

I'm not yet sure if this API is not too misleading but anyway, I'd like to have read/read_for_updates in iterators only. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MNSqPQe4c8B7ZI1O2nQ:b-vgyukl)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @pbalcer and @szyrom)

___
*[src/engines-experimental/radix.cc, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNNunKq-oSE_-Kou1_R:-MNSpvoT070IcEfBGDAQ:b-werv89) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/src/engines-experimental/radix.cc#L20)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

this implementation will make another copy of the objects, right?

Can't you just start the obj transaction immediately, and just insert elements? That way we don't have the extra copy.
</blockquote></details>

Right, we could do that but then: a) we would not be able to start multiple txs, b) the changes would be visible to all non-tx reads (like db.get()) c) if we do db.put() while holdind tx class those db.puts() would also be part of a tx

This could all be resolved by independex txs ;d


<!-- Sent from Reviewable.io -->

2020-12-01 12:52 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @pbalcer and @szyrom)

___
*[src/engines-experimental/radix.cc, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNNunKq-oSE_-Kou1_R:-MNTLpPN779rLf5U3-Uu:bri4h97) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/src/engines-experimental/radix.cc#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, we could do that but then: a) we would not be able to start multiple txs, b) the changes would be visible to all non-tx reads (like db.get()) c) if we do db.put() while holdind tx class those db.puts() would also be part of a tx

This could all be resolved by independex txs ;d
</blockquote></details>

(maybe not b) but with independent txs we could just allocate the node of radix_tree on pmem immediately and then insert the node on commit). 


<!-- Sent from Reviewable.io -->

2020-12-01 12:52 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @pbalcer and @szyrom)

___
*[src/engines-experimental/radix.cc, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNNunKq-oSE_-Kou1_R:-MNTM3w-ApJP7H1tvL2N:bvehdzm) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/src/engines-experimental/radix.cc#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

(maybe not b) but with independent txs we could just allocate the node of radix_tree on pmem immediately and then insert the node on commit). 
</blockquote></details>

So, I think it would be better to stay with the current implementation and switch to independex txs (or redo logs if we add support for action/intent API in c++ containers).


<!-- Sent from Reviewable.io -->

2020-12-01 13:45 UTC, KFilipek reviewed
> Reviewed 8 of 10 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor, @pbalcer, and @szyrom)

___
*[examples/pmemkv_transaction_cpp/CMakeLists.txt, line 2 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNTYA0B-pWSISIlXLbZ:-MNTYA0B-pWSISIlXLb_:bvvpo6c) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/examples/pmemkv_transaction_cpp/CMakeLists.txt#L2)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2019-2020, Intel Corporation
> ```

I see, that is new file, so only 2020
___
*[examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNTXzwK3l2d9b_JmBu_:-MNTXzwK3l2d9b_JmBua:b-krqmkm) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp#L17)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #define ASSERT(expr)                                                                     \
> 	do {                                                                             \
> 		if (!(expr))                                                             \
> 			std::cout << pmemkv_errormsg() << std::endl;                     \
> 		assert(expr);                                                            \
> ```
</details>

Please format line break symbols


<!-- Sent from Reviewable.io -->

2020-12-02 09:52 UTC, pbalcer reviewed
The second approach looks cool, but I'm not sure how you'd implement that. If you don't have a transaction started, then you can do a "read_for_update" or a "write", right? unless you'd use actions or something like `std::future`?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MNXr4Gd1zguIfcvcvLh:b-fmrhb6)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor, @pbalcer, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-02 09:59 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @szyrom)

___
*[src/engines-experimental/radix.cc, line 20 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNNunKq-oSE_-Kou1_R:-MNXt1ThBFtf0RiwO859:b-pqov82) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/src/engines-experimental/radix.cc#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, I think it would be better to stay with the current implementation and switch to independex txs (or redo logs if we add support for action/intent API in c++ containers).
</blockquote></details>

makes sense


<!-- Sent from Reviewable.io -->

2020-12-03 14:13 UTC, igchor reviewed
Right. for normal, "undo" based transaction it would probably be impossible (unless we could have independent txs and somehow merge them - so that we can commit multiple txs in a single step, but that would probably pretty hard ;d). We could do that only if we 'd rely on actions or just in-dram logging.

For undo based approached I agree that we would need to have a tx started before calling write()/read_for_update. In that case, we can probably just accept a tx. Maybe then we could have (the order of tx add is switched):

```
tx.add(it);
tx.add(it2);
it.read_for_udate()
it2.write_range()
// it2.commit() // FAILS, iterator added to a tx
auto tx = db.tx_begin();
tx.commit() // this commit depends on read_for_update
```

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MNcvt1y-TuzE5OZmcub:bruequy)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-07 10:22 UTC, szyrom reviewed
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-12-09 15:19 UTC, igchor reviewed
Right now, the pmemkv_tx object is destroyed automatically on commit (if it succeeds) or on abort. I was thinking that exposing a separate function to destroy the pmemkv_tx could be better but I realized that having:
```
pmemkv_tx_remove //remove element from db
pmemkv_tx_delete // destroys the pmemkv_tx_object
```

might bit a bit misleading. What do you think?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MO73z5mA_kStVqPNONj:bd5xlir)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-12-17 09:21 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 9 of 22 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @szyrom)

___
*[examples/pmemkv_transaction_cpp/CMakeLists.txt, line 2 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNTYA0B-pWSISIlXLbZ:-MOk-N7rDAzyZ7gyhiw5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/examples/pmemkv_transaction_cpp/CMakeLists.txt#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I see, that is new file, so only 2020
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv/830#-MNTXzwK3l2d9b_JmBu_:-MO75LrO8R2wC05pIFgU:bj15qpi) ([raw file](https://github.com/pmem/pmemkv/blob/05ef45abf72252300681c52ca9c8a20e96e068f4/examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #define ASSERT(expr)                                                                     \
> 	do {                                                                             \
> 		if (!(expr))                                                             \
> 			std::cout << pmemkv_errormsg() << std::endl;                     \
> 		assert(expr);                                                            \
> ```
Please format line break symbols
</blockquote></details>

It is formatted (with clang-format) and looks ok in vscode for example but github has some other display settings (tab width or something) so it seems broken.


<!-- Sent from Reviewable.io -->

2020-12-17 12:43 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r3, 9 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 18 of 22 files reviewed, 21 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[doc/libpmemkv_tx.3.md.in, line 41 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZW0B4kA8jGruzMqd:-MOkZW0B4kA8jGruzMqe:b-fupubk) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L41)):*
> ```
> # DESCRIPTION #
> 
> The transaction allows grouping put and remove operations into a single atomic action
> ```

perhaps: \`put\` and \`remove\`
___
*[doc/libpmemkv_tx.3.md.in, line 53 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZr0aCHGXWkN3iimY:-MOkZr0aCHGXWkN3iimZ:b-j03clw) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L53)):*
> ```
> `int pmemkv_tx_put(pmemkv_tx *tx, const char *k, size_t kb, const char *v, size_t vb);`
> 
> :   Inserts a key-value pair into pmemkv database. `kb` is the length of key `k` and `vb` is the length of value `v`.
> ```

of **the** key
___
*[doc/libpmemkv_tx.3.md.in, line 54 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc5Mz7xeV4NiRc5vY:-MOkc5Mz7xeV4NiRc5vZ:b-f6mq8i) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L54)):*
> ```
> 
> :   Inserts a key-value pair into pmemkv database. `kb` is the length of key `k` and `vb` is the length of value `v`.
> 	When this function returns, caller is free to reuse both buffers. The inserted element is visible only after calling commit.
> ```

maybe to be more precise - `calling pmemkv_tx_commit.` ...?
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc8jIEhN_VlEG6sQD:-MOkc8jIEhN_VlEG6sQE:b-4dbn7d) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
> ```
> `int pmemkv_tx_remove(pmemkv_tx *tx, const char *k, size_t kb);`
> 
> :   Removes record with key `k` of length `kb`. The removed elements are still visible until calling commit.
> ```

. (maybe to be more precise - `calling pmemkv_tx_commit.` ...?)
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkgRwKCMk-BmKCfnqv:-MOkgRwKCMk-BmKCfnqw:b1mbl69) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
> ```
> `int pmemkv_tx_remove(pmemkv_tx *tx, const char *k, size_t kb);`
> 
> :   Removes record with key `k` of length `kb`. The removed elements are still visible until calling commit.
> ```

. (of the key)
___
*[doc/libpmemkv_tx.3.md.in, line 68 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZMMx7Q-3dZmlailm:-MOkZMMx7Q-3dZmlailn:b-to326v) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L68)):*
> ```
> `void pmemkv_tx_abort(pmemkv_tx *tx);`
> 
> :   Discards all operations. 
> ```

whitespace at the end of the line
___
*[doc/libpmemkv_tx.3.md.in, line 68 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg_qY-9iogGxY0mGi:-MOkg_qY-9iogGxY0mGj:by2a5ou) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L68)):*
> ```
> `void pmemkv_tx_abort(pmemkv_tx *tx);`
> 
> :   Discards all operations. 
> ```

maybe more precise: **all uncommitted** ops ...?
___
*[doc/libpmemkv_tx.3.md.in, line 76 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkcMxFEMBIOGTzUpnS:-MOkcMxG7Pu3p-iKBe5y:bpggy6j) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L76)):*
> ```
> # EXAMPLE #
> 
> The following examples are taken from `examples/pmemkv_config_c` directory.
> ```

that's not true ;)
___
*[doc/libpmemkv_tx.3.md.in, line 86 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZ0BYBxHkUzbDtHuU:-MOkZ0BZEyAPLHeGeuFm:b-ljs2pr) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L86)):*
> ```
> ```
> 
> ## C++ EXAMPLE ##
> ```

hmm in C manpage? not sure if needed, unless you think it's good to see comparison
___
*[doc/libpmemkv_tx.3.md.in, line 96 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZ7IJ38GuX0nH8BAJ:-MOkZ7IJ38GuX0nH8BAK:bw0wpjl) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L96)):*
> ```
> # SEE ALSO #
> 
> **libpmemkv**(7), **libpmemkv**(3) and **<https://pmem.io>**
> ```

no new line at the end
___
*[examples/CMakeLists.txt, line 24 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkcVZq2oKtxrKg5xmO:-MOkcVZq2oKtxrKg5xmP:bf6e7k7) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/CMakeLists.txt#L24)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_comparator_cpp/*.cpp
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_comparator_c/*.c
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_transaction_cpp/*.cpp
> ```

whitespace check in any file - `/*.*`
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 5 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg0WE8pRyetHZ5Eex:-MOkg0WF2Ws_HmGBpYCZ:bfo6ziw) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L5)):*
> ```CMake
> 
> cmake_minimum_required(VERSION 3.3)
> project(pmemkv_transaction_cpp C)
> ```

pmemkv_transaction_c
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 7 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkclc8EbHoH2x4BihB:-MOkclc8EbHoH2x4BihC:bxnl3l5) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L7)):*
> ```CMake
> project(pmemkv_transaction_cpp C)
> 
> find_package(PkgConfig QUIET)
> ```

make it REQUIRED instead of QUIET, and then the whole 'if' below can be removed (error msg will be printed by find_package).
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 16 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkh7g57p8WfwB_WJST:-MOkh7g57p8WfwB_WJSU:b-krrm2a) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L16)):*
> ```CMake
> include_directories(${LIBPMEMKV_INCLUDE_DIRS})
> link_directories(${LIBPMEMKV_LIBRARY_DIRS})
> add_executable(pmemkv_transaction pmemkv_transaction.c)
> ```

exec name: pmemkv_transaction_c
___
*[examples/pmemkv_transaction_c/pmemkv_transaction.c, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkhyxl7CV-AyCzvB-O:-MOkhyxl7CV-AyCzvB-P:bs5nksz) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/pmemkv_transaction.c#L77)):*
> ```C
> 	/* Until transaction is committed, changes are not visible */
> 	s = pmemkv_exists(db, key1, strlen(key1));
> 	ASSERT(s == PMEMKV_STATUS_NOT_FOUND);
> ```

shouldn't this be OK ?
___
*[examples/pmemkv_transaction_c/pmemkv_transaction.c, line 88 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOki3_w8dmz-cUaKA5u:-MOki3_x528jv7NCiFul:b8zm237) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/pmemkv_transaction.c#L88)):*
> ```C
> 	/* Changes are now visible and pmemkv_tx object is destroyed */
> 	s = pmemkv_exists(db, key1, strlen(key1));
> 	ASSERT(s == PMEMKV_STATUS_OK);
> ```

and this NOT_FOUND, then
___
*[examples/pmemkv_transaction_cpp/CMakeLists.txt, line 7 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg4NLBtz5c_BV5Ysx:-MOkg4NLBtz5c_BV5Ysy:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_cpp/CMakeLists.txt#L7)):*
> ```CMake
> project(pmemkv_transac [...]

2020-12-17 14:32 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 5 of 22 files reviewed, 21 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[doc/libpmemkv_tx.3.md.in, line 41 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZW0B4kA8jGruzMqd:-MOkkfOuBR4VSdhkxlvO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps: \`put\` and \`remove\`
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 53 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZr0aCHGXWkN3iimY:-MOkkjy24h0dbyz-lpI9:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of **the** key
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 54 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc5Mz7xeV4NiRc5vY:-MOkkmGkA7ISi59IlFli:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe to be more precise - `calling pmemkv_tx_commit.` ...?
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkgRwKCMk-BmKCfnqv:-MOkkpZPCpokicxaXQ_W:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (of the key)
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc8jIEhN_VlEG6sQD:-MOkkpoo2PzpOtddIcFw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (maybe to be more precise - `calling pmemkv_tx_commit.` ...?)
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 68 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZMMx7Q-3dZmlailm:-MOkl-WJ7D-M0NBcIDM5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

whitespace at the end of the line
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 68 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg_qY-9iogGxY0mGi:-MOkl-tHCE63dfibkBk-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe more precise: **all uncommitted** ops ...?
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 76 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkcMxFEMBIOGTzUpnS:-MOkl6GX3AQrJwH-rb8z:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L76)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's not true ;)
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 86 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZ0BYBxHkUzbDtHuU:-MOklHAs7zmmIaTvG1CZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm in C manpage? not sure if needed, unless you think it's good to see comparison
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 96 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkZ7IJ38GuX0nH8BAJ:-MOklIUY0UJcmKcd6jPL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no new line at the end
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 24 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkcVZq2oKtxrKg5xmO:-MOklUYl8A-uIKhWDFhS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/CMakeLists.txt#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

whitespace check in any file - `/*.*`
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 5 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg0WE8pRyetHZ5Eex:-MOklf4VEB6cMYlZDTFw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pmemkv_transaction_c
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 7 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkclc8EbHoH2x4BihB:-MOkloPm-hQpbip9spQH:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it REQUIRED instead of QUIET, and then the whole 'if' below can be removed (error msg will be printed by find_package).
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_c/CMakeLists.txt, line 16 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkh7g57p8WfwB_WJST:-MOklwE6Cf9FQxdsmK37:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/CMakeLists.txt#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

exec name: pmemkv_transaction_c
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_c/pmemkv_transaction.c, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkhyxl7CV-AyCzvB-O:-MOkmsuA0kNBU1SkU5NP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/pmemkv_transaction.c#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't this be OK ?
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_c/pmemkv_transaction.c, line 88 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOki3_w8dmz-cUaKA5u:-MOkmt9OCwm7QA-z5PMy:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_c/pmemkv_transaction.c#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and this NOT_FOUND, then
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_cpp/CMakeLists.txt, line 7 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkg4NLBtz5c_BV5Ysx:-MOkmvzH4msyGt839A6s:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/examples/pmemkv_transaction_cpp/CMakeLists.txt#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_cpp/CMakeLists.txt, line 16 at r4] [...]

2020-12-18 13:21 UTC, lukaszstolarczuk reviewed
> Reviewed 10 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 14 of 22 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[doc/libpmemkv_tx.3.md.in, line 54 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc5Mz7xeV4NiRc5vY:-MOpjzwCCzzXUJUqN8Z7:b-qvbq5r) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

almost - `pmemobj`?
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc8jIEhN_VlEG6sQD:-MOptdbvDSNSJgGAzg81:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[doc/libpmemkv_tx.3.md.in, line 75 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOptzTR5AbQAx5_ViGG:-MOptzTR5AbQAx5_ViGH:b2gayo6) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L75)):*
> ```
> `void pmemkv_tx_end(pmemkv_tx *tx);`
> 
> :	Deletes the pmemkv transaction.
> ```

maybe pmemkv transaction **object** (?)
___
*[doc/libpmemkv_tx.3.md.in, line 75 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpu4CzEiBmQXJRUnqS:-MOpu4CzEiBmQXJRUnqT:bl60op8) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L75)):*
> ```
> `void pmemkv_tx_end(pmemkv_tx *tx);`
> 
> :	Deletes the pmemkv transaction.
> ```

add info that it aborts the uncommitted changes (does it, right?)
___
*[examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpyqKI0KyExCuKeVLX:-MOpyqKI0KyExCuKeVLY:bpmv9z3) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp#L77)):*
> ```cpp
> 	ASSERT(kv.exists("key2") == status::OK);
> 	ASSERT(kv.exists("key3") == status::OK);
> ```

maybe add a comment we don't have to close the tx object because it's unique ptr
___
*[utils/docker/run-build.sh, line 197 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpwBWN2NhNRVwkFVBf:-MOpwBWN2NhNRVwkFVBg:b1dk1e) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/utils/docker/run-build.sh#L197)):*
> ```Shell
> 	CC=gcc CXX=g++ \
> 	cmake .. -DCMAKE_BUILD_TYPE=Release \
> 		-DENGINE_RADIX=1
> ```

you're missing `\` at the end of line


<!-- Sent from Reviewable.io -->

2020-12-18 16:18 UTC, lukaszstolarczuk requested changes
> Reviewed 2 of 11 files at r1, 1 of 10 files at r2, 1 of 13 files at r4, 6 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: 21 of 22 files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[src/libpmemkv.hpp, line 483 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqF-JS7TpoJMDAgt7Y:-MOqF-JS7TpoJMDAgt7Z:b-vg6a3p) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L483)):*
> ```cpp
> 	durability. Actions in a transaction are executed in the order in which they were
> 	called.
> */
> ```

\+ example snippet
___
*[src/libpmemkv.hpp, line 1113 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqH-IDAiOzYN1t7iB3:-MOqH-IDAiOzYN1t7iB4:b-bftdxd) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1113)):*
> ```cpp
> /**
>  * Commits the transaction. All operations of this transaction are applied as
>  * a single power fail-safe atomic action.
> ```

pls describe it can be used after commit
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqEWj_Dy-qg-iDnYKd:-MOqEWj_Dy-qg-iDnYKe:blforyq) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
> ```cpp
> 
> /**
>  * Aborts the transaction. Transaction class cannot be used after this.
> ```

`class` -> `object` ?
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqGu5x3zhAbe-Z9LjK:-MOqGu5y8q-CIYw9WAx9:bw20s2b) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
> ```cpp
> 
> /**
>  * Aborts the transaction. Transaction class cannot be used after this.
> ```

actually why it can't be used? in radix impl. it just does nothing
___
*[src/libpmemkv.hpp, line 1679 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqEm_H7D1IJezYYxng:-MOqEm_H7D1IJezYYxnh:bze462e) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1679)):*
> ```cpp
> 
> /**
>  * Start a pmemkv transaction.
> ```

Starts
___
*[src/libpmemkv.cc, line 307 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqYj2a8ycQeV-Iem3e:-MOqYj2a8ycQeV-Iem3f:b-54dgvk) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L307)):*
> ```cpp
> int pmemkv_tx_begin(pmemkv_db *db, pmemkv_tx **tx)
> {
> 	if (!tx || !db)
> ```

pls add tests for C API (in null_db_config.c)
___
*[src/libpmemkv.cc, line 348 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqHggp09drBkA37-SL:-MOqHggqA7iaxhkd09GB:bflt6wg) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L348)):*
> ```cpp
> 
> void pmemkv_tx_abort(pmemkv_tx *tx)
> {
> ```

missing check for tx (use ERR(), I guess)
___
*[src/libpmemkv.cc, line 361 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqI5SJ6hMRkaJ_OA9T:-MOqI5SJ6hMRkaJ_OA9U:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L361)):*
> ```cpp
> 
> void pmemkv_tx_end(pmemkv_tx *tx)
> {
> ```

.
___
*[src/transaction.h, line 42 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIdrZE5t8A3ZG6L38:-MOqIdrZE5t8A3ZG6L39:b-oix0si) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L42)):*
> ```objc
> class dram_log {
> public:
> 	using element_type = std::pair<std::string, std::string>;
> ```

not string_view?
___
*[src/transaction.h, line 62 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqJNSB094Pn3yWurYW:-MOqJNSB094Pn3yWurYX:b41m8ci) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L62)):*
> ```objc
> 	template <typename F1, typename F2>
> 	void foreach (F1 &&insert_cb, F2 && remove_cb)
> 	{
> ```

save log.size() in a var, perhaps
___
*[src/transaction.h, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIE0xDb2_xRsep9xF:-MOqIE0xDb2_xRsep9xG:b-dntgwi) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L77)):*
> ```objc
> 					break;
> 			}
> 		}
> ```

clean log after(?)
___
*[src/engines-experimental/radix.cc, line 45 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqYydr3a24gDabzvwe:-MOqYydr3a24gDabzvwf:b-4qwjlx) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/engines-experimental/radix.cc#L45)):*
> ```cpp
> 	};
> 
> 	pmem::obj::transaction::run(pop, [&] { log.foreach (insert_cb, remove_cb); });
> ```

try-catch this and return other status if needed
___
*[tests/engine_scenarios/transaction/remove.cc, line 68 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOq_cyrAOZeiKTLuUIN:-MOq_cyrAOZeiKTLuUIO:b-s2f7gp) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/remove.cc#L68)):*
> ```cpp
> 		std::size_t cnt;
> 		ASSERT_STATUS(kv.count_all(cnt), pmem::kv::status::OK);
> 		UT_ASSERT(cnt == 0);
> ```

ASSERTeq
___
*[tests/engine_scenarios/transaction/remove.cc, line 86 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOq_b8v6pD-p5nQj8gY:-MOq_b8v6pD-p5nQj8gZ:b-s2f7gp) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/remove.cc#L86)):*
> ```cpp
> 		std::size_t cnt;
> 		ASSERT_STATUS(kv.count_all(cnt), pmem::kv::status::OK);
> 		UT_ASSERT(cnt == NUM_ITER / 2);
> ```

ASSERTeq
___
*[tests/engine_scenarios/transaction/remove.cc, line 126 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqaamJEKHsdJZO3zSd:-MOqaamJEKHsdJZO3zSe:b-79n7ov) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/remove.cc#L126)):*
> ```cpp
> 		}
> 
> 		/* remove half the elements inserted above and BATCH_SIZE non-existent
> ```

and BATCH_SIZE **of** non-...
___
*[tests/engine_scenarios/transaction/remove.cc, line 129 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqbpBB13RPeJHp7nuk:-MOqbpBC9O4at0bQDZ1X:btcf0kk) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/remove.cc#L129)):*
> ```cpp
> 		 * elements (should have no effect) */
> 		for (int j = BATCH_SIZE / 2; j < BATCH_SIZE + BATCH_SIZE / 2; j++) {
> 			ASSERT_STATUS(tx.remove(gen_key(i, j)), pmem::kv::status::OK);
> ```

actually this may be a little confusing case. One may expect to get NOT_FOUND if tried to remove a non-existing key... should this case be described somewhere...?
___
*[tests/engine_scenarios/transaction/remove.cc, line 146 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqchOH0hp53i8hp7qt:-MOqchOH0hp53i8hp7qu:b-srdu8x) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/remove.cc#L146)):*
> ```cpp
> 	}
> }
> ```

perhaps add a case with two tx's:
 - one tx adds elements and commit
 - second, new tx removes elements and commit
___
*[tests/engine_scenarios/transaction/put.cc, line 5 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqPr6rAW-dk4H88_wi:-MOqPr6s6wVWvzoR853Q:bju196) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/put.cc#L5)):*
> ```cpp
> 
> #include "unittest.hpp"
> ```

maybe add some test where we overwrite existing key
___
*[tests/engine_scenarios/transaction/put.cc, line 35 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqLOzJ946Zg7allH7K:-MOqLOzJ946Zg7allH7L:b-dv0441) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/put.cc#L35)):*
> ```cpp
> 
> 	for (auto &e : elements)
> 		ASSERT_ [...]

2020-12-21 09:46 UTC, szyrom approved these changes
> Reviewed 2 of 13 files at r4, 17 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/transaction.h, line 42 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIdrZE5t8A3ZG6L38:-MP3dcDM4PJcyRf_DokF:bveknvp) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not string_view?
</blockquote></details>

we cannot store ptr and size only in a log; they might be invalid in the moment of copying them to pmem when the commit was triggered
___
*[src/transaction.h, line 62 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqJNSB094Pn3yWurYW:-MP3ewRw2FqwmLuuhN5F:b-kyj42i) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L62)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

save log.size() in a var, perhaps
</blockquote></details>

its in dram, it will be cached 
___
*[src/transaction.h, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIE0xDb2_xRsep9xF:-MP3fy9_A5fsKsK-rovP:b-ud1bul) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

clean log after(?)
</blockquote></details>

commit is handling destruction of the log


<!-- Sent from Reviewable.io -->

2020-12-21 09:46 UTC, szyrom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MP3gOEC98bebJoJV5Fz:bnfp4nl)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-12-21 13:23 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4SpGY4GSlvVprAc8k:-MP4SpGY4GSlvVprAc8l:b1qmiq) (no related file):*
pls check the coverage, it's a bit low, I guess

---
___
*[doc/libpmemkv_tx.3.md.in, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4Sn501UY29V77-1-_:-MP4Sn512AQzbPlg0Lea:b-7uzpjm) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L8)):*
> ```
> header: PMEMKV_TX
> secondary_title: pmemkv
> ...
> ```

`---`
___
*[src/transaction.h, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIE0xDb2_xRsep9xF:-MP4SyVMBVdZQF7pC0dj:b-jphini) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L77)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

commit is handling destruction of the log
</blockquote></details>

does it?


<!-- Sent from Reviewable.io -->

2020-12-21 13:48 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 29 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[doc/libpmemkv_tx.3.md.in, line 54 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc5Mz7xeV4NiRc5vY:-MP43-F7EAj4mATqXLzJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

almost - `pmemobj`?
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv/830#-MOkc8jIEhN_VlEG6sQD:-MP42zTuEuClV8lSqIN7:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5452e6e41f7bc498192d84ec8fe1d7ad189edccd/doc/libpmemkv_tx.3.md.in#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4Sn501UY29V77-1-_:-MP4Y9Yr9MFS-L1SMQPY:b-t71jyy) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`---`
</blockquote></details>

Hm, it's the same as in all other manpages
___
*[doc/libpmemkv_tx.3.md.in, line 75 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOptzTR5AbQAx5_ViGG:-MP432ig3ditafWLd6Hb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe pmemkv transaction **object** (?)
</blockquote></details>

Done.
___
*[doc/libpmemkv_tx.3.md.in, line 75 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpu4CzEiBmQXJRUnqS:-MP43VWc4y9AkNz5zJjh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add info that it aborts the uncommitted changes (does it, right?)
</blockquote></details>

Done.
___
*[examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpyqKI0KyExCuKeVLX:-MP43no052Ssh0z7He2z:bbqj9nv) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe add a comment we don't have to close the tx object because it's unique ptr
</blockquote></details>

There is no function in C++ API to destroy the tx, other than the destructor so it should be pretty clear I think. But I added example without calling commit.
___
*[src/libpmemkv.hpp, line 483 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqF-JS7TpoJMDAgt7Y:-MP45rS-7HpuB5cPYgyb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L483)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ example snippet
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1113 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqH-IDAiOzYN1t7iB3:-MP46_GfEqJtpDj5x0X5:b-ywc8lp) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls describe it can be used after commit
</blockquote></details>

Done. (+ added test)
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqEWj_Dy-qg-iDnYKd:-MP46uTWETOiYvshx68O:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`class` -> `object` ?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqGu5x3zhAbe-Z9LjK:-MP46ur36RW6Wv98cE-4:bwzd6v8) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually why it can't be used? in radix impl. it just does nothing
</blockquote></details>

Right, I wanted to not guarantee that so we can have more freedom in implementation for other engines. But as I think about this, it will not compilcated it much. Done.
___
*[src/libpmemkv.hpp, line 1679 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqEm_H7D1IJezYYxng:-MP478Os2pMsoqZ3iOOU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1679)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Starts
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 307 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqYj2a8ycQeV-Iem3e:-MP49XoaAcY2NfYdnb1y:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L307)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add tests for C API (in null_db_config.c)
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 348 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqHggp09drBkA37-SL:-MP48Vbe1bhlObag5Grx:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L348)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing check for tx (use ERR(), I guess)
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 361 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqI5SJ6hMRkaJ_OA9T:-MP4A9H84kSFykshxOyF:bht3wpv) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L361)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

It fine here, since delete will just do nothing for NULL.
___
*[src/transaction.h, line 42 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIdrZE5t8A3ZG6L38:-MP4AEF00Hcv-1_HLvKQ:b7u03hh) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L42)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

we cannot store ptr and size only in a log; they might be invalid in the moment of copying them to pmem when the commit was triggered
</blockquote></details>

Correct
___
*[src/transaction.h, line 62 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqJNSB094Pn3yWurYW:-MP4AJHA6n6F-BeWLQ9R:b-7jzv7t) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L62)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

its in dram, it will be cached 
</blockquote></details>

right
___
*[src/transaction.h, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqIE0xDb2_xRsep9xF:-MP4AUsr3MpFDvm-Yiai:b-kj5bnn) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/transaction.h#L77)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

commit is handling destruction of the log
</blockquote></details>

yes, the log will be cleared when  [...]

2020-12-21 14:57 UTC, lukaszstolarczuk reviewed
> Reviewed 18 of 18 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[doc/libpmemkv_tx.3.md.in, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4Sn501UY29V77-1-_:-MP4fcc_DNXTZjO5VkyH:b-1cd4o6) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/doc/libpmemkv_tx.3.md.in#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, it's the same as in all other manpages
</blockquote></details>

hmm.. I just seen this on pmem.io blogpost and assumed it should be the same here, but you're right
___
*[examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp, line 77 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOpyqKI0KyExCuKeVLX:-MP4bEhI5Z7eJ8rqh8qs:b9y27z0) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/examples/pmemkv_transaction_cpp/pmemkv_transaction.cpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There is no function in C++ API to destroy the tx, other than the destructor so it should be pretty clear I think. But I added example without calling commit.
</blockquote></details>

great, thanks!
___
*[src/libpmemkv.hpp, line 1113 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqH-IDAiOzYN1t7iB3:-MP4lMCMD6uFo5_bMfgr:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1113)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done. (+ added test)
</blockquote></details>

.
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqGu5x3zhAbe-Z9LjK:-MP4hczb83MBWmD3F8uH:b312k7i) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, I wanted to not guarantee that so we can have more freedom in implementation for other engines. But as I think about this, it will not compilcated it much. Done.
</blockquote></details>

soo.. I'm confused - shouldn't this description be updated...?
___
*[src/libpmemkv.cc, line 361 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqI5SJ6hMRkaJ_OA9T:-MP4c-d3-1e_ElNWCo5Z:b3cepbl) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.cc#L361)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It fine here, since delete will just do nothing for NULL.
</blockquote></details>

och, true
___
*[tests/c_api/null_db_config.c, line 81 at r6](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4dV9MAYc9lMdWrxM4:-MP4dV9MAYc9lMdWrxM5:bmqmp70) ([raw file](https://github.com/pmem/pmemkv/blob/1c34f97bdfa90f00846fda17a29746703c86fe8f/tests/c_api/null_db_config.c#L81)):*
> ```C
> 	pmemkv_tx *tx;
> 	s = pmemkv_tx_begin(NULL, &tx);
> 	UT_ASSERT(s == PMEMKV_STATUS_INVALID_ARGUMENT);
> ```

what about null tx?
___
*[tests/c_api/null_db_config.c, line 121 at r6](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4cybi8NN_uUx7tXu7:-MP4cybi8NN_uUx7tXu8:b-7y6wxl) ([raw file](https://github.com/pmem/pmemkv/blob/1c34f97bdfa90f00846fda17a29746703c86fe8f/tests/c_api/null_db_config.c#L121)):*
> ```C
> 	s = pmemkv_tx_commit(NULL);
> 	UT_ASSERT(s == PMEMKV_STATUS_INVALID_ARGUMENT);
> }
> ```

what about abort and end?
___
*[tests/engine_scenarios/transaction/put.cc, line 66 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqQQBo38-ig3MP5hhG:-MP4jgQ90zauOstCZ8Jp:bj2ybgm) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/tests/engine_scenarios/transaction/put.cc#L66)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done in test_use_after_commit/abort
</blockquote></details>

awesome, thanks!


<!-- Sent from Reviewable.io -->

2020-12-21 15:10 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 1113 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqH-IDAiOzYN1t7iB3:-MP4ogXcEyMrBRURYdvK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1123 at r5](https://reviewable.io/reviews/pmem/pmemkv/830#-MOqGu5x3zhAbe-Z9LjK:-MP4ohU43r_6rc--Xlw0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/b0e38e9c129fa507973c4cf5374d12d468cb1def/src/libpmemkv.hpp#L1123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

soo.. I'm confused - shouldn't this description be updated...?
</blockquote></details>

Done.
___
*[tests/c_api/null_db_config.c, line 81 at r6](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4dV9MAYc9lMdWrxM4:-MP4ooVMAXCa6p4Cl_Vs:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c34f97bdfa90f00846fda17a29746703c86fe8f/tests/c_api/null_db_config.c#L81)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about null tx?
</blockquote></details>

Done.
___
*[tests/c_api/null_db_config.c, line 121 at r6](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4cybi8NN_uUx7tXu7:-MP4pA7m0rgtiYLdXzix:bn1fzls) ([raw file](https://github.com/pmem/pmemkv/blob/1c34f97bdfa90f00846fda17a29746703c86fe8f/tests/c_api/null_db_config.c#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about abort and end?
</blockquote></details>

Hm, I can test it for end (to see if nothing explodes) but not for abort(), passing null there is an error (I added statement in the docs). 


<!-- Sent from Reviewable.io -->

2020-12-21 15:15 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/c_api/null_db_config.c, line 121 at r6](https://reviewable.io/reviews/pmem/pmemkv/830#-MP4cybi8NN_uUx7tXu7:-MP4rYwN52REJakC8aAa:bgr6gjb) ([raw file](https://github.com/pmem/pmemkv/blob/1c34f97bdfa90f00846fda17a29746703c86fe8f/tests/c_api/null_db_config.c#L121)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I can test it for end (to see if nothing explodes) but not for abort(), passing null there is an error (I added statement in the docs). 
</blockquote></details>

maybe assert it also (in the src)?


<!-- Sent from Reviewable.io -->

2020-12-21 15:36 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MP4wTxz6CrUyIRenj69:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-21 18:17 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/830#-:-MP5WLJU4qgKU09s2WS6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-12-22 10:53 UTC, merged