Iterators API
pmem/pmemkv pull request #831
Opened 2020-10-21 08:09 UTC by JanDorniak99

#809

2020-10-21 12:03 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA1VQr8blyuXhMLwhv:-MKA1VQr8blyuXhMLwhw:b-y9u30x) (no related file):*
please describe more in commit 98a8db3 - why, what for, etc.

---
___
*[src/engine.h, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9lbUV7Se1Ay6XKbr1:-MK9lbUV7Se1Ay6XKbr2:b1310cs) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/engine.h#L11)):*
> ```objc
> #include <string>
> 
> #include "../iterator.h"
> ```

`..` ? isn't it in the same dir?
___
*[src/engine.cc, line 214 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9ln2-85pOuDVs_ssx:-MK9ln2-85pOuDVs_ssy:b-ju9apl) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/engine.cc#L214)):*
> ```cpp
> }
> 
> /* until implemented for all engines */
> ```

you can remove these comments, this is basically why we have NOT_SUPPORTED status ;)
___
*[src/libpmemkv.map, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9mSD48LNn-VDrO73v:-MK9mSD48LNn-VDrO73w:bdnif8q) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/libpmemkv.map#L50)):*
> ```
> 		pmemkv_put;
> 		pmemkv_remove;
> 		pmemkv_read_iterator_new;
> ```

sort alphabetically, I guess


<!-- Sent from Reviewable.io -->

2020-10-21 12:09 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 2 of 11 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99)

___
*[src/libpmemkv.cc, line 617 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA34mY8uW1WkNynpiZ:-MKA34mY8uW1WkNynpi_:b-9wabvt) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/libpmemkv.cc#L617)):*
> ```cpp
> }
> 
> /* void * ? */
> ```

seems ok to return void
___
*[src/libpmemkv.cc, line 686 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA2wXf5rIf82uTu35q:-MKA2wXf5rIf82uTu35r:b-soj6dd) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/libpmemkv.cc#L686)):*
> ```cpp
> 
> 	return catch_and_return_status(__func__, [&] {
> 		return iterator_to_base(it)->seek_higher(pmem::kv::string_view(k, kb));
> ```

`higher_eq`


<!-- Sent from Reviewable.io -->

2020-10-22 10:10 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 2 of 15 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[src/engine.h, line 11 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9lbUV7Se1Ay6XKbr1:-MKE1pey-_WQ-Rn3RzKj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/engine.h#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`..` ? isn't it in the same dir?
</blockquote></details>

Done.
___
*[src/engine.cc, line 214 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9ln2-85pOuDVs_ssx:-MKE1qZV3sGwsu8aKNXU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/engine.cc#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can remove these comments, this is basically why we have NOT_SUPPORTED status ;)
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 686 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA2wXf5rIf82uTu35q:-MKE1sZF6rktuMh5CxY0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/libpmemkv.cc#L686)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`higher_eq`
</blockquote></details>

Done.
___
*[src/libpmemkv.map, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv/831#-MK9mSD48LNn-VDrO73v:-MKE1u-l2FR-vu555YYW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/62caf0f456b171a43e5960c07ad81773364e8853/src/libpmemkv.map#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sort alphabetically, I guess
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 11:46 UTC, igchor reviewed
> Reviewed 1 of 11 files at r1, 2 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 4 of 17 files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[src/engine.cc, line 214 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdo_MG6rsy0VIzfA--:-MKdo_MH6q2f_uO8Pe5Z:b-o0z0cy) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/engine.cc#L214)):*
> ```cpp
> }
> 
> status engine_base::new_iterator(internal::iterator<false> *&it)
> ```

Hm, I think you could implement those functions like this:

```
iterator<false> new_iterator() {
    throw status::NOT_SUPPORTED;
}
```

This should work the same way (you can test this)  and we do not really care about performance for NOT_SUPPORTED case but will be more readible (in our internal implementation).
___
*[src/iterator.h, line 29 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdkQipCFrZ3JGSQC-x:-MKdkQipCFrZ3JGSQC-y:btsyhd7) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/iterator.h#L29)):*
> ```objc
> 	// op? iterator_base& operator=(const iterator_base&) = delete;
> 
> 	virtual status seek(string_view key);
> ```

I would make seek, seek_to_first, seek_to_last pure virtual (` = 0`). Those functions should be implemented by all iterators.
___
*[src/libpmemkv.hpp, line 271 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdlbZT9iRe9XkthQOQ:-MKdlbZT9iRe9XkthQOR:b-2jfdmy) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L271)):*
> ```cpp
> 	status defrag(double start_percent = 0, double amount_percent = 100);
> 
> 	template <bool IsConst>
> ```

I think in public API it would be better to have 2 separate methods for const and non-const iterators. We should also expose const and non-const iterator types in db class (the class itself can remain templated, we can just do:
```
class db {
private;
class iterator;
public:
using read_iterator = iterator<true>;
using write_iterator = iterator<false>;
```
).
___
*[src/libpmemkv.hpp, line 283 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmyTd66g-CN_9BLWE:-MKdmyTd66g-CN_9BLWF:b-g5ccmf) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L283)):*
> ```cpp
> class db::iterator {
> public:
> 	iterator(pmemkv_db *db);
> ```

I think it would be better if this class took pointer to C iterator instead of pememkv_db*. We do not want to allow users to create iterators using iterator ctors but only through a call to db::new_iterator(). Moreover, if any error occurs while creating iterator should be returned from new_iterator.
___
*[src/libpmemkv.hpp, line 286 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmTYSB3UdKPLbq1Up:-MKdmTYSB3UdKPLbq1Uq:bim54sq) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L286)):*
> ```cpp
> 	~iterator();
> 
> 	virtual status seek(string_view key);
> ```

This should not be virtual. + it can be noexcept.
___
*[src/libpmemkv.hpp, line 299 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmbqT23DIYyYJRkcm:-MKdmbqT23DIYyYJRkcn:bc5rqwc) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L299)):*
> ```cpp
> 
> private:
> 	void *_it;
> ```

I think you can hold an exact type here. If IsConst == true this will be pmemkv_read_iterator, otherwise pmemkv_write_iterator. (you can use std::conditional)
___
*[src/engines/vsmap.h, line 81 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdr_Fu5PmpWuMUMmsk:-MKdr_Fu5PmpWuMUMmsl:banbqsa) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/engines/vsmap.h#L81)):*
> ```objc
> 
> template <>
> class vsmap::vsmap_iterator<false> : public internal::iterator<false> {
> ```

Hm, after some thought, I think you don't have to actually make those 2 specialization. You could just do:

```
template <bool IsConst>
vsmap_iterator : public internal::iterator<IsConst> 
{

}
```

and implement most of the functions just once. Only for key() and value() there will be seperate impl but this can be done using enable_if
___
*[src/engines/vsmap.h, line 133 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdqLHe4ek4uRZP828X:-MKdqLHe4ek4uRZP828Y:b-cim6xo) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/engines/vsmap.h#L133)):*
> ```objc
> 	container_type *container;
> 	vsmap::map_allocator_type *kv_allocator;
> 	container_type::iterator _it;
> ```

I guess you can have const_iterator here


<!-- Sent from Reviewable.io -->

2020-10-27 18:53 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 11 files at r1, 8 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 11 of 17 files reviewed, 19 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA1VQr8blyuXhMLwhv:-MKehn2L-wWs42xt1RUw:b1rhpj0) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please describe more in commit 98a8db3 adding base_iterator class - why, what for, etc.
</blockquote></details>

still not done \+ tests commit can be merged to commit with the one introducing new functionality

---
___
*[tests/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfALzCApAW6vwuadKP:-MKfALzCApAW6vwuadKQ:b-8ppm3o) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L54)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.c*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.h*
> 		${CMAKE_CURRENT_SOURCE_DIR}/iterator/*.*)
> ```

only .c* and .h* files, not all
___
*[tests/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfEJ2D0w1G5OyPmolj:-MKfEJ2EBJCRAxrCOWA3:b68rty8) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L54)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.c*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.h*
> 		${CMAKE_CURRENT_SOURCE_DIR}/iterator/*.*)
> ```

I guess you can put iterator test within "engine_scenarios", since you run them only for engines.
___
*[tests/CMakeLists.txt, line 121 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfGtnd1E0baafV0gi3:-MKfGtnd1E0baafV0gi4:b-8nivck) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L121)):*
> ```CMake
> add_test_generic(NAME config_cpp TRACERS none memcheck)
> 
> build_test(blackhole_test engines/blackhole/blackhole_test.cc)
> ```

you can extend this test to check if not_supported is returned as a default (for engine that does not implement iterators)
___
*[tests/CMakeLists.txt, line 175 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfIDvH8yezaTbp4utl:-MKfIDvI67FfkdUXJehN:b-c9mv35) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L175)):*
> ```CMake
> build_test_ext(NAME memkind_error_handling SRC_FILES engine_scenarios/memkind/error_handling.cc LIBS json)
> 
> # Tests for C API
> ```

I believe you can add checks for iterator C API
___
*[tests/iterator/iterator_basic.cc, line 137 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMN4W6oEsQnZkPJg1:-MKfMN4W6oEsQnZkPJg2:b41y7cf) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L137)):*
> ```cpp
> 	auto it = kv.new_iterator<IsConst>();
> 
> 	insert_keys(kv);
> ```

check before inserting keys
___
*[tests/iterator/iterator_basic.cc, line 157 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMQMN1SFOS7lCawpJ:-MKfMQMN1SFOS7lCawpK:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L157)):*
> ```cpp
> 	auto it = kv.new_iterator<IsConst>();
> 
> 	insert_keys(kv);
> ```

.
___
*[tests/iterator/iterator_basic.cc, line 177 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfM_dMCgzXc06e-hbd:-MKfM_dNB_Nj6yjMugs5:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L177)):*
> ```cpp
> 	auto it = kv.new_iterator<IsConst>();
> 
> 	insert_keys(kv);
> ```

.
___
*[tests/iterator/iterator_basic.cc, line 181 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMtkg-PChXasIjFPA:-MKfMtkg-PChXasIjFPB:b4nyoxc) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L181)):*
> ```cpp
> 	ASSERT_STATUS(it.seek_to_first(), pmem::kv::status::OK);
> 
> 	std::for_each(keys.begin() + 1, keys.end(), [&](pair p) {
> ```

why `+ 1` ? rather `end() - 1`
___
*[tests/iterator/iterator_basic.cc, line 198 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMe178qP-JcuD75cp:-MKfMe178qP-JcuD75cq:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L198)):*
> ```cpp
> 	auto it = kv.new_iterator<IsConst>();
> 
> 	insert_keys(kv);
> ```

.
___
*[tests/iterator/iterator_basic.cc, line 218 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfDdJC4-6W50DdlSvU:-MKfDdJC4-6W50DdlSvV:b-qp4c0y) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L218)):*
> ```cpp
> 
> 	auto engine = std::string(argv[1]);
> ```

if you don't change anything within config you can just use `run_engine_tests` - it initializes kv and clears it out after testing


<!-- Sent from Reviewable.io -->

2020-10-28 10:01 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 3 of 19 files reviewed, 19 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MKA1VQr8blyuXhMLwhv:-MKidmyQD1CkDCjRRKjj:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still not done \+ tests commit can be merged to commit with the one introducing new functionality
</blockquote></details>

Done.

---
___
*[src/engine.cc, line 214 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdo_MG6rsy0VIzfA--:-MKeOzLd1-Vm3hYi9_l9:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/engine.cc#L214)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I think you could implement those functions like this:

```
iterator<false> new_iterator() {
    throw status::NOT_SUPPORTED;
}
```

This should work the same way (you can test this)  and we do not really care about performance for NOT_SUPPORTED case but will be more readible (in our internal implementation).
</blockquote></details>

Done.
___
*[src/iterator.h, line 29 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdkQipCFrZ3JGSQC-x:-MKdypLb4SInZun_FWE6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/iterator.h#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would make seek, seek_to_first, seek_to_last pure virtual (` = 0`). Those functions should be implemented by all iterators.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 271 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdlbZT9iRe9XkthQOQ:-MKe7RvLA0X2vUUWr4yh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L271)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think in public API it would be better to have 2 separate methods for const and non-const iterators. We should also expose const and non-const iterator types in db class (the class itself can remain templated, we can just do:
```
class db {
private;
class iterator;
public:
using read_iterator = iterator<true>;
using write_iterator = iterator<false>;
```
).
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 283 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmyTd66g-CN_9BLWE:-MKeXU6V5xL03qxGpZol:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L283)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better if this class took pointer to C iterator instead of pememkv_db*. We do not want to allow users to create iterators using iterator ctors but only through a call to db::new_iterator(). Moreover, if any error occurs while creating iterator should be returned from new_iterator.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 286 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmTYSB3UdKPLbq1Up:-MKeOw8LEjySL3PfyfYS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L286)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This should not be virtual. + it can be noexcept.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 299 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdmbqT23DIYyYJRkcm:-MKeBs2I7jiY6chH7WpT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/libpmemkv.hpp#L299)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you can hold an exact type here. If IsConst == true this will be pmemkv_read_iterator, otherwise pmemkv_write_iterator. (you can use std::conditional)
</blockquote></details>

Done.
___
*[src/engines/vsmap.h, line 81 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdr_Fu5PmpWuMUMmsk:-MKeOxBr632ud7NsuVe0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/engines/vsmap.h#L81)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, after some thought, I think you don't have to actually make those 2 specialization. You could just do:

```
template <bool IsConst>
vsmap_iterator : public internal::iterator<IsConst> 
{

}
```

and implement most of the functions just once. Only for key() and value() there will be seperate impl but this can be done using enable_if
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfEJ2D0w1G5OyPmolj:-MKi7rHs2UGvetbAJiGP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can put iterator test within "engine_scenarios", since you run them only for engines.
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 54 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfALzCApAW6vwuadKP:-MKi7rTa6jWUEjMYLDc2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

only .c* and .h* files, not all
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 137 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMN4W6oEsQnZkPJg1:-MKi90rBEwMvOgLTqJP2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L137)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

check before inserting keys
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 157 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMQMN1SFOS7lCawpJ:-MKi92xqEm9_VTWin4oM:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 177 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfM_dMCgzXc06e-hbd:-MKi9Xu45-5_h1Xbg5Ra:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L177)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 181 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMtkg-PChXasIjFPA:-MKiB-xpBXG87XiH8v4G:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L181)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why `+ 1` ? rather `end() - 1`
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 198 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfMe178qP-JcuD75cp:-MKi9bImB4iHHkGlsPRd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L198)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:12 UTC, lukaszstolarczuk reviewed
> Reviewed 6 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 9 of 19 files reviewed, 11 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-11-02 08:21 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 9 of 19 files reviewed, 8 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/iterator.h, line 29 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKdkQipCFrZ3JGSQC-x:-ML6ox-o1eip8G5JCRvb:bckjs2j) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/src/iterator.h#L29)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Probably key() and value() also once they are implemented.
___
*[src/libpmemkv.hpp, line 274 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6pei27uLWT4ZvY6pf:-ML6pei3CqWp2sGNUe4G:b9ynusa) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/libpmemkv.hpp#L274)):*
> ```cpp
> 	status defrag(double start_percent = 0, double amount_percent = 100);
> 
> 	write_iterator new_write_iterator();
> ```

I guess those functions should (in the final version) return iterator wrapped in some result type - we need a way to pass errors.
___
*[src/engines-experimental/csmap.cc, line 319 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6qU_8-qIMkfOXwUbD:-ML6qU_8-qIMkfOXwUbE:b-yzi19j) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/csmap.cc#L319)):*
> ```cpp
> csmap::csmap_iterator<IsConst>::csmap_iterator(container_type *c, global_mutex_type &mtx)
> {
> 	// lock = csmap::shared_global_lock_type(mtx);
> ```

It would be better to use initialization list: https://en.cppreference.com/w/cpp/language/constructor
___
*[src/engines-experimental/csmap.cc, line 327 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6qcVp0OkB0xnIv0py:-ML6qcVp0OkB0xnIv0pz:b-pdxtcr) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/csmap.cc#L327)):*
> ```cpp
> csmap::csmap_iterator<IsConst>::~csmap_iterator()
> {
> 	// lock.unlock();
> ```

unlock will be done automatically by the lock dtor
___
*[src/engines-experimental/radix.cc, line 326 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6rMl11lxUgTsVvW0i:-ML6rMl11lxUgTsVvW0j:bifpqnx) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/radix.cc#L326)):*
> ```cpp
> 	if (container->empty() ||
> 	    (_it == container->begin() &&
> 	     key.compare(string_view{_it->key().data(), _it->key().size()}) != 0)) {
> ```

Is this comparison really needed? You can implement lower_eq by using --upper_bound and lower by using --lower_bound (just check if iterator is != begin)


<!-- Sent from Reviewable.io -->

2020-11-05 08:19 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 3 of 21 files reviewed, 8 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/engines-experimental/csmap.cc, line 319 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6qU_8-qIMkfOXwUbD:-MLIIu46COIBYqZOP7Do:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/csmap.cc#L319)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It would be better to use initialization list: https://en.cppreference.com/w/cpp/language/constructor
</blockquote></details>

Done.
___
*[src/engines-experimental/csmap.cc, line 327 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6qcVp0OkB0xnIv0py:-MLIJ5Pq7JdWG9oE00JH:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/csmap.cc#L327)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

unlock will be done automatically by the lock dtor
</blockquote></details>

Done.
___
*[src/engines-experimental/radix.cc, line 326 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6rMl11lxUgTsVvW0i:-MLMPYnq7HYvdggpyVsR:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/engines-experimental/radix.cc#L326)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this comparison really needed? You can implement lower_eq by using --upper_bound and lower by using --lower_bound (just check if iterator is != begin)
</blockquote></details>

Done.
___
*[tests/iterator/iterator_basic.cc, line 218 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfDdJC4-6W50DdlSvU:-MKnRe442q-g9m_Px9EB:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/iterator/iterator_basic.cc#L218)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you don't change anything within config you can just use `run_engine_tests` - it initializes kv and clears it out after testing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-09 18:12 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 8 of 21 files reviewed, 10 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiCJn27D9l__JMpyIQ:-MLiCJn27D9l__JMpyIR:bqrwkgq) (no related file):*
just to make sure we don't forget later - please add docs (for C and C++ API)

---
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 5 at r4](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiBximCTFKW3ex6rKK:-MLiBximCTFKW3ex6rKL:b-ylh6hh) ([raw file](https://github.com/pmem/pmemkv/blob/eb847f89177b40f422fd0e68efefee29e52258de/tests/engine_scenarios/sorted/iterator_sorted.cc#L5)):*
> ```cpp
> 
> #include "../all/iterator.hpp"
> ```

please add some short descriptions to new test files (or for each test case, if needed)
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 75 at r4](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiBlPI-Z0nDqBhklj3:-MLiBlPI-Z0nDqBhklj4:b-bgx00b) ([raw file](https://github.com/pmem/pmemkv/blob/eb847f89177b40f422fd0e68efefee29e52258de/tests/engine_scenarios/all/iterator_basic.cc#L75)):*
> ```cpp
> 
> 	run_engine_tests(argv[1], argv[2],
> 			 {seek_test<true>, seek_test<false>, seek_to_first_test<true>,
> ```

please make it - one test, one line


<!-- Sent from Reviewable.io -->

2020-11-10 11:10 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 7 of 22 files reviewed, 10 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 175 at r2](https://reviewable.io/reviews/pmem/pmemkv/831#-MKfIDvH8yezaTbp4utl:-MLlbaQl5VcPAjpGcmor:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/17073637eb90582e60ea19ead59025e036afe059/tests/CMakeLists.txt#L175)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can add checks for iterator C API
</blockquote></details>

Done.
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 5 at r4](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiBximCTFKW3ex6rKK:-MLlpMtiAKIzvsP_M2IC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eb847f89177b40f422fd0e68efefee29e52258de/tests/engine_scenarios/sorted/iterator_sorted.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add some short descriptions to new test files (or for each test case, if needed)
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 75 at r4](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiBlPI-Z0nDqBhklj3:-MLlbnwdDuf5dykwhegd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eb847f89177b40f422fd0e68efefee29e52258de/tests/engine_scenarios/all/iterator_basic.cc#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please make it - one test, one line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-23 12:32 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 29 files at r5, 4 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 6 of 34 files reviewed, 20 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[examples/CMakeLists.txt, line 23 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMopEcX1pYIUkY_yo6B:-MMopEcY98G37AtdBJKh:bw5owk5) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/CMakeLists.txt#L23)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_comparator_cpp/*.cpp
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_comparator_c/*.c
> 		${CMAKE_CURRENT_SOURCE_DIR}/pmemkv_iterator_cpp/*.cpp)
> ```

check for whitespaces should be done for all files, hence `*.*` (above ones too)
___
*[examples/pmemkv_iterator_cpp/CMakeLists.txt, line 7 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMorTSA5swv0xI8Bh1z:-MMorTSA5swv0xI8Bh2-:b4mnrnd) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/CMakeLists.txt#L7)):*
> ```CMake
> project(pmemkv_iterator CXX)
> 
> find_package(PkgConfig QUIET)
> ```

I know we have it the same way in other examples, but actually - we can make it REQUIRED (instead of QUIET) and just skip check in the below `if`
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 28 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMosCVn96UF2oNR3_8D:-MMosCVn96UF2oNR3_8E:bswhh3b) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L28)):*
> ```cpp
> {
> 	if (argc < 2) {
> 		std::cerr << "Usage: " << argv[0] << " file\n";
> ```

use `std::endl` instead of `\n`
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 43 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMotIUx0hv6SI3ovLIC:-MMotIUx0hv6SI3ovLID:bkghxby) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L43)):*
> ```cpp
> 	ASSERT(s == status::OK);
> 
> 	LOG("\nOpening pmemkv database with 'radix' engine");
> ```

drop the `\n` at the beginning of all the logs
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 67 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMow4hG6hHxVOs2Plsu:-MMow4hG6hHxVOs2Plsv:bpc7ahw) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L67)):*
> ```cpp
> 		ASSERT(key_result.second == status::OK);
> 		auto key_string = std::string(key_result.first.data());
> 		ASSERT(key_string == std::to_string(cnt));
> ```

not sure if we need this assert (and the same one for checking value); if this would be test then yes, but it is an example, we can remove this (I believe) or just put a comment with info, what's the expected value (but we have LOG for that ;) )
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 72 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMovVDq0gBEg2uUlWgH:-MMovVDq0gBEg2uUlWgI:b-wiwsed) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L72)):*
> ```cpp
> 		/* read value */
> 		/* to read whole value, pass max size_t as n */
> 		auto val_result = it.read_range(0, std::numeric_limits<size_t>::max());
> ```

can't we add another method/override (or use default param value) to not pass this 'max' every time we want to read whole key?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMows0P69C71SyVvPKb:-MMows0P69C71SyVvPKc:bvbppre) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L101)):*
> ```cpp
> 		ASSERT(val_string == std::string(10 + cnt, 'a'));
> 		LOG("Value = " + val_string);
> ```

perhaps make this read key & read value a function in this example
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 108 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMowo0z9DFSc_2_mu6g:-MMowo0z9DFSc_2_mu6h:byfd51l) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L108)):*
> ```cpp
> 	auto w_it = kv->new_write_iterator();
> 
> 	LOG("\nModify value of element lower than \"5\"");
> ```

of the element
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 115 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMox3CCBienXsQ1DyFM:-MMox3CCBienXsQ1DyFN:b1v7om8) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L115)):*
> ```cpp
> 		w_it.read_range(0, std::numeric_limits<size_t>::max()).first.begin();
> 
> 	/* get write range, to obtain whole value's range, pass max size_t as n */
> ```

`get write range; ...` or `.` (instead of `;`)
___
*[tests/CMakeLists.txt, line 54 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMoxmxI20doZI-DHnNl:-MMoxmxJDku_6R6iGEA-:by7v503) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/tests/CMakeLists.txt#L54)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.c*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.h*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/pmreorder/*.c*)
> ```

move this line 2 lines up (so it's sorted a-z)
___
*[tests/CMakeLists.txt, line 69 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMoxtOWDW3CkGlnYZ_7:-MMoxtOWDW3CkGlnYZ_8:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/tests/CMakeLists.txt#L69)):*
> ```CMake
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/pmemobj/*.*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/sorted/*.*
> 		${CMAKE_CURRENT_SOURCE_DIR}/engine_scenarios/pmreorder/*.*)
> ```

.
___
*[tests/c_api/null_db_config.c, line 156 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMp4jKd6KIIGk-vVQxw:-MMp4jKe336QwDnHlyRz:bt9qzm5) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/tests/c_api/null_db_config.c#L156)):*
> ```C
> 	/* returns void */
> 	pmemkv_write_iterator_abort(NULL);
> }
> ```

aren't you missing some funcs?
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 7 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMp2wF-2wF8lVtdaLiA:-MMp2wF-2wF8lVtdaLiB:b-l9sy6h) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/tests/engine_scenarios/sorted/iterator_sorted.cc#L7)):*
> ```cpp
> 
> /**
>  * Test basic methods available only in sorted engines's iterators.
> ```

`engines's` -> `engines'`


<!-- Sent from Reviewable.io -->

2020-11-23 13:43 UTC, szyrom reviewed
> Reviewed 1 of 11 files at r1, 13 of 29 files at r5, 12 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 38 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiCJn27D9l__JMpyIQ:-MMpKk1s1fBUfoGcsrlk:b209jva) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just to make sure we don't forget later - please add docs (for C and C++ API)
</blockquote></details>

write iterators for libpmemobj-based engines will have the same commit method - I am not sure if it will be applicable here (the code will be complicated too much) to add an additional libpmemobj-based base iterator class?

---
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 67 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMow4hG6hHxVOs2Plsu:-MMpF5sZ8LsrrJe2ljdp:b-n48wip) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure if we need this assert (and the same one for checking value); if this would be test then yes, but it is an example, we can remove this (I believe) or just put a comment with info, what's the expected value (but we have LOG for that ;) )
</blockquote></details>

I think it is ok, however, I would add some comments like "key_result is a pair<X,Y> which stores this and that
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 71 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpESoPDeGFKlV3qP74:-MMpESoPDeGFKlV3qP75:b-fcr23x) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L71)):*
> ```cpp
> 
> 		/* read value */
> 		/* to read whole value, pass max size_t as n */
> ```

a whole
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 81 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpDkc5-YibYafPn6p6:-MMpDkc6AlMyRVKBdgLU:bbtmsw3) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L81)):*
> ```cpp
> 	} while (it.next() == status::OK);
> 
> 	--cnt;
> ```

use a const var for the number of elements we've put, and set cnt to this value. we are not sure if cnt was incremented desired number of times, I guess it.next() may return status different than OK and it won't mean that we reached end. Assert(cnt == some_var) after the look should be also there
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 87 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpEVPMDkx5Pb5_Ws71:-MMpEVPMDkx5Pb5_Ws72:b-7umwg5) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L87)):*
> ```cpp
> 	ASSERT(s == status::OK);
> 	do {
> 		/* read key */
> ```

a key
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 115 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpFTK98nGdW8Nrrm4O:-MMpFTK98nGdW8Nrrm4P:b-fcr23x) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L115)):*
> ```cpp
> 		w_it.read_range(0, std::numeric_limits<size_t>::max()).first.begin();
> 
> 	/* get write range, to obtain whole value's range, pass max size_t as n */
> ```

a whole
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 141 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpFlAZ0aV74-Qw7HJ3:-MMpFlAZ0aV74-Qw7HJ4:b-r0r0q8) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L141)):*
> ```cpp
> 
> 	return 0;
> }
> ```

add a note where you open a db, that radix_tree is a single-threaded engine. Describe how it affects the usage of write iterators. Can we add also an example with a concurrent angine?
___
*[src/libpmemkv.hpp, line 274 at r3](https://reviewable.io/reviews/pmem/pmemkv/831#-ML6pei27uLWT4ZvY6pf:-MMpGI50AYkcKJnZALlB:b5bs67s) ([raw file](https://github.com/pmem/pmemkv/blob/65c131524cc6e31a2261d14d2b6d66465ea880ce/src/libpmemkv.hpp#L274)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess those functions should (in the final version) return iterator wrapped in some result type - we need a way to pass errors.
</blockquote></details>

+1, just like e.g key() method returns a std::pair
___
*[src/libpmemkv.hpp, line 293 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpGSLE-VOK1V-ym41j:-MMpGSLE-VOK1V-ym41k:b-ttvzrq) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.hpp#L293)):*
> ```cpp
> 	std::pair<string_view, status> key() noexcept;
> 
> 	// XXX: result<slice<InputIt>, status>
> ```

what is this XXX?
___
*[src/engines/cmap.cc, line 199 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpJnWH7j__nWlMrG7F:-MMpJnWH7j__nWlMrG7G:bqrguyy) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L199)):*
> ```cpp
> 	}
> 
> 	if (pos + n > _acc->second.size() || pos + n < pos)
> ```

n < 0, same for the other engines
___
*[src/engines/cmap.cc, line 202 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpIj8Z61KdWHjkaW0r:-MMpIj8Z61KdWHjkaW0s:b-rjytxd) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L202)):*
> ```cpp
> 		n = _acc->second.size() - pos;
> 
> 	log.push_back({std::string(_acc->second.c_str() + pos, n), pos});
> ```

push_back may fail on reallocation, maybe we need to try-catch it? same for the other engines
___
*[src/engines/cmap.cc, line 203 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpIcOr3FwELY80scQ6:-MMpIcOr3FwELY80scQ7:batifhq) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L203)):*
> ```cpp
> 
> 	log.push_back({std::string(_acc->second.c_str() + pos, n), pos});
> 	auto &val = log[log.size() - 1].first;
> ```

log.back().first, same for the other engines
___
*[src/engines/vcmap.cc, line 173 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpJs_1E1FXBUzvE9yx:-MMpJs_1E1FXBUzvE9yy:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/vcmap.cc#L173)):*
> ```cpp
> 		return {{nullptr, nullptr}, status::NOT_FOUND};
> 
> 	if (pos + n > _acc->second.size() || pos + n < pos)
> ```

.
___
*[src/engines/vcmap.cc, line 196 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpJdbfDN9ElG8PYZeZ:-MMpJdbfDN9ElG8PYZe_:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/vcmap.cc#L196)):*
> ```cpp
> 
> 	log.push_back({std::string(_acc->second.c_str() + pos, n), pos});
> 	auto &val = log[log.size() - 1].first;
> ```

.
___
*[src/engines/vsmap.cc, line 460 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpK-BJ289C7Y9lZkFU:-MMpK-BJ289C7Y9lZkFV:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/vsmap.cc#L460)):*
> ```cpp
> 
> 	log.push_back({std::string(&(_it->second[0]), n), pos});
> 	auto &val = log[log.size() - 1].first;
> ```

.
___
*[src/engines-experimental/csmap.cc, line 458 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpKGKW2MtduJqe675J:-MMpKGKW2MtduJqe675K:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines-experimental/csmap.cc#L458)):*
> ```cpp
> 		return {{nullptr, nullptr}, status::NOT_FOUND};
> 
> 	if (pos + n > _it->second.val.size() || pos + n < pos)
> ```

.
___
*[src/engines-experimental/csmap.cc, line 481 at r6](https: [...]

2020-11-23 15:16 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 44 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 72 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMovVDq0gBEg2uUlWgH:-MMpRGds7hioNbGwumu7:bpxzj39) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can't we add another method/override (or use default param value) to not pass this 'max' every time we want to read whole key?
</blockquote></details>

Right, I think for C++ api we could make both parametrs to have default values (pos = 0, n = numeric_limits::max())
___
*[src/iterator.h, line 34 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpaqHy6ut-lpR9NMoe:-MMpaqHy6ut-lpR9NMof:b-m3jwhx) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/iterator.h#L34)):*
> ```objc
> 	virtual status next();
> 	virtual status prev();
> ```

I think it would be useful to have something like is_next() (maybe the implementation could just be internal_it != end())? It would allow iterating to the last element and using it for something,.
___
*[src/iterator.h, line 36 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpenR396Alcgqhetm7:-MMpenR396Alcgqhetm8:b-kahlxd) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/iterator.h#L36)):*
> ```objc
> 
> 	virtual std::pair<string_view, status> key() = 0;
> 	virtual std::pair<pmem::obj::slice<const char *>, status>
> ```

I think the read_range can just return string_view instead of pmem::obj::slice
___
*[src/libpmemkv.hpp, line 294 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpex-sA7vK2lX40vC1:-MMpex-t5kj0PDa0NupF:bopqe05) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.hpp#L294)):*
> ```cpp
> 
> 	// XXX: result<slice<InputIt>, status>
> 	std::pair<pmem::obj::slice<const char *>, status> read_range(size_t pos,
> ```

I think it can return string_view instead of pmem::obj::slice.
___
*[src/libpmemkv.hpp, line 298 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpf-bW84bmMIuJP_H7:-MMpf-bW84bmMIuJP_H8:bd6sxa0) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.hpp#L298)):*
> ```cpp
> 
> 	template <bool IC = IsConst>
> 	typename std::enable_if<!IC, std::pair<pmem::obj::slice<char *>, status>>::type
> ```

I think that in the public interface the return value of write_range should be rather:

```
std::pair<OutputIt<pmem::obj::slice<char *>>, status>
```

where output it is some class that fulfulls those (and only those!) requirements: https://en.cppreference.com/w/cpp/named_req/OutputIterator

We don't want to allow reading the data from write_range.
___
*[src/engines-experimental/csmap.cc, line 387 at r5](https://reviewable.io/reviews/pmem/pmemkv/831#-MMPvST8Bcbnmf2q3BoX:-MMPvST8Bcbnmf2q3BoY:b-i2ri76) ([raw file](https://github.com/pmem/pmemkv/blob/09f8eab93dcbba316559f4acd6ae5c05d0fa537d/src/engines-experimental/csmap.cc#L387)):*
> ```cpp
> 
> 	_it = container->begin();
> 	std::advance(_it, container->size() - 1);
> ```

I think if there is no way to implement seek_to_last in logn time this method should not be supported.
___
*[src/engines-experimental/csmap.cc, line 331 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpco13CWT5qnNxn9y3:-MMpco13CWT5qnNxn9y4:bju12bj) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines-experimental/csmap.cc#L331)):*
> ```cpp
> {
> 	if (_it != container->end())
> 		node_lock.unlock();
> ```

Is this necessary? I think the operator= below will call unlock() if any lock is held.
___
*[src/engines-experimental/csmap.cc, line 455 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpd49-Czj12Dziil5W:-MMpd49-Czj12Dziil5X:b-gk0pql) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines-experimental/csmap.cc#L455)):*
> ```cpp
> csmap::csmap_iterator<true>::read_range(size_t pos, size_t n)
> {
> 	if (_it == container->end())
> ```

Hm, I;m not sure if we should check this. We could just say it's UB to call read_range if next()/seek() returned NOT_FOUND. We could also just turn this check into an assert. @szyrom what do you think?
___
*[src/engines-experimental/csmap.cc, line 472 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpe-_L4xUfevTcmEnt:-MMpe-_L4xUfevTcmEnu:b-lxy27b) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines-experimental/csmap.cc#L472)):*
> ```cpp
> 	/* check if position of iterator changed */
> 	auto key = _it->first.cdata();
> 	if (snapshotted_key.compare(key) != 0) {
> ```

I'm not sure if snapshottig the key is the best approach (especially for really long keys). Maybe we could just call log.clear() at the beggining of next/seek etc.? This would basically have the same effect as abort, right?
___
*[src/engines-experimental/csmap.cc, line 480 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpeMQ63MxFRWGnh-E0:-MMpeMQ63MxFRWGnh-E1:byq0tqq) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines-experimental/csmap.cc#L480)):*
> ```cpp
> 		n = _it->second.val.size() - pos;
> 
> 	log.push_back({{_it->second.val.cdata(), n}, pos});
> ```

You don;t have to copy the data to the log here. It's fine for the log to be uninitialized - the user should not read from the write_log anyway.


<!-- Sent from Reviewable.io -->

2020-11-30 11:44 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.h, line 110 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MNNwJm97S7Cbr3ogWEk:-MNNwJmAEVMCIcMMkMDW:bslrta5) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.h#L110)):*
> ```objc
> pmemkv_write_iterator *pmemkv_write_iterator_new(pmemkv_db *db);
> 
> void pmemkv_iterator_delete(void *it);
> ```

Don't use voids everywhere.
Try making a common iterator struct (by either entirely removing the distinction between read and write iterators or creating an opaque "generic_iterator" struct and conversion functions or by creating a tagged union).

Looking at the API it seems that read iterators are just write iterators that don't have write APIs exposed. If that's the case, then I don't particularly see the motivation behind this...


<!-- Sent from Reviewable.io -->

2020-12-01 10:45 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @pbalcer)

___
*[src/libpmemkv.h, line 110 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MNNwJm97S7Cbr3ogWEk:-MNSsabg5Z5PnQ36zSel:b-hge8b0) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.h#L110)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Don't use voids everywhere.
Try making a common iterator struct (by either entirely removing the distinction between read and write iterators or creating an opaque "generic_iterator" struct and conversion functions or by creating a tagged union).

Looking at the API it seems that read iterators are just write iterators that don't have write APIs exposed. If that's the case, then I don't particularly see the motivation behind this...
</blockquote></details>

The motivation was to avoid explicit casts, if it's not void but rather pmemkv_read_iterator* or pmemkv_base_iterator* you'd have to do:

pmemkv_iterator_seek((pmemkv_base_iterator*)  write_iterator, ...);

but if you think it's fine the we can change it. Or as you said, we can just have one API struct and just check in runtime whether it's read or write and return NOT_SUPPORTED in write_range for read iterator. But I think I'd prefer the first solution with explicit casting.


<!-- Sent from Reviewable.io -->

2020-12-02 09:50 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.h, line 110 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MNNwJm97S7Cbr3ogWEk:-MNXqnRS7vu3-i5RWI4S:b-vvg051) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.h#L110)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The motivation was to avoid explicit casts, if it's not void but rather pmemkv_read_iterator* or pmemkv_base_iterator* you'd have to do:

pmemkv_iterator_seek((pmemkv_base_iterator*)  write_iterator, ...);

but if you think it's fine the we can change it. Or as you said, we can just have one API struct and just check in runtime whether it's read or write and return NOT_SUPPORTED in write_range for read iterator. But I think I'd prefer the first solution with explicit casting.
</blockquote></details>

but what's the point of this distinction between read and write? Can't you just have a single iterator type that's universal? Or does the behavior or read-only functions change if it's write iterator?


<!-- Sent from Reviewable.io -->

2020-12-02 11:02 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 27 of 34 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @pbalcer)

___
*[src/libpmemkv.h, line 110 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MNNwJm97S7Cbr3ogWEk:-MNXzVKy1-5IxmnHDx74:b-qp50rh) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/libpmemkv.h#L110)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

but what's the point of this distinction between read and write? Can't you just have a single iterator type that's universal? Or does the behavior or read-only functions change if it's write iterator?
</blockquote></details>

From API perspective the difference is only that write_iterator supports 3 additional methods - write_range, commit and abort. And yeah, I think you're right, we can just have one type: pmemkv_iterator* (both pmemkv_read_iterator and pmemkv_write_iterator would return this type) and if you use `pmemkv_write_range(pmemkv_read_iterator_new())` you'll just get NOT_SUPPORTED


<!-- Sent from Reviewable.io -->

2020-12-10 11:29 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 4 of 35 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/CMakeLists.txt, line 23 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMopEcX1pYIUkY_yo6B:-MMt6qhKDtz6I6JEDk4Y:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/CMakeLists.txt#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

check for whitespaces should be done for all files, hence `*.*` (above ones too)
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/CMakeLists.txt, line 7 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMorTSA5swv0xI8Bh1z:-MMtAXaQ8SZ3w_EFpJcX:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/CMakeLists.txt#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know we have it the same way in other examples, but actually - we can make it REQUIRED (instead of QUIET) and just skip check in the below `if`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 28 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMosCVn96UF2oNR3_8D:-MMt7G583SuxmmpC_BLo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use `std::endl` instead of `\n`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 43 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMotIUx0hv6SI3ovLIC:-MMt7SGj2Le6ec_Gj-k0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop the `\n` at the beginning of all the logs
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 67 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMow4hG6hHxVOs2Plsu:-MNTBkKwA7UCZo54elUT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L67)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

I think it is ok, however, I would add some comments like "key_result is a pair<X,Y> which stores this and that
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 71 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpESoPDeGFKlV3qP74:-MMtbfqB6XMBlPJaN_Lb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L71)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

a whole
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 72 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMovVDq0gBEg2uUlWgH:-MMtAtD9En9MI007BWeo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, I think for C++ api we could make both parametrs to have default values (pos = 0, n = numeric_limits::max())
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 81 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpDkc5-YibYafPn6p6:-MNTCYmGCYfL6J7e847_:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L81)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

use a const var for the number of elements we've put, and set cnt to this value. we are not sure if cnt was incremented desired number of times, I guess it.next() may return status different than OK and it won't mean that we reached end. Assert(cnt == some_var) after the look should be also there
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 87 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpEVPMDkx5Pb5_Ws71:-MNTCa98-NAh18wc0q5e:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L87)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

a key
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMows0P69C71SyVvPKb:-MNcKZtr8zj8W2h9tA2B:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make this read key & read value a function in this example
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 108 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMowo0z9DFSc_2_mu6g:-MNcKaCcBl8j0tBPwbEd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L108)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of the element
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 115 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMox3CCBienXsQ1DyFM:-MO0raWh9DWquz5k1WFr:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L115)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`get write range; ...` or `.` (instead of `;`)
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 115 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpFTK98nGdW8Nrrm4O:-MO0qzX67g-XredJAQs4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L115)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

a whole
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 141 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpFlAZ0aV74-Qw7HJ3:-MO0reZ52VOANnaBRFHW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L141)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

add a note where you open a db, that radix_tree is a single-threaded engine. Describe how it affects the usage of write iterators. Can we add also an example with a concurrent angine?
</blockquote></details>

Done.
___
*[src/iterator.h, line 34 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpaqHy6ut-lpR9NMoe:-MO0rm3sA60Lq7uTWI2N:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/iterator.h#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be useful to have something like is_next() (maybe the implementation could just be internal_it != end())? It would allow iterati [...]

2020-12-10 18:05 UTC, lukaszstolarczuk reviewed
> Reviewed 7 of 30 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 11 of 36 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/CMakeLists.txt, line 58 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCiU1b8cBbDKk7KWYX:-MOCiU1b8cBbDKk7KWYY:bqri3je) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/CMakeLists.txt#L58)):*
> ```CMake
> else()
> 	message(STATUS
> 			"Examples use cmap engine, which is disabled, hence they are "
> ```

maybe add "Some examples use..."
___
*[examples/CMakeLists.txt, line 76 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCi_a50Eltx_mPUQNI:-MOCi_a50Eltx_mPUQNJ:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/CMakeLists.txt#L76)):*
> ```CMake
> else()
> 	message(STATUS
> 		"Examples use csmap engine, which is disabled, hence they are "
> ```

.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 57 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCof-kETvB409ylgP4:-MOCof-kETvB409ylgP5:bi60ffz) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L57)):*
> ```cpp
> static std::string read_key(pmem::kv::db::read_iterator &it)
> {
> 	/* key_result's type is a pmem::kv::result<string_view>, for more informations
> ```

`information`
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 60 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCorYQ7lTZvfvsraaN:-MOCorYQ7lTZvfvsraaO:b8iyoxq) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L60)):*
> ```cpp
> 	 * check pmem::kv::result's documentation */
> 	auto key_result = it.key();
> 	/* check if the result is ok, alternatively you can do:
> ```

`you can also do:`
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 71 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCovAA8zayyeTXvxH0:-MOCovAA8zayyeTXvxH1:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L71)):*
> ```cpp
> static std::string read_value(pmem::kv::db::read_iterator &it)
> {
> 	/* val_result's type is a pmem::kv::result<string_view>, for more informations
> ```

.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 74 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCouPu1XUUmLG2mdE1:-MOCouPu1XUUmLG2mdE2:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L74)):*
> ```cpp
> 	 * check pmem::kv::result's documentation */
> 	auto val_result = it.read_range();
> 	/* check if the result is ok, alternatively you can do:
> ```

.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 145 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCjIwh8yAH3wo8UQJP:-MOCjIwiC0VgbyKBxqCh:bjfkc24) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L145)):*
> ```cpp
> 	std::string value_before_write = w_it.read_range().get_value().data();
> 
> 	/* Get a write range. Default it is a whole value (pos = 0, n =
> ```

it's either `By default it is...` or `Default is...`
___
*[src/libpmemkv.hpp, line 535 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnBfgCS_lAyPeRLmf:-MOCnBfgCS_lAyPeRLmg:b3br4z9) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L535)):*
> ```cpp
> 	iterator, and db.new_write_iterator() for a write iterator).
> 
> 	Both iterators types (write_iterator and read_iterator) allows reading record's
> ```

`Both iterator types`
___
*[src/libpmemkv.hpp, line 535 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnF_n8fPsTh0OdPKJ:-MOCnF_n8fPsTh0OdPKK:bkswz6) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L535)):*
> ```cpp
> 	iterator, and db.new_write_iterator() for a write iterator).
> 
> 	Both iterators types (write_iterator and read_iterator) allows reading record's
> ```

`allow`
___
*[src/libpmemkv.hpp, line 590 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCn_U-61MFI8amnr7T:-MOCn_U-61MFI8amnr7U:btzku77) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L590)):*
> ```cpp
> 
> /*! \class db::iterator::OutputIterator
> 	\brief OutputIterator provides iteration through elements without an option of
> ```

`without an option of...` -> it's better `without a possibility of...`
___
*[src/libpmemkv.hpp, line 591 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnUpz5SZDlHvpMxFI:-MOCnUpz5SZDlHvpMxFJ:b-6wqr0i) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L591)):*
> ```cpp
> /*! \class db::iterator::OutputIterator
> 	\brief OutputIterator provides iteration through elements without an option of
>    reading them, It is only allowed to modify them.
> ```

`them. It ...`
___
*[src/libpmemkv.hpp, line 695 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCoJHFEr51blLbkrNg:-MOCoJHFEr51blLbkrNh:bezeos4) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L695)):*
> ```cpp
>  * It internally aborts all uncommitted changes.
>  *
>  * @param[in] key record's key to change position for
> ```

`to change position to` I guess
___
*[tests/engine_scenarios/concurrent/iterator_concurrent.cc, line 5 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCm5nY3H4Ck0490LRF:-MOCm5nY3H4Ck0490LRG:b482h8a) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/tests/engine_scenarios/concurrent/iterator_concurrent.cc#L5)):*
> ```cpp
> 
> #include "../all/iterator.hpp"
> #include "unittest.hpp"
> ```

no need to include it - it's already in "../all/iterator.hpp"
___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 21 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCkk_9EV3dGhSxo439:-MOCkk_9EV3dGhSxo43A:b-y8ez8h) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/utils/docker/images/install-libpmemobj-cpp.sh#L21)):*
> ```Shell
> echo "PACKAGE_TYPE: ${PACKAGE_TYPE}"
> 
> # Merge pull request #927 from JanDorniak99/range_method_basic_string; 13.10.2020
> ```

please update the description and the date


<!-- Sent from Reviewable.io -->

2020-12-14 11:49 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 9 of 36 files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/CMakeLists.txt, line 58 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCiU1b8cBbDKk7KWYX:-MOV9DqXDVgnZf-uhUk7:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/CMakeLists.txt#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe add "Some examples use..."
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 76 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCi_a50Eltx_mPUQNI:-MOV9EAE-8zCTLszy5E5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/CMakeLists.txt#L76)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 57 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCof-kETvB409ylgP4:-MOV9RDJ-qgyGUvPp1FG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`information`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 60 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCorYQ7lTZvfvsraaN:-MOV9QiY16goE-5I1Bb2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`you can also do:`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 71 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCovAA8zayyeTXvxH0:-MOV9Ygt8VEgwErIcHqu:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 74 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCouPu1XUUmLG2mdE1:-MOV9YxzBmgmuOSkYG57:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 145 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCjIwh8yAH3wo8UQJP:-MOV9rStB4wSgWZxsUko:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's either `By default it is...` or `Default is...`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 535 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnBfgCS_lAyPeRLmf:-MOVAAxP3TUo14AoDrU2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L535)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Both iterator types`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 535 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnF_n8fPsTh0OdPKJ:-MOVABOuC87lx1SjV5n5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L535)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`allow`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 590 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCn_U-61MFI8amnr7T:-MOVAVhnDAelwWmuZkFm:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L590)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`without an option of...` -> it's better `without a possibility of...`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 591 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCnUpz5SZDlHvpMxFI:-MOVAW-bCxu1tZeSNHfC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L591)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`them. It ...`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 695 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCoJHFEr51blLbkrNg:-MOVAtkmEzKpT1WXLUtl:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L695)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`to change position to` I guess
</blockquote></details>

Done.
___
*[src/engines/cmap.cc, line 202 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpIj8Z61KdWHjkaW0r:-MOW2XnmBuWy67TXuyf0:bodsvfc) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L202)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

push_back may fail on reallocation, maybe we need to try-catch it? same for the other engines
</blockquote></details>

I think it will be caught in catch_and_return_status in libpmemkv.cc
___
*[tests/engine_scenarios/concurrent/iterator_concurrent.cc, line 5 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCm5nY3H4Ck0490LRF:-MOVB9r31XniZyiVYvjR:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/tests/engine_scenarios/concurrent/iterator_concurrent.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no need to include it - it's already in "../all/iterator.hpp"
</blockquote></details>

Done.
___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 21 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCkk_9EV3dGhSxo439:-MOVCBlt59bI85rDOSht:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/utils/docker/images/install-libpmemobj-cpp.sh#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please update the description and the date
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 13:48 UTC, igchor requested changes
> Reviewed 1 of 11 files at r1, 2 of 29 files at r5, 21 of 30 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 26 of 36 files reviewed, 52 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 27 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW8O862zPV86spOOyA:-MOW8O862zPV86spOOyB:baxbzpz) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L27)):*
> ```cpp
> const uint64_t SIZE = 1024UL * 1024UL * 1024UL;
> 
> static db *init_kv(const std::string &engine, const std::string &path, size_t n_elements)
> ```

I'd suggest using unique_ptr here so you don'y have to call delete
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 57 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCof-kETvB409ylgP4:-MOW6txE9G-SDR68Vp_u:beefh7s) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L57)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

maybe write the type explicitly, instead of using auto to make it more visible?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 91 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW7LQd6rMIx6ZMT8B4:-MOW7LQd6rMIx6ZMT8B5:b88fnu0) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L91)):*
> ```cpp
> 	/* get a new read iterator */
> 	auto res_it = kv->new_read_iterator();
> 	/* you need to take reference to the iterator from the result, because iterator
> ```

I think it would be good to add checking is_ok here (and write that you can only call get_value when the is_ok is true)
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 158 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW92WM8XVwbg3YBjwq:-MOW92WM8XVwbg3YBjwr:br8f4nn) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L158)):*
> ```cpp
> 	}
> 
> 	/* note that changes aren't visible until commit */
> ```

this can actually change if we swtich to undo logs - I'd say here that changes MIGHT not be visible and maybe comment the code?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 188 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW7zKHBMQMjAtaicS5:-MOW7zKHBMQMjAtaicS6:b-plfgim) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L188)):*
> ```cpp
> 	/* thread1 */
> 	threads.emplace_back([&]() {
> 		auto res_it = kv->new_read_iterator();
> ```

check for is_ok?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 202 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW80R86RbZ94jyUBsI:-MOW80R86RbZ94jyUBsJ:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L202)):*
> ```cpp
> 	/* thread2 */
> 	threads.emplace_back([&]() {
> 		auto res_it = kv->new_read_iterator();
> ```

.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 205 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW8CZjAbJ_gQ1Fv0n2:-MOW8CZjAbJ_gQ1Fv0n3:by5khhq) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L205)):*
> ```cpp
> 		auto &it = res_it.get_value();
> 		it.seek("5");
> 		/* reversed order */
> ```

how is this reversed order?
___
*[src/iterator.cc, line 58 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW9CeKE0gp0wSbbEL4:-MOW9CeKE0gp0wSbbEL5:bxpzmvo) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/iterator.cc#L58)):*
> ```cpp
> }
> 
> std::pair<pmem::obj::slice<char *>, status> iterator_base::write_range(size_t pos,
> ```

I think you can just return a result here. (or just return pmem::obj::slice<char*> and throw exception on error)
___
*[src/libpmemkv.hpp, line 466 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW9ihL7LNF9f9_xEX_:-MOW9ihL7LNF9f9_xEXa:b-j9qjjm) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L466)):*
> ```cpp
> 	class iterator;
> 
> 	class accessor;
> ```

is it still needed?
___
*[src/libpmemkv.hpp, line 605 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWAF5k2VwbOwjkpUkd:-MOWAF5k2VwbOwjkpUke:b-90fupz) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L605)):*
> ```cpp
> 	using iterator_category = std::output_iterator_tag;
> 
> 	OutputIterator(T *x) : ao(x)
> ```

I think it would be more consistent to implement those functions outside of class (like for db class).
___
*[src/libpmemkv.hpp, line 663 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWAX2z35B-OVIAwn14:-MOWAX2z35B-OVIAwn15:bdtl7ap) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L663)):*
> ```cpp
> 		}
> 
> 		assign_only &operator=(T x)
> ```

const T& x (if we ever decide to use it for something else than chars)
___
*[src/libpmemkv.cc, line 572 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWKh5QEDhEU4HYBxFZ:-MOWKh5QEDhEU4HYBxF_:b-q91wz7) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.cc#L572)):*
> ```cpp
> int pmemkv_read_iterator_new(pmemkv_db *db, pmemkv_iterator **it)
> {
> 	if (!db)
> ```

I think you can also check it.
___
*[src/libpmemkv.cc, line 587 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWKlNS1_4NI_mIsbkb:-MOWKlNS1_4NI_mIsbkc:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.cc#L587)):*
> ```cpp
> int pmemkv_write_iterator_new(pmemkv_db *db, pmemkv_write_iterator **it)
> {
> 	if (!db)
> ```

.
___
*[src/libpmemkv.cc, line 591 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWKv386ifkQ902sT-W:-MOWKv386ifkQ902sT-X:b-rrvqaj) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.cc#L591)):*
> ```cpp
> 
> 	try {
> 		*it = new pmemkv_write_iterator();
> ```

@pbalcer do you think it's OK to add this additional layer (one more allocation)? This was done so that all functions can accept `pmemv_iterator*` and `pmemkv_write_iterator*` instead of `pmemkv_write_iterator` (by copy)
___
*[src/engines/cmap.h, line 111 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWLWkIBTF5NW1XfQlL:-MOWLWkIBTF5NW1XfQlM:bthqjee) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/engines/cmap.h#L111)):*
> ```objc
> 	std::pair<string_view, status> key() final;
> 
> 	std::pair<pmem::obj::slice<const char *>, status> read_range(size_t pos,
> ```

I believe this can be just pmem::obj::slice<const char*>(or even string_view) without the pair. You can either return result<> or throw an exception. The same for key()
___
*[src/engines/cmap.h, line 127 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWLnHXB0be-QKk_tP6:-MOWLnHXB0be-QKk_tP7:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/engines/cmap.h#L127)):*
> ```objc
> 	cmap_iterator(container_type *container);
> 
> 	std::pair<pmem::obj::slice<char *>, status> write_range(size_t pos,
> ```

.
___
*[src/engines-experimental/csmap.cc, line 317 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWOGvm2fblBm7TkkLo:-MOWOGvm2fblBm7TkkLp:b-w2epic) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/engines-experimental/csmap.cc#L317)):*
> ```cpp
> 
> csmap::csmap_iterator<true>::csmap_ [...]

2020-12-14 13:57 UTC, igchor requested changes
> Reviewed 2 of 29 files at r5, 2 of 30 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 29 of 36 files reviewed, 54 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, @pbalcer, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWXbAU9OdNcXJwfpiB:-MOWXbAU9OdNcXJwfpiC:b4sio37) (no related file):*
Where are the manpages for C API? ;d

---
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 6 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWXghv2x2HfA19hGUf:-MOWXghv2x2HfA19hGUg:bkss7w2) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L6)):*
> ```cpp
> /*
>  * pmemkv_iterator.cpp -- example usage of pmemkv.
>  */
> ```

Please add some example with C API also


<!-- Sent from Reviewable.io -->

2020-12-14 14:03 UTC, pbalcer reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 29 of 36 files reviewed, 53 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

___
*[src/libpmemkv.cc, line 591 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWKv386ifkQ902sT-W:-MOWYuzP3nmrFEAJd10X:b-d0yseu) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.cc#L591)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

@pbalcer do you think it's OK to add this additional layer (one more allocation)? This was done so that all functions can accept `pmemv_iterator*` and `pmemkv_write_iterator*` instead of `pmemkv_write_iterator` (by copy)
</blockquote></details>

yup, its fine.

just maybe add a comment that this is on purpose because it looks odd when you look at the implementation.


<!-- Sent from Reviewable.io -->

2020-12-14 14:14 UTC, KFilipek reviewed
> Reviewed 1 of 11 files at r1, 2 of 30 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 55 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 66 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWYOD71e0Ya81-9kno:-MOWYOD71e0Ya81-9knp:bvor6uu) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L66)):*
> ```
> read_key
> ```
there is need to call explicitly std::string constructor?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 197 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWYGzI6WGuQtx5Fu0G:-MOWYGzI6WGuQtx5Fu0H:bcb08ik) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L197)):*
> ```
> "5"
> ```
read_key returns a std::string so, you can reorder to
read_key(it).compare("5") and it should be the same when you just checking !=0


<!-- Sent from Reviewable.io -->

2020-12-15 10:02 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 44 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

___
*[examples/CMakeLists.txt, line 58 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOCiU1b8cBbDKk7KWYX:-MO_jxfx3leUL46NhjdQ:b-ucfknh) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/CMakeLists.txt#L58)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 152 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MO_pyhJ362PtuY_BF3O:-MO_pyhK7pPblm9CexNK:b-7jos6t) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L152)):*
> ```cpp
> 	/* set all chars to 'x' */
> 	for (auto &c : res.get_value()) {
> 		/* note that you can't read elements from write_range, so f.e. char x = c
> ```

`f.e.`? did you mean `e.g.`?
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 153 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MO_q6rTCFpU3HYef7A5:-MO_q6rTCFpU3HYef7A6:bbilwy4) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L153)):*
> ```cpp
> 	for (auto &c : res.get_value()) {
> 		/* note that you can't read elements from write_range, so f.e. char x = c
> 		 * isn't possible, if you want to read a value, you need to use read_range
> ```

`possible. If you...`


<!-- Sent from Reviewable.io -->

2020-12-15 13:34 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 45 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOaav3mCLDqOZxhGFF7:-MOaav3mCLDqOZxhGFF8:brq69zg) (no related file):*
Also, we should mention somewhere that holding two iterators simultaneously in the same thread is undefined behavior for now.

---


<!-- Sent from Reviewable.io -->

2020-12-15 14:40 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 44 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWXbAU9OdNcXJwfpiB:-MOaUVnhCGQUSpfdt2iy:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Where are the manpages for C API? ;d
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOaav3mCLDqOZxhGFF7:-MOak4958h8kEnZCVr7i:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, we should mention somewhere that holding two iterators simultaneously in the same thread is undefined behavior for now.
</blockquote></details>

Done.

---
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 6 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWXghv2x2HfA19hGUf:-MO_jRi41f_iobCcjGiF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L6)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add some example with C API also
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 27 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW8O862zPV86spOOyA:-MO_GOtd6jDRy6iqyXWk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'd suggest using unique_ptr here so you don'y have to call delete
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 91 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW7LQd6rMIx6ZMT8B4:-MO_J9wW9d_UN90-7tBE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be good to add checking is_ok here (and write that you can only call get_value when the is_ok is true)
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 158 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW92WM8XVwbg3YBjwq:-MOa0jOlCcyWw0uK5LPn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L158)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can actually change if we swtich to undo logs - I'd say here that changes MIGHT not be visible and maybe comment the code?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 188 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW7zKHBMQMjAtaicS5:-MO_JFoi-oHmgM8FfUda:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L188)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

check for is_ok?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 202 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW80R86RbZ94jyUBsI:-MO_JdVQ5-BU2fICvzUF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L202)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 205 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW8CZjAbJ_gQ1Fv0n2:-MO_JiQp2w2z24kAouAL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L205)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

how is this reversed order?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 66 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWYOD71e0Ya81-9kno:-MO_GvoS0R_vmO2CCBLT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L66)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> read_key
> ```
there is need to call explicitly std::string constructor?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 152 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MO_pyhJ362PtuY_BF3O:-MO_v8Q25Oq38ki8RmmN:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`f.e.`? did you mean `e.g.`?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 153 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MO_q6rTCFpU3HYef7A5:-MO_vDA-9PIoU1CV5djR:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L153)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`possible. If you...`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 197 at r8](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWYGzI6WGuQtx5Fu0G:-MO_JZS6Elo_vEv9bAI-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/7e9b8551a66d821d2ba626ad0ef1837b26cecc0d/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L197)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> "5"
> ```
read_key returns a std::string so, you can reorder to
read_key(it).compare("5") and it should be the same when you just checking !=0
</blockquote></details>

Done.
___
*[src/iterator.cc, line 58 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW9CeKE0gp0wSbbEL4:-MO_u1Rg8KLxqnFBh3fI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/iterator.cc#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you can just return a result here. (or just return pmem::obj::slice<char*> and throw exception on error)
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 466 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOW9ihL7LNF9f9_xEX_:-MO_K1OgDTeYBzDPGPKW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L466)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is it still needed?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 605 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWAF5k2VwbOwjkpUkd:-MO_PFK25xuFxG14mKP_:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.hpp#L605)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be more consistent to implement those functions outside of class (like for db class).
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 663 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWAX2z35B-OVIAwn14:-MO_KJvr59KaqfrHnho8:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd2 [...]

2020-12-15 19:03 UTC, lukaszstolarczuk requested changes
> Reviewed 10 of 31 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 23 of 44 files reviewed, 61 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MLiCJn27D9l__JMpyIQ:-MObfMUq8pc_8dEMAmoC:b-gvqvug) (no related file):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

write iterators for libpmemobj-based engines will have the same commit method - I am not sure if it will be applicable here (the code will be complicated too much) to add an additional libpmemobj-based base iterator class?
</blockquote></details>

docs added, this is done.

@szyrom , what did you mean? I'm guessing this comment is put in wrong place...?

---
___
*[doc/libpmemkv.7.md, line 151 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObd2zW0dQrfZTKFyAg:-MObd2zW0dQrfZTKFyAh:b-nti7me) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv.7.md#L151)):*
> ```Markdown
> # SEE ALSO #
> 
> **libpmemkv**(3), **libpmemkv_config(3)**, **libpmemkv_iterator**(3), **pmempool**(1), **libpmemobj**(7) and **<https://pmem.io>** //iterator
> ```

drop the comment ;)
___
*[doc/libpmemkv_config.3.md.in, line 65 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObd6um92Bzp85BMcls:-MObd6um92Bzp85BMclt:bu2b1uw) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_config.3.md.in#L65)):*
> ```
> For general description of pmemkv and available engines see **libpmemkv**(7).
> For description of pmemkv core API see **libpmemkv**(3).
> For pmemkv iterator API description see **libpmemkv_iterator**(3).
> ```

I'm not sure if we need to link it from config - iterators does not use config (explicitly)
___
*[doc/libpmemkv_iterator.3.md.in, line 64 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObdgz7-SN2371GwBvR:-MObdgz84igL43vYDOeo:b-zfuagp) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L64)):*
> ```
> For general description of pmemkv and available engines see **libpmemkv**(7).
> For description of pmemkv core API see **libpmemkv**(3).
> For pmemkv configuration API description see **libpmemkv_config**(3).
> ```

not sure if config link needed
___
*[doc/libpmemkv_iterator.3.md.in, line 71 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgAnE91C43TCrHdqS:-MObgAnFDQFKoCjCC8Dj:boho9em) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L71)):*
> ```
> 
> Both iterator types (pmemkv_iterator (read) and pmemkv_write_iterator) allow reading record's
> key and value. To use pmemkv_write_iterator as a pmemkv_iterator you need to get his member "iter" (write_it->iter). 
> ```

trailing white space at the end of this line
___
*[doc/libpmemkv_iterator.3.md.in, line 77 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgOsn5Mox6l8m78il:-MObgOsn5Mox6l8m78im:byvz2ii) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L77)):*
> ```
> If an engine does not support a certain function, it will return PMEMKV\_STATUS\_NOT\_SUPPORTED.
> 
> Holding more iterators than one simultaneously in the same thread is undefined behavior.
> ```

I believe it's better: `Holding simultaneously in the same thread more than one iterator is ..`
___
*[doc/libpmemkv_iterator.3.md.in, line 92 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgoTvENoECArACgS_:-MObgoTvENoECArACgSa:b-dtqrfa) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L92)):*
> ```
> 
> `int pmemkv_iterator_seek(pmemkv_iterator *it, const char *k, size_t kb);`
> :	Changes iterator position to the record with given *key* (*k* is a pointer to the key's value and *kb* is a key's length). 
> ```

trailing whitespace at the end of this line
___
*[doc/libpmemkv_iterator.3.md.in, line 92 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObhF3p3uKt1GT_xcYs:-MObhF3p3uKt1GT_xcYt:brfjf2t) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L92)):*
> ```
> 
> `int pmemkv_iterator_seek(pmemkv_iterator *it, const char *k, size_t kb);`
> :	Changes iterator position to the record with given *key* (*k* is a pointer to the key's value and *kb* is a key's length). 
> ```

`key's value` might sound a little bit confusing. I know it's precise description, but maybe like it is in libpmemkv.3.md.in - just: key `k` of length `kb` ...?
___
*[doc/libpmemkv_iterator.3.md.in, line 99 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObheSQ1NA_Q96Vo9OT:-MObheSQ1NA_Q96Vo9OU:b-eoj24h) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L99)):*
> ```
> `int pmemkv_iterator_seek_lower(pmemkv_iterator *it, const char *k, size_t kb);`
> :	Changes iterator position to the record with key lower than given *key* (*k* is a pointer to the key's value and *kb* is a key's length).
> 	If the record is present and no errors occurred, returns PMEMKV_STATUS_OK. 
> ```

trailing whitespace at the end of this line

pls fix where applicable (check-whitespace does not work...? )
___
*[doc/libpmemkv_iterator.3.md.in, line 161 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObl3qS1xcCtT3ayBe-:-MObl3qS1xcCtT3ayBe0:b56re0f) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L161)):*
> ```
> :	Allows getting record's value's range which can be modified. 
> 	You can request for either full value or only value's subrange (n elements starting from pos). 
> 	Assigns pointer to the beginning of the requested range to *data*, and number of elements in range to *kb*.
> ```

pls describe, what if I request more than the value size
___
*[doc/libpmemkv_iterator.3.md.in, line 177 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObdkuK8RU2R7nJoKbJ:-MObdkuK8RU2R7nJoKbK:bjhnokm) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L177)):*
> ```
> + **PMEMKV_STATUS_OK** -- no error
> + **PMEMKV_STATUS_UNKNOWN_ERROR** -- unknown error
> + **PMEMKV_STATUS_NOT_FOUND** -- record (or config item) not found
> ```

I guess you can drop `(or config item)` since it won't regard config in case of iterators.
___
*[doc/libpmemkv_iterator.3.md.in, line 178 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObe0Mi6bcdr4OWgAzF:-MObe0Mi6bcdr4OWgAzG:b-klmxvh) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L178)):*
> ```
> + **PMEMKV_STATUS_UNKNOWN_ERROR** -- unknown error
> + **PMEMKV_STATUS_NOT_FOUND** -- record (or config item) not found
> + **PMEMKV_STATUS_NOT_SUPPORTED** -- fucntion is not supported with current iterator/engine type
> ```

`function` (misspell)
___
*[doc/libpmemkv_iterator.3.md.in, line 194 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObe8jiDfFcmnjnSpV-:-MObe8jiDfFcmnjnSpV0:bkhz7oi) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L194)):*
> ```
> # SEE ALSO #
> 
> **libpmemkv**(7), **libpmemkv**(3), **libpmemkv_config**(3), **libpmemkv_json_config**(3) and **<https://pmem.io>**
> ```

config and config_json not needed here (I guess)
___
*[doc/libpmemkv_json_config.3.md, line 39 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObem0K8faS6Ximl38t:-MObem0K8faS6Ximl38u:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_json_config.3.md#L39)):*
> ```Markdown
> For description of pmemkv core API see **libpmemkv**(3).
> For description of configuration API for [...]

2020-12-16 09:41 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 18 of 42 files reviewed, 61 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[doc/libpmemkv.7.md, line 151 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObd2zW0dQrfZTKFyAg:-MOeeHgh6cyW8FwOvwEX:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv.7.md#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop the comment ;)
</blockquote></details>

Done.
___
*[doc/libpmemkv_config.3.md.in, line 65 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObd6um92Bzp85BMcls:-MOeeV9B3urElcEJfTyF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_config.3.md.in#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if we need to link it from config - iterators does not use config (explicitly)
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 64 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObdgz7-SN2371GwBvR:-MOeeZ3K0uRxHC_XIR1B:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure if config link needed
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 71 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgAnE91C43TCrHdqS:-MOeecB6-MWjo55AK_18:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing white space at the end of this line
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 77 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgOsn5Mox6l8m78il:-MOeeop63pUIG5u_cM_T:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it's better: `Holding simultaneously in the same thread more than one iterator is ..`
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 92 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObgoTvENoECArACgS_:-MOef4Wo5qXbz6ellqtl:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing whitespace at the end of this line
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 92 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObhF3p3uKt1GT_xcYs:-MOehAKG2_AEygLMfP_5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`key's value` might sound a little bit confusing. I know it's precise description, but maybe like it is in libpmemkv.3.md.in - just: key `k` of length `kb` ...?
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 99 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObheSQ1NA_Q96Vo9OT:-MOehSQi3NaIhZosbmQA:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L99)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing whitespace at the end of this line

pls fix where applicable (check-whitespace does not work...? )
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 161 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObl3qS1xcCtT3ayBe-:-MOemt0y4dJJtx6hdcss:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls describe, what if I request more than the value size
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 177 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObdkuK8RU2R7nJoKbJ:-MOeir6nBoCSXhIs9Y3Q:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L177)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can drop `(or config item)` since it won't regard config in case of iterators.
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 178 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObe0Mi6bcdr4OWgAzF:-MOeiw995F0xHdCei9rW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L178)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`function` (misspell)
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 194 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObe8jiDfFcmnjnSpV-:-MOej2yjE-iVSK6gSCG-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_iterator.3.md.in#L194)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

config and config_json not needed here (I guess)
</blockquote></details>

Done.
___
*[doc/libpmemkv_json_config.3.md, line 39 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObem0K8faS6Ximl38t:-MOejGs-0sgnSQHe9TQv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/doc/libpmemkv_json_config.3.md#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 82 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObfDHkCLtIjR5HxdDg:-MOelADi1Cj7CuuqXLNd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/examples/CMakeLists.txt#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put it under `if(ENGINE_RADIX)` I believe
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_c/CMakeLists.txt, line 5 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObeyaKD5M09PauRwMg:-MOelDFs3J0SAusqEBJC:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/examples/pmemkv_iterator_c/CMakeLists.txt#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

CXX -> C
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_c/pmemkv_iterator.c, line 34 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MObj45N4Sqn4yDlnhe8:-MOelRrPEGPqeW6Bk4LU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/examples/pmemkv_iterator_c/pmemkv_iterator.c#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this buffer big enough?
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_c/pmemkv_iterator.c, line 102 at r9](https://reviewable.io/reviews/pmem/pmemkv/831#-MOblMLF4rAADqv8FMdN:-MOelaQE86LYYHWJd58r:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/78de7bab708b7d52dd9b8d2cdd39a12eaa69a1a3/exampl [...]

2020-12-16 11:18 UTC, igchor requested changes
> Reviewed 17 of 31 files at r9, 9 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 49 unresolved discussions (waiting on @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfElP42WDTj7XtUevR:-MOfElP51IUZU2KEXTzF:bm9esi4) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
> ```
> 
> Both iterator types (pmemkv_iterator (read) and pmemkv_write_iterator) allow reading record's
> key and value. To use pmemkv_write_iterator as a pmemkv_iterator you need to get his member "iter" (write_it->iter).
> ```

his -> its
___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfErVt4vI_xj7WFEa7:-MOfErVt4vI_xj7WFEa8:bmb2gih) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
> ```
> 
> Both iterator types (pmemkv_iterator (read) and pmemkv_write_iterator) allow reading record's
> key and value. To use pmemkv_write_iterator as a pmemkv_iterator you need to get his member "iter" (write_it->iter).
> ```

I think some simple code snippet how to call e.g. iterator_seek for both read and write iterator would be nice
___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfF0S91piOWCBJVPm1:-MOfF0S91piOWCBJVPm2:bplkkov) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L78)):*
> ```
> Holding simultaneously in the same thread more than one iterator is undefined behavior.
> 
> `int pmemkv__iterator_new(pmemkv_db *db, pmemkv_iterator **it);`
> ```

two underscores?
___
*[doc/libpmemkv_iterator.3.md.in, line 79 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfF2ywE-yweWkw_cEy:-MOfF2yxEj0MkUl9f1jy:b-razojh) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L79)):*
> ```
> 
> `int pmemkv__iterator_new(pmemkv_db *db, pmemkv_iterator **it);`
> :	Creates an instance of pmemkv_iterator (read iterator).
> ```

add info that it will be set to new instance (please look at pmemkv_open description).
___
*[doc/libpmemkv_iterator.3.md.in, line 94 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfFKpx9TB9fZEHEVdK:-MOfFKpx9TB9fZEHEVdL:b-7sxjlv) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L94)):*
> ```
> 	If the record is present and no errors occurred, returns PMEMKV_STATUS_OK.
> 	If the record does not exist, PMEMKV_STATUS_NOT_FOUND is returned and the iterator
> 	position is undefined. It internally aborts all uncommitted changes.
> ```

maybe "... changes made to a previous element"?
___
*[doc/libpmemkv_iterator.3.md.in, line 126 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfFVUR7-ETFZOU57c8:-MOfFVUR7-ETFZOU57c9:bwkq44c) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L126)):*
> ```
> 
> `int pmemkv_iterator_seek_to_last(pmemkv_iterator *it);`
> :	Changes iterator position to the lasy record. If db isn't empty, and no errors occurred, returns
> ```

typo 'lasy'
___
*[doc/libpmemkv_iterator.3.md.in, line 163 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfG4Cu8LFOjCGptnpt:-MOfG4Cu8LFOjCGptnpu:b-e5n7b4) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L163)):*
> ```
> 	Assigns pointer to the beginning of the requested range to `data`, and number of elements in range to `kb`.
> 	If `n` is bigger than number of elements in a value it's automatically shrinked.
> 	If the iterator is on an undefined position, calling this method is undefined behaviour.
> ```

Maybe add some information like "changes are not persistent until commit is called"
___
*[doc/libpmemkv_iterator.3.md.in, line 178 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfGD838wl8KaSXtkyT:-MOfGD838wl8KaSXtkyU:bz1zma7) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L178)):*
> ```
> + **PMEMKV_STATUS_OK** -- no error
> + **PMEMKV_STATUS_UNKNOWN_ERROR** -- unknown error
> + **PMEMKV_STATUS_NOT_FOUND** -- record not found
> ```

I think there can be more errors than this (e.g. OUT_OF_MEMORY). Maybe we could just link to error list in libpmemkv.3?
___
*[src/libpmemkv.cc, line 591 at r7](https://reviewable.io/reviews/pmem/pmemkv/831#-MOWKv386ifkQ902sT-W:-MOfDPfV-SHd5Z1YEbnZ:b-50wgzr) ([raw file](https://github.com/pmem/pmemkv/blob/cbcd23594d2b9c35d682027dfb8b6d6398df3d95/src/libpmemkv.cc#L591)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

yup, its fine.

just maybe add a comment that this is on purpose because it looks odd when you look at the implementation.
</blockquote></details>

@jandorniak99  can you add such comment?


<!-- Sent from Reviewable.io -->

2020-12-16 11:36 UTC, lukaszstolarczuk reviewed
> Reviewed 7 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 46 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfHWbI5jy6YIEPsaD-:-MOfHWbI5jy6YIEPsaD0:b-4s556v) (no related file):*
please add this new class to important classes listed in `src/README.md`

---
___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf12OV4gMqPYH_qcyI:-MOf12OV4gMqPYH_qcyJ:b-thmnio) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
> ```
> 
> Both iterator types (pmemkv_iterator (read) and pmemkv_write_iterator) allow reading record's
> key and value. To use pmemkv_write_iterator as a pmemkv_iterator you need to get his member "iter" (write_it->iter).
> ```

`get his member "iter"` -> get its member \`iter\`
___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf1zHD8w6PN1U9GCtp:-MOf1zHD8w6PN1U9GCtq:bqav235) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L78)):*
> ```
> Holding simultaneously in the same thread more than one iterator is undefined behavior.
> 
> `int pmemkv__iterator_new(pmemkv_db *db, pmemkv_iterator **it);`
> ```

misspell in function name - `__`
___
*[doc/libpmemkv_iterator.3.md.in, line 122 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf2mbgBOa7xiMyB5ZO:-MOf2mbgBOa7xiMyB5ZP:b-ycy3h6) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L122)):*
> ```
> `int pmemkv_iterator_seek_to_first(pmemkv_iterator *it);`
> :	Changes iterator position to the first record. If db isn't empty, and no errors occurred, returns
>  	PMEMKV_STATUS_OK. If db is empty, PMEMKV_STATUS_NOT_FOUND is returned and the iterator position is undefined.
> ```

space before tab (at the beginning of the line). Here and in few lines below, pls fix all
___
*[doc/libpmemkv_iterator.3.md.in, line 126 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf3igk5mDy4qCGznl1:-MOf3igk5mDy4qCGznl2:btuy747) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L126)):*
> ```
> 
> `int pmemkv_iterator_seek_to_last(pmemkv_iterator *it);`
> :	Changes iterator position to the lasy record. If db isn't empty, and no errors occurred, returns
> ```

`lasy` misspell
___
*[doc/libpmemkv_iterator.3.md.in, line 130 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf7fltBPQOLdQ79Au0:-MOf7fltBPQOLdQ79Au1:b-rit31g) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L130)):*
> ```
> 	It internally aborts all uncommitted changes.
> 
> `int pmemkv_iterator_is_next(pmemkv_iterator *it);`
> ```

perhaps we can have an alternate solution... as discussed offline, this may not work (in some engines) if last element was removed in the meantime
___
*[doc/libpmemkv_iterator.3.md.in, line 143 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfCcjX4MqpFxxImBKp:-MOfCcjYBxup03d0O32Y:bi6vjxm) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L143)):*
> ```
> `int pmemkv_iterator_prev(pmemkv_iterator *it);`
> :	Changes iterator position to the previous record.
>  	If the next record exists, returns PMEMKV_STATUS_OK, otherwise 
> ```

if the previous ;)
___
*[doc/libpmemkv_iterator.3.md.in, line 148 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfCjGX-A8xeUdwrvo2:-MOfCjGX-A8xeUdwrvo3:b-pgn5h9) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L148)):*
> ```
> 
> `int pmemkv_iterator_key(pmemkv_iterator *it, const char **k, size_t *kb);`
> :	Assigns record's key's address to `k` and key's length to `kb`. If the iterator is on an undefined position, 
> ```

trailing whitespace at the end
___
*[doc/libpmemkv_iterator.3.md.in, line 162 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf0pKt1ZhOGwxAkasH:-MOf0pKu4Xr6OzGcUO0o:b-bhvgmo) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L162)):*
> ```
> 	You can request for either full value or only value's subrange (n elements starting from pos).
> 	Assigns pointer to the beginning of the requested range to `data`, and number of elements in range to `kb`.
> 	If `n` is bigger than number of elements in a value it's automatically shrinked.
> ```

maybe I'm being picky, but what are `elements in a value`? maybe write `length of a value`?
___
*[doc/libpmemkv_iterator.3.md.in, line 166 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfDKjRD9YJivfUFMXI:-MOfDKjRD9YJivfUFMXJ:b-5q7so7) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L166)):*
> ```
> 
> `int pmemkv_write_iterator_commit(pmemkv_write_iterator *it);`
> :	Commits modifications made on the current record.
> ```

maybe extend this with info - it's required to call this function after any write (and before switching iterator to another position)...? 
___
*[examples/CMakeLists.txt, line 87 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfDjSU46cQGHynpK1_:-MOfDjSU46cQGHynpK1a:bx2aw21) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/examples/CMakeLists.txt#L87)):*
> ```CMake
> else()
> 	message(STATUS
> 		"Some examples use use radix engine, which is disabled, hence they are "
> ```

use use
___
*[src/libpmemkv.hpp, line 560 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfHJ83-kNzHwmQYOnj:-MOfHJ83-kNzHwmQYOnk:bttpztf) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L560)):*
> ```cpp
> 
> 	Holding simultaneously in the same thread more than one iterator is undefined
>    behavior.
> ```

this line starts with spaces instead of a tab; the same applies for the very next line
___
*[src/libpmemkv.hpp, line 794 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfIjRF4c2TGnwOszey:-MOfIjRF4c2TGnwOszez:btamtmn) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L794)):*
> ```cpp
>  * It internally aborts all uncommitted changes.
>  *
>  * @param[in] key record's key to change position to
> ```

it's not precise (we don't change position to this key exactly); perhaps, please compare with db::get_* functions
___
*[src/libpmemkv.hpp, line 969 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfGay91tU7q203gcow:-MOfGay91tU7q203gcox:bed5ael) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L969)):*
> ```cpp
> 		return {string_view{c, size}};
> 	else
> 		return {s};
> ```

codecov warning says this is not covered by tests (also not covered in the same return path in *_range functions)
___
*[src/libpmemkv.hpp, line 976 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfJ_I07uX_knS3k5Li:-MOfJ_I07uX_knS3k5Lj:bfr7ifh) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L976)):*
> ```cpp
>  *
>  * It is only used to read a value, if you want to modify the value, use
>  * db::iterator::write_range.
> ```

use write_range **instead**.
___
*[src/libpmemkv.hpp, line 981 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfJgRf2VKx4UJv-Ltc:-MOfJgRf2VKx4UJv-Ltd:bn4ttog) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L981)):*
> ```cpp
>  * behaviour.
>  *
>  * @param[in] pos position of value's element which will be the first element in the range
> ```

value's element - ?
___
* [...]

2020-12-17 11:52 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 37 of 43 files reviewed, 46 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfHWbI5jy6YIEPsaD-:-MOjuRIJAGo9DD-M7StX:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add this new class to important classes listed in `src/README.md`
</blockquote></details>

Done.

---
___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfElP42WDTj7XtUevR:-MOjaEt-8KOh9KRW6TXc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

his -> its
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf12OV4gMqPYH_qcyI:-MOjaFquEZRXva8l-sgZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`get his member "iter"` -> get its member \`iter\`
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 70 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfErVt4vI_xj7WFEa7:-MOjyR4NBv7dCrNIVhXY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think some simple code snippet how to call e.g. iterator_seek for both read and write iterator would be nice
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfF0S91piOWCBJVPm1:-MOjaPh-8rUnRz_W7q9y:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L78)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

two underscores?
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf1zHD8w6PN1U9GCtp:-MOjaQ9nDhfUZXnbLhuv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell in function name - `__`
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 79 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfF2ywE-yweWkw_cEy:-MOk-Otl15iGughBWZpS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L79)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

add info that it will be set to new instance (please look at pmemkv_open description).
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 94 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfFKpx9TB9fZEHEVdK:-MOk0GcLA7dPsLh5e6SK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L94)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe "... changes made to a previous element"?
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 122 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf2mbgBOa7xiMyB5ZO:-MOjemFA3Jh_yczOiq7E:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L122)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

space before tab (at the beginning of the line). Here and in few lines below, pls fix all
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 126 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfFVUR7-ETFZOU57c8:-MOjerT47z166gFbO-4F:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L126)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

typo 'lasy'
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 126 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf3igk5mDy4qCGznl1:-MOjers3DrdF28YGssAN:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L126)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`lasy` misspell
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 143 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfCcjX4MqpFxxImBKp:-MOjew4cAi-iUO52ZNNd:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L143)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if the previous ;)
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 148 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfCjGX-A8xeUdwrvo2:-MOjfF_w9xX2TsEWxqFL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing whitespace at the end
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 162 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOf0pKt1ZhOGwxAkasH:-MOjgjYJ6wwLBtz7o--6:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L162)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe I'm being picky, but what are `elements in a value`? maybe write `length of a value`?
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 163 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfG4Cu8LFOjCGptnpt:-MOjk_h7BrmSFpyzP4vN:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L163)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe add some information like "changes are not persistent until commit is called"
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 166 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfDKjRD9YJivfUFMXI:-MOk80g58c3ZiMLCjo43:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L166)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe extend this with info - it's required to call this function after any write (and before switching iterator to another position)...? 
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 178 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfGD838wl8KaSXtkyT:-MOk0p6r8Iya9y5zJSst:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/doc/libpmemkv_iterator.3.md.in#L178)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think there can be more errors than this (e.g. OUT_OF_MEMORY). Maybe [...]

2020-12-17 12:21 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 37 of 43 files reviewed, 39 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkcwh936UOohGpwcvo:-MOkcwh936UOohGpwcvp:b-ottu0) (no related file):*
If it's not mentioned anywhere, I think we should add info in libpmemkv.h (above the iterator functions), in manpage and in libpmemkv.hpp that iterators API is experiement and might change. I think it would be better to have some possibility to change it if we encounter any problems with tx and iterators integration.

---


<!-- Sent from Reviewable.io -->

2020-12-17 13:22 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 9 files at r10, 4 of 6 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 41 of 43 files reviewed, 31 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkjI0gAFRD-FIJ0NCB:-MOkjI0h-guGR2RtKVjW:b3elers) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/doc/libpmemkv_iterator.3.md.in#L78)):*
> ```
> 
> // write_it is already created pmemkv_write_iterator
> status = pmemkv_iterator_seek_to_first(write_it->iter);
> ```

int status
___
*[doc/libpmemkv_iterator.3.md.in, line 155 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkjrj77kEIkINklGpt:-MOkjrj87niVz5Qlxtoy:boem7s3) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/doc/libpmemkv_iterator.3.md.in#L155)):*
> ```
> 	If the previous record exists, returns PMEMKV_STATUS_OK, otherwise
> 	PMEMKV_STATUS_NOT_FOUND is returned and the iterator position is undefined.
> 	It internally aborts all changes made to a previous element.
> ```

maybe I'm being picky (again), but this may be misleading - `previous element` (especially) in this method may be not understood properly - perhaps `changes made to an element previously pointed by the iterator.`...? What do you think? (you may disregard this comment if you disagree) ;)
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 60 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkoYf82UnXWVYRuozL:-MOkoYf82UnXWVYRuozM:bmv7vxm) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L60)):*
> ```cpp
> {
> 	/* key_result's type is a pmem::kv::result<string_view>, for more information
> 	 * check pmem::kv::result's documentation */
> ```

I think you can drop `'s`
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 74 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkok2K0GCPTFf2SivA:-MOkok2L6nNXHvVKcxL1:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L74)):*
> ```cpp
> {
> 	/* val_result's type is a pmem::kv::result<string_view>, for more information
> 	 * check pmem::kv::result's documentation */
> ```

.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 135 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkpe3PA_d_OYleoaOY:-MOkpe3PA_d_OYleoaOZ:bv32dhn) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L135)):*
> ```cpp
> 	} while (it.prev() == status::OK);
> 
> 	/* get a new write iterator */
> ```

shouldn't we close the old iterator previously?

BTW, pls verify if examples compile and can be executed properly (unless you checked it already, ofcoz)
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 168 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkq61D6KU6DfWlccsi:-MOkq61E4VuwvUWBHYhY:b-qqvenw) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L168)):*
> ```cpp
> 
> 	std::string current_value = w_it.read_range().get_value().data();
> 	/* check if a value has changed */
> ```

if **the** value
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 182 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkqTc2-Mk2Ixg7I-_I:-MOkqTc2-Mk2Ixg7I-_J:b-grqrer) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L182)):*
> ```cpp
> 	auto kv = init_kv("csmap", path + "_csmap", n_elements);
> 
> 	/* create 2 threads, in first thread iterate from begin to the element with key
> ```

from the beginning
___
*[src/libpmemkv.hpp, line 560 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfHJ83-kNzHwmQYOnj:-MOkklb98iR27SWvNoYH:bvp3oem) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L560)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done in the next line (`Example usage...`) - pls put a tab instead of 4 spaces
___
*[src/libpmemkv.hpp, line 969 at r10](https://reviewable.io/reviews/pmem/pmemkv/831#-MOfGay91tU7q203gcow:-MOklIYtDBxXSDlhyiPr:b-5dwae7) ([raw file](https://github.com/pmem/pmemkv/blob/71b28dc92db263b669c34024ecbbbd58fc7f721e/src/libpmemkv.hpp#L969)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

codecov warning says this is not covered by tests (also not covered in the same return path in *_range functions)
</blockquote></details>

closing for now (as discussed)


<!-- Sent from Reviewable.io -->

2020-12-17 14:46 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 41 of 43 files reviewed, 31 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkcwh936UOohGpwcvo:-MOl6Jbu36Ja-4A1p9Ay:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If it's not mentioned anywhere, I think we should add info in libpmemkv.h (above the iterator functions), in manpage and in libpmemkv.hpp that iterators API is experiement and might change. I think it would be better to have some possibility to change it if we encounter any problems with tx and iterators integration.
</blockquote></details>

Done.

---
___
*[doc/libpmemkv_iterator.3.md.in, line 78 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkjI0gAFRD-FIJ0NCB:-MOktNHU9v7ev7z1n1Ll:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/doc/libpmemkv_iterator.3.md.in#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

int status
</blockquote></details>

Done.
___
*[doc/libpmemkv_iterator.3.md.in, line 155 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkjrj77kEIkINklGpt:-MOl4M332qOi1UTmKH6S:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/doc/libpmemkv_iterator.3.md.in#L155)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe I'm being picky (again), but this may be misleading - `previous element` (especially) in this method may be not understood properly - perhaps `changes made to an element previously pointed by the iterator.`...? What do you think? (you may disregard this comment if you disagree) ;)
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 60 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkoYf82UnXWVYRuozL:-MOku2I75s73TWPxnbK5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think you can drop `'s`
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 74 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkok2K0GCPTFf2SivA:-MOkuuQFAHP1IkCB-Kpl:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 135 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkpe3PA_d_OYleoaOY:-MOl29LW3JVO9gJ6mBUV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L135)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we close the old iterator previously?

BTW, pls verify if examples compile and can be executed properly (unless you checked it already, ofcoz)
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 168 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkq61D6KU6DfWlccsi:-MOkxcXh5c88s9xa9snc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L168)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if **the** value
</blockquote></details>

Done.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 182 at r11](https://reviewable.io/reviews/pmem/pmemkv/831#-MOkqTc2-Mk2Ixg7I-_I:-MOkxhGM12iobQPKvlr7:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/859cdb14607d2d85e97dab662bfd9acd4608cf73/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L182)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

from the beginning
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-18 09:55 UTC, igchor requested changes
> Reviewed 1 of 6 files at r11, 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 32 unresolved discussions (waiting on @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 92 at r12](https://reviewable.io/reviews/pmem/pmemkv/831#-MOpG3BF0uOYa7HYK-nn:-MOpG3BG9lpe93u2Usho:b-7m2bx0) ([raw file](https://github.com/pmem/pmemkv/blob/988174a71f38021b86371cf9f001c0a07f2688f2/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L92)):*
> ```cpp
> 
> 	/* We shouldn't hold simultaneously in the same thread more than one iterator. So
> 	 * every iterator in this example will be in the other scope */
> ```

in a separate scope
___
*[src/libpmemkv.hpp, line 551 at r12](https://reviewable.io/reviews/pmem/pmemkv/831#-MOpG70kDR4N2GHTtJYb:-MOpG70kDR4N2GHTtJYc:bgrw6un) ([raw file](https://github.com/pmem/pmemkv/blob/988174a71f38021b86371cf9f001c0a07f2688f2/src/libpmemkv.hpp#L551)):*
> ```cpp
> /*! \class db::iterator
> 	\brief Iterator provides methods to iterate over records in db. This class is
> 	experimental so far and might change.
> ```

I think it would be better to put this info about experimental API in uppercase, similar as in transactions API PR: https://github.com/pmem/pmemkv/blob/29254a11f234dbb4d581f31179de14f6ca26a096/src/libpmemkv.hpp#L475 (also in other places)


<!-- Sent from Reviewable.io -->

2020-12-18 11:04 UTC, KFilipek reviewed
> Reviewed 1 of 31 files at r9, 1 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 30 unresolved discussions (waiting on @JanDorniak99, @lukaszstolarczuk, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-21 08:01 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 39 of 43 files reviewed, 28 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

___
*[src/libpmemkv.hpp, line 551 at r12](https://reviewable.io/reviews/pmem/pmemkv/831#-MOpG70kDR4N2GHTtJYb:-MP3G3kn3KQ77Q0JLRf-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/988174a71f38021b86371cf9f001c0a07f2688f2/src/libpmemkv.hpp#L551)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better to put this info about experimental API in uppercase, similar as in transactions API PR: https://github.com/pmem/pmemkv/blob/29254a11f234dbb4d581f31179de14f6ca26a096/src/libpmemkv.hpp#L475 (also in other places)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-21 11:26 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831#-:-MP429b5DnJVpkpPBVBq:bnfp4nl)* status: 39 of 43 files reviewed, 27 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-21 11:44 UTC, KFilipek reviewed
> Reviewed 1 of 31 files at r9, 1 of 6 files at r11, 2 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 41 of 43 files reviewed, 35 unresolved discussions (waiting on @igchor, @JanDorniak99, @lukaszstolarczuk, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 23 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43gF-05XOVm8rX-WC:-MP43gF0CGWWm82Kssiy:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L23)):*
> ```
> 
> 
> # NAME #
> ```

.
___
*[doc/libpmemkv_iterator.3.md.in, line 29 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43htL72LBZZhJf9Hn:-MP43htL72LBZZhJf9Ho:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L29)):*
> ```
> This API is EXPERIMENTAL and might change.
> 
> # SYNOPSIS #
> ```

.
___
*[doc/libpmemkv_iterator.3.md.in, line 67 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3hu6h5-NhXylE-uW-:-MP3hu6h5-NhXylE-uW0:b-upqxta) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L67)):*
> ```
> For description of pmemkv core API see **libpmemkv**(3).
> 
> # DESCRIPTION #
> ```

I suppose that it should be:
# Description
___
*[doc/libpmemkv_iterator.3.md.in, line 192 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43ozs5CQzsNa3Uxa5:-MP43ozs5CQzsNa3Uxa6:b2i4thu) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L192)):*
> ```
> :	Aborts uncommitted modifications made on the current record.
> 
> ## ERRORS ##
> ```

Remove ## from the end of line, only first letter should be capital
___
*[doc/libpmemkv_iterator.3.md.in, line 197 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP446ZP8w2X5ypjpmvL:-MP446ZP8w2X5ypjpmvM:b-dy0ta1) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L197)):*
> ```
> returns one of the pmemkv status codes. To check possible options see **libpmemkv**(3).
> 
> # EXAMPLE #
> ```

Remove # from the end of line, only first letter should be capital
___
*[doc/libpmemkv_iterator.3.md.in, line 201 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP448OSB22fyuFfuo2k:-MP448OSB22fyuFfuo2l:b2i4thu) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L201)):*
> ```
> The following example is taken from `examples/pmemkv_iterator_c` directory.
> 
> ## BASIC EXAMPLE ##
> ```

Remove ## from the end of line, only first letter should be capital
___
*[doc/libpmemkv_iterator.3.md.in, line 209 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP449XT6ICc41isIeMm:-MP449XT6ICc41isIeMn:b-dy0ta1) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L209)):*
> ```
> ```
> 
> # SEE ALSO #
> ```

Remove # from the end of line, only first letter should be capital
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 126 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP44VI8D7FtpqN-e_B1:-MP44VI8D7FtpqN-e_B2:b-wmg1dw) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L126)):*
> ```cpp
> 		do {
> 			/* read a key */
> 			auto key = read_key(it);
> ```

Did you try to compile this code without logging and asserting? You will get "key is declared, but not used" in this scope.


<!-- Sent from Reviewable.io -->

2020-12-21 11:45 UTC, KFilipek commented
PS
If it's in "man" style it should be okay, but trailing #* has no effect anyway.

2020-12-21 13:13 UTC, lukaszstolarczuk requested changes
> Reviewed 5 of 29 files at r5, 2 of 30 files at r7, 1 of 5 files at r8, 4 of 31 files at r9, 1 of 6 files at r11, 1 of 5 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 55 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4QQDb1xoBlaqSMXSg:-MP4QQDb1xoBlaqSMXSh:b-bs0o3) (no related file):*
iterator.cc has low coverage on your branch (see: https://codecov.io/gh/pmem/pmemkv/src/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/iterator.cc) - I'm not sure why and if we should worry

---
___
*[doc/libpmemkv_iterator.3.md.in, line 67 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3hu6h5-NhXylE-uW-:-MP47ckM-4SztnksMa2S:b4uuhbi) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L67)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I suppose that it should be:
# Description

</blockquote></details>

This is how we and the world do manpages' headers apparently, see e.g.:
https://pmem.io/pmdk/manpages/linux/master/libpmemobj/libpmemobj.7.html
or
https://man7.org/linux/man-pages/man1/less.1.html
___
*[src/iterator.cc, line 70 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3b3bg9HKGcPlgwFK8:-MP3b3bg9HKGcPlgwFK9:bv20gel) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/iterator.cc#L70)):*
> ```cpp
> void iterator_base::abort()
> {
> 	/* defaulty NOT_SUPPORTED */
> ```

`by default`
___
*[src/libpmemkv.h, line 134 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3c9AWDmy5_iab8ME5:-MP3c9AX2uFJ-8u-M2PJ:b-qw3373) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.h#L134)):*
> ```objc
> 
> int pmemkv_iterator_read_range(pmemkv_iterator *it, size_t pos, size_t n,
> 			       const char **data, size_t *kb);
> ```

why `kb`? perhaps it should be `rb` (as in: range bytes) or just `vb`...?
___
*[src/libpmemkv.hpp, line 541 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4A4hVChGws_FNCzNI:-MP4A4hVChGws_FNCzNJ:bu16f21) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L541)):*
> ```cpp
> 
> 	result<write_iterator> new_write_iterator();
> 	result<read_iterator> new_read_iterator();
> ```

(picky as always) pls switch places, make read_iter first one, of these two
___
*[src/libpmemkv.hpp, line 554 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3dPkeCeAltkKmZ924:-MP3dPkf2gn5CLii6Euk:bcll1ww) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L554)):*
> ```cpp
> 	EXPERIMENTAL API
> 
> 	It can be only created by methods in db (db.new_read_iterator() - for a read
> ```

pls make it `db::new_read_iterator()` - docs should link well then
___
*[src/libpmemkv.hpp, line 982 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nPDz5iPIhhh-Qwoq:-MP3nPE-AUklCr_R1aFz:b-v8don6) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L982)):*
> ```cpp
>  * Returns value's range (pmem::kv::string_view) to read, in pmem::kv::result.
>  *
>  * It is only used to read a value, if you want to modify the value, use
> ```

`... a value. If ...`
___
*[src/libpmemkv.hpp, line 991 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nVsuC6d9A2z9LA2S:-MP3nVsuC6d9A2z9LA2T:b-4qz7pi) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L991)):*
> ```cpp
>  * the returned range (default = 0)
>  * @param[in] n number of elements in range (default = std::numeric_limits<size_t>::max(),
>  * if n is bigger than length of a value it's automatically shrinked)
> ```

the length
___
*[src/libpmemkv.hpp, line 1014 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nm677TP_0leuv2MH:-MP3nm677TP_0leuv2MI:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L1014)):*
> ```cpp
>  * in pmem::kv::result.
>  *
>  * It is only used to modify a value, if you want to read the value, use
> ```

.
___
*[src/libpmemkv.hpp, line 1025 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nuL877Ix0HoIg8Ri:-MP3nuL877Ix0HoIg8Rj:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L1025)):*
> ```cpp
>  * the returned range (default = 0)
>  * @param[in] n number of elements in range (default = std::numeric_limits<size_t>::max(),
>  * if n is bigger than length of a value it's automatically shrinked)
> ```

.
___
*[src/libpmemkv.cc, line 608 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zbj_90oUBWnUI4KE:-MP3zbjaACctdyPcCp-2:b-tk4elh) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L608)):*
> ```cpp
> {
> 	if (!it)
> 		return;
> ```

set ERR perhaps
___
*[src/libpmemkv.cc, line 622 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zuiv8dcdZ-LzBlYA:-MP3zuiv8dcdZ-LzBlYB:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L622)):*
> ```cpp
> {
> 	if (!it)
> 		return;
> ```

.
___
*[src/libpmemkv.cc, line 740 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-V2l5Z9v5k4pstLr:-MP4-V2l5Z9v5k4pstLs:baa8cl1) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L740)):*
> ```cpp
> 			return static_cast<int>(ret.get_status());
> 
> 		auto value = std::move(ret).get_value();
> ```

`value` may be confusing, perhaps rename this var to `key`...?
___
*[src/libpmemkv.cc, line 760 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-fLYAvE4O1D07n70:-MP4-fLYAvE4O1D07n71:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L760)):*
> ```cpp
> 			return static_cast<int>(ret.get_status());
> 
> 		auto value = std::move(ret).get_value();
> ```

.
___
*[src/libpmemkv.cc, line 779 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-k4Q4zvGv_5nmTx-:-MP4-k4Q4zvGv_5nmTx0:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L779)):*
> ```cpp
> 			return static_cast<int>(ret.get_status());
> 
> 		auto value = std::move(ret).get_value();
> ```

.
___
*[src/engines/cmap.h, line 115 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4269E-Jx8cCzntztU:-MP4269E-Jx8cCzntztV:b-4qyp38) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/engines/cmap.h#L115)):*
> ```objc
> protected:
> 	container_type *container;
> 	container_type::accessor _acc;
> ```

rename to `acc_` (?)
___
*[src/engines/vsmap.cc, line 332 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP484IE30-ToexHhPyc:-MP484IE30-ToexHhPyd:b-nras8a) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/engines/vsmap.cc#L332)):*
> ```cpp
> 	init_seek();
> 
> 	_it = container->find(vsmap::key_type(key.data(), key.size(), *kv_allocator));
> ```

rename to `it_` (?)
___
*[tests/engine_scenarios/concurrent/iterator_concurrent.cc, line 5 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4LAMF2m53eVo3HLKL:-MP4LAMF2m53eVo3HLKM:bqdltjf) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_scenarios/concurrent/iterator_concurrent.cc#L5)):*
> ```cpp
> 
> #include "../all/iterator.hpp"
> ```

pls add short description
___
*[tests/engine_scenarios/pmreorder/iterator.cc, line 5 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4KW0c38xvXZ-TZHSg:-MP4KW0c38xvXZ-TZHSh:beiysgx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_s [...]

2020-12-21 14:31 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 56 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 192 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43ozs5CQzsNa3Uxa5:-MP4hI_uDqL6AGx-Bd6F:bbsx8bw) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L192)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Remove ## from the end of line, only first letter should be capital
</blockquote></details>

we have done this similarly in other manpages, I'm not sure if that's necessary (if so, we should change all manpages)
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 1 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4h-qO1S8-jbk0Druk:-MP4h-qO1S8-jbk0Drul:b-ew7bl3) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_scenarios/all/iterator_basic.cc#L1)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> ```

similarly to how Igor did in his PR (tx API) - move this file one level up; it's a helper class for more iterator's tests


<!-- Sent from Reviewable.io -->

2020-12-21 14:54 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 56 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 192 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43ozs5CQzsNa3Uxa5:-MP4gQU51CaCrFIP-tl_:b-q5d8c) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L192)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Remove ## from the end of line, only first letter should be capital
</blockquote></details>

I'm not sure if it has any effect but it;s a convention we keep.
___
*[examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp, line 126 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP44VI8D7FtpqN-e_B1:-MP4gEkG3w6_9727FbZx:b-4xzlsf) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/examples/pmemkv_iterator_cpp/pmemkv_iterator.cpp#L126)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Did you try to compile this code without logging and asserting? You will get "key is declared, but not used" in this scope.
</blockquote></details>

Which is fine I guess, what else could we do with this key?


<!-- Sent from Reviewable.io -->

2020-12-21 15:29 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 56 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[doc/libpmemkv_iterator.3.md.in, line 192 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP43ozs5CQzsNa3Uxa5:-MP4uIzI8ZqoyLdjlD9w:bpwss6u) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/doc/libpmemkv_iterator.3.md.in#L192)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if it has any effect but it;s a convention we keep.
</blockquote></details>

Even with trailing ##?


<!-- Sent from Reviewable.io -->

2020-12-22 10:33 UTC, szyrom reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 40 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines/cmap.cc, line 199 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpJnWH7j__nWlMrG7F:-MP9-Q9304A_RlB7s0RY:b-tx7kfe) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L199)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

I think it always is >= 0 (n is size_t)
</blockquote></details>

n >=0 implies pos + n < pos is always false


<!-- Sent from Reviewable.io -->

2020-12-28 09:22 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: all files reviewed, 40 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4QQDb1xoBlaqSMXSg:-MP9GWUa2vUeF8hEBRpq:bdtyvd) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

iterator.cc has low coverage on your branch (see: https://codecov.io/gh/pmem/pmemkv/src/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/iterator.cc) - I'm not sure why and if we should worry
</blockquote></details>

I think to cover this lines we should have something like "blackhole iterator" or #867

---
___
*[src/iterator.cc, line 70 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3b3bg9HKGcPlgwFK8:-MP9HyYn6GZYocnguJzi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/iterator.cc#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`by default`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 541 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4A4hVChGws_FNCzNI:-MP9JRmH3xZss0SB2BwZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L541)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

(picky as always) pls switch places, make read_iter first one, of these two
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 554 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3dPkeCeAltkKmZ924:-MP9JXoy-WwJaBTXJdT4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L554)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it `db::new_read_iterator()` - docs should link well then
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 982 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nPDz5iPIhhh-Qwoq:-MP9JhU65lSoErsEqjnB:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L982)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`... a value. If ...`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 991 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nVsuC6d9A2z9LA2S:-MP9JliU-rHUW_h80Npg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L991)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the length
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1014 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nm677TP_0leuv2MH:-MP9JqtK9Wv9Cc_y7kGK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L1014)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1025 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3nuL877Ix0HoIg8Ri:-MP9JrAo41ivwJm8XzrT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.hpp#L1025)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 608 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zbj_90oUBWnUI4KE:-MP9L-0l0ll9xax4HYzZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L608)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

set ERR perhaps
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 622 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zuiv8dcdZ-LzBlYA:-MP9L-fID3RlZrJr-IB4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L622)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 740 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-V2l5Z9v5k4pstLr:-MP9LiJQ1T58BajZeKM-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L740)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`value` may be confusing, perhaps rename this var to `key`...?
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 760 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-fLYAvE4O1D07n70:-MP9MYgxE7NEpHSVtAJ2:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L760)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 779 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4-k4Q4zvGv_5nmTx-:-MP9MZ5Q3on1swhBNhha:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L779)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/engines/cmap.h, line 115 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4269E-Jx8cCzntztU:-MP9QdIaAFzRhtsSmIAk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/engines/cmap.h#L115)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rename to `acc_` (?)
</blockquote></details>

Done.
___
*[src/engines/cmap.cc, line 199 at r6](https://reviewable.io/reviews/pmem/pmemkv/831#-MMpJnWH7j__nWlMrG7F:-MP9R7v--sF-jdiaFBa-:b-my0eun) ([raw file](https://github.com/pmem/pmemkv/blob/1e0b60fa29e58525aeca22e3a58e7b858f74df37/src/engines/cmap.cc#L199)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

n >=0 implies pos + n < pos is always false
</blockquote></details>

It checks overflow, e.g. if we want all elements from the second position to the end we can do: write_range(2, std::numeric_limits<size_t>::max()) and then we got pos + n < pos. 
___
*[src/engines/vsmap.cc, line 332 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP484IE30-ToexHhPyc:-MP9Qf1y5IqVXHEbfT-V:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/engines/vsmap.cc#L332)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rename to `it_` (?)
</blockquote></details>

Done.
___
*[tests/engine_scenarios/concurrent/iterator_concurrent.cc, line 5 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4LAMF2m53eVo3HLKL:-MP9h4Wm-ZktWX7SaEY-:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_scenarios/concurrent/iterator_concurrent.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add short description
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmreorder/iterator.cc, line 5 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4KW0c38xvXZ-TZHSg:-MP9hKQM7l3BJFL_sTf1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_scenarios/pmreorder/iterator.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i [...]

2020-12-28 13:23 UTC, lukaszstolarczuk requested changes
> Reviewed 19 of 31 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 30 of 42 files reviewed, 17 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[src/libpmemkv.hpp, line 581 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPcpmap1bp7i3UFvDGe:-MPcpmap1bp7i3UFvDGf:bwilg6e) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/src/libpmemkv.hpp#L581)):*
> ```cpp
> 	\brief Iterator provides methods to iterate over records in db.
> 
> 	EXPERIMENTAL API
> ```

pls make it as in tx: `This API is EXPERIMENTAL and might change.`
___
*[src/libpmemkv.cc, line 608 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zbj_90oUBWnUI4KE:-MPcrHoy88TKnjXQ-rrk:b8tdxqg) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L608)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, maybe it better to do it similarly to `pmemkv_tx_abort` and just do nothing, as it was before; delete function may just do nothing on null
___
*[src/libpmemkv.cc, line 622 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP3zuiv8dcdZ-LzBlYA:-MPcrWVp8xuraMS_8lON:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/src/libpmemkv.cc#L622)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[src/libpmemkv.cc, line 885 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPcsDk96fvfrVZiJQ5U:-MPcsDk96fvfrVZiJQ5V:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/src/libpmemkv.cc#L885)):*
> ```cpp
> {
> 	if (!it) {
> 		ERR() << "Iterator not found";
> ```

.
___
*[tests/engine_scenarios/concurrent/iterator_concurrent.cc, line 5 at r13](https://reviewable.io/reviews/pmem/pmemkv/831#-MP4LAMF2m53eVo3HLKL:-MPdR42SBHUkTb4uv-di:b-9qg1u4) ([raw file](https://github.com/pmem/pmemkv/blob/9897fbcd3032078f6628f688cfae5987e3a8ae8a/tests/engine_scenarios/concurrent/iterator_concurrent.cc#L5)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 210 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVPT172nOV9Z9KbZR:-MPdVPT172nOV9Z9KbZS:b-hsx66p) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/sorted/iterator_sorted.cc#L210)):*
> ```cpp
> 	});
> 
> 	/* write something after seek_to_last() */
> ```

seek_to_first()
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 278 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVySv69wI7NkhtmXp:-MPdVySv69wI7NkhtmXq:bfjybft) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/sorted/iterator_sorted.cc#L278)):*
> ```cpp
> 			 });
> 
> 	/* check if iterator supports prev method */
> ```

`... prev and seek_to_last methods */`
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 23 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVnjH8UjmBcjmD_ZU:-MPdVnjH8UjmBcjmD_ZV:b-sps5w2) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/all/iterator_basic.cc#L23)):*
> ```cpp
> 	insert_keys(kv);
> 
> 	std::for_each(keys.begin(), keys.end(), [&](pair p) {
> ```

maybe extract this into a common function ('verify_keys' perhaps) - it can be used in several places in these tests


<!-- Sent from Reviewable.io -->

2020-12-28 13:59 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831)* status: 24 of 42 files reviewed, 17 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[src/libpmemkv.hpp, line 581 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPcpmap1bp7i3UFvDGe:-MPdXww43te3XXBv5lNA:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/src/libpmemkv.hpp#L581)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it as in tx: `This API is EXPERIMENTAL and might change.`
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 885 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPcsDk96fvfrVZiJQ5U:-MPdYOc04LDAFfkaKbEY:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/src/libpmemkv.cc#L885)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 210 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVPT172nOV9Z9KbZR:-MPdZqv1A7IBsooYFxLq:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/sorted/iterator_sorted.cc#L210)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

seek_to_first()
</blockquote></details>

Done.
___
*[tests/engine_scenarios/sorted/iterator_sorted.cc, line 278 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVySv69wI7NkhtmXp:-MPdZyyfCr3OC9Y_MiG1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/sorted/iterator_sorted.cc#L278)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`... prev and seek_to_last methods */`
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/iterator_basic.cc, line 23 at r14](https://reviewable.io/reviews/pmem/pmemkv/831#-MPdVnjH8UjmBcjmD_ZU:-MPdcp788xsvBsnZG93a:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e430ee1edd96bdfe7c70988169e3957e76af4390/tests/engine_scenarios/all/iterator_basic.cc#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe extract this into a common function ('verify_keys' perhaps) - it can be used in several places in these tests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-28 14:25 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831#-:-MPdjH7j0Wz0j_fb-X2I:bnfp4nl)* status: 30 of 42 files reviewed, 11 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, @lukaszstolarczuk, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-28 15:55 UTC, szyrom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/831#-:-MPe2qQI4gUBvrnYGXtX:bnfp4nl)* status: 30 of 42 files reviewed, 10 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-12-28 15:55 UTC, merged