add result class to C++ API
pmem/pmemkv pull request #852
Opened 2020-12-01 10:08 UTC by JanDorniak99

2020-12-01 11:24 UTC, karczex reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852#-:-MNT2-Ki24nh_96duoUz:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-01 11:52 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 145 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7gwVE3WS8k3awudn:-MNT7gwVE3WS8k3awudo:b-d06tm3) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L145)):*
> ```cpp
>    language.
> 
> 	If result contains value: is_ok() returns true, ok() returns value, is_error()
> ```

I think you could move those comments above the appropraite methods instead of having it for the entire class.
___
*[src/libpmemkv.hpp, line 163 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT882wAuL3q2-PQ1W9:-MNT882wAuL3q2-PQ1WA:b-8c2akn) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L163)):*
> ```cpp
> 	result(const OkType &val);
> 	result(const ErrType &err);
> 	result(const result &other);
> ```

if you define copy ctor you should also define copy assignment 


<!-- Sent from Reviewable.io -->

2020-12-01 12:26 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/libpmemkv.hpp, line 142 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7RMw7CUvI8eSk7iB:-MNT7RMw7CUvI8eSk7iC:bjgmbkr) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L142)):*
> ```cpp
> 
> /*! \class result
> 	\brief class used to store a result, based on std::result from Rust programming
> ```

Please re-write a little, e.g.
`Stores result of a ... . It's based on std::result ...`
___
*[src/libpmemkv.hpp, line 145 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7gwVE3WS8k3awudn:-MNTAeBU2-Bvg96Fgfnt:brmav7e) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L145)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you could move those comments above the appropraite methods instead of having it for the entire class.
</blockquote></details>

I say, we can have both
___
*[src/libpmemkv.hpp, line 229 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBXOBDNu7-xAPPUSu:-MNTBXOBDNu7-xAPPUSv:b-c4lmi7) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L229)):*
> ```cpp
> 
> /**
>  * Returns value from result.
> ```

from **the** result.
___
*[src/libpmemkv.hpp, line 235 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBguW9hwlYKvw63Xh:-MNTBguW9hwlYKvw63Xi:b-wm274j) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L235)):*
> ```cpp
>  * @throw bad_result_access
>  *
>  * @return OkType (type of value)
> ```

it returns value, right? not the type of value
___
*[src/libpmemkv.hpp, line 253 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBktMB-p6P0xeULua:-MNTBktMB-p6P0xeULub:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L253)):*
> ```cpp
>  * @throw bad_result_access
>  *
>  * @return ErrType (type of error)
> ```

.
___
*[tests/result/result.cpp, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTCtmU5D_g9DbZOvMl:-MNTCtmU5D_g9DbZOvMm:b7h6wvz) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L3)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

pls add short test description
___
*[tests/result/result.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTFXC39E2dHwp5ypbW:-MNTFXC39E2dHwp5ypbX:boi8a2q) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L16)):*
> ```cpp
> 	const std::string str = "abcdefgh";
> 
> 	result res1(slice(&str[0], &str[str.size()]));
> ```

pls add a short comment that you test return with value
___
*[tests/result/result.cpp, line 29 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTFaCtAt_KwIzYY9Aj:-MNTFaCtAt_KwIzYY9Ak:b-uxa1uc) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L29)):*
> ```cpp
> 	UT_ASSERT(exception_thrown);
> 
> 	result res2(pmem::kv::status::NOT_FOUND);
> ```

and comment here, for "result with err"


<!-- Sent from Reviewable.io -->

2020-12-02 08:04 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 142 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7RMw7CUvI8eSk7iB:-MNXLPqj3la0B9dxAQNO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L142)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please re-write a little, e.g.
`Stores result of a ... . It's based on std::result ...`
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 145 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7gwVE3WS8k3awudn:-MNXLVnQ2NgodlGD0T9N:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I say, we can have both
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 163 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT882wAuL3q2-PQ1W9:-MNXM8RM72xZBdkntl3W:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L163)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

if you define copy ctor you should also define copy assignment 
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 229 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBXOBDNu7-xAPPUSu:-MNXMBEuD_y2QApI1FhL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L229)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

from **the** result.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 235 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBguW9hwlYKvw63Xh:-MNXMjdM16oEJC7UuipU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L235)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it returns value, right? not the type of value
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 253 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTBktMB-p6P0xeULua:-MNXMkVgESEQVeThTEvt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L253)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTCtmU5D_g9DbZOvMl:-MNXQ_ZT0xeDUVEHG4t4:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add short test description
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTFXC39E2dHwp5ypbW:-MNXR06u1jOvMuDDUCRb:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short comment that you test return with value
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 29 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNTFaCtAt_KwIzYY9Aj:-MNXR0Oy9aXauooxygbD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/tests/result/result.cpp#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and comment here, for "result with err"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-02 08:24 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 164 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXXuIA6EqKQg8q2Mlq:-MNXXuIA6EqKQg8q2Mlr:b1yid0p) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L164)):*
> ```cpp
> 	result(const ErrType &err);
> 	result(const result &other);
> ```

I think you should have an explicit destructor and manually destroy the active member: https://www.stroustrup.com/C++11FAQ.html#unions
___
*[src/libpmemkv.hpp, line 203 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXXmdh55qN6BUPPJKL:-MNXXmdh55qN6BUPPJKM:bgkomdp) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L203)):*
> ```cpp
> {
> 	if (has_value)
> 		this->value = other.value;
> ```

I think you should use emplace new() here instead of assignment (the member union has not yet been initialized).
___
*[src/libpmemkv.hpp, line 216 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXUuQH61rQvekg5w4h:-MNXUuQH61rQvekg5w4i:b-sqcjsa) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L216)):*
> ```cpp
> result<OkType, ErrType> &result<OkType, ErrType>::operator=(const result &other)
> {
> 	this->has_value = other.value;
> ```

other.has_value?
___
*[src/libpmemkv.hpp, line 219 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXV5yQ4EnnoGvImXH0:-MNXV5yQ4EnnoGvImXH1:b5lq93o) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L219)):*
> ```cpp
> 
> 	if (has_value)
> 		this->value = other.value;
> ```

I think that, in general, you should first destroy the object which is stored in this.

```
if (has_value) this->value.~OkType();
else ~this->error.~ErrType();
```

and then use ctors instead of copy assignment operators. (you can also optimize this, bu destroying the object only if this->has_value != other.has_value).

See: https://www.stroustrup.com/C++11FAQ.html#unions
___
*[tests/result/result.cpp, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXY58R0cDSXbamIDTW:-MNXY58R0cDSXbamIDTX:b-f7u592) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/tests/result/result.cpp#L13)):*
> ```cpp
> #include "libpmemkv.hpp"
> 
> using slice = pmem::obj::slice<const char *>;
> ```

Please add some test, where slice and result are some complex types (e.g. std::string or unique_ptr). It will verify that the members are created/destroyed properly (you can also use some custom class and verify if ctor/dtor is called appropriate number of times).


<!-- Sent from Reviewable.io -->

2020-12-02 10:30 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXzdVmBUg4rxFVl5sa:-MNXzdVnAoqPCbBOaQlr:b-69fd30) (no related file):*
Hi guys,
What about something like Status from other database?
https://github.com/mongodb/mongo/blob/master/src/mongo/base/status.h
I worked some time with MongoDB with engine development and this solution was easy to use.
Status funcname(args){
 return OK();
}
looks pretty and clear.

---
___
*[src/libpmemkv.hpp, line 142 at r1](https://reviewable.io/reviews/pmem/pmemkv/852#-MNT7RMw7CUvI8eSk7iB:-MNXw73_B4dNSEQJiniF:b-iq7do7) ([raw file](https://github.com/pmem/pmemkv/blob/5489df39d47801c26a564ddc3141a3823fa0332d/src/libpmemkv.hpp#L142)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Additionally:
a operation -> an operation
:) 


<!-- Sent from Reviewable.io -->

2020-12-02 10:55 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXzdVmBUg4rxFVl5sa:-MNY4osg3GfBHwRz2LEJ:b-3cumwa) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Hi guys,
What about something like Status from other database?
https://github.com/mongodb/mongo/blob/master/src/mongo/base/status.h
I worked some time with MongoDB with engine development and this solution was easy to use.
Status funcname(args){
 return OK();
}
looks pretty and clear.
</blockquote></details>

Also:
https://github.com/mongodb/mongo/blob/master/src/mongo/base/status_with.h

---


<!-- Sent from Reviewable.io -->

2020-12-03 09:47 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 164 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXXuIA6EqKQg8q2Mlq:-MNXkrLjClpzhdqsasYH:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L164)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should have an explicit destructor and manually destroy the active member: https://www.stroustrup.com/C++11FAQ.html#unions
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 203 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXXmdh55qN6BUPPJKL:-MNXmUUpEad8E3NFscUz:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L203)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should use emplace new() here instead of assignment (the member union has not yet been initialized).
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 216 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXUuQH61rQvekg5w4h:-MNXmVYz7xaYO65fB-bV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L216)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

other.has_value?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 219 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXV5yQ4EnnoGvImXH0:-MNbzxoR1duRrbC_b_wJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L219)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that, in general, you should first destroy the object which is stored in this.

```
if (has_value) this->value.~OkType();
else ~this->error.~ErrType();
```

and then use ctors instead of copy assignment operators. (you can also optimize this, bu destroying the object only if this->has_value != other.has_value).

See: https://www.stroustrup.com/C++11FAQ.html#unions
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXY58R0cDSXbamIDTW:-MNbzysV210bgU7J3reo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/tests/result/result.cpp#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add some test, where slice and result are some complex types (e.g. std::string or unique_ptr). It will verify that the members are created/destroyed properly (you can also use some custom class and verify if ctor/dtor is called appropriate number of times).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 15:19 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 203 at r2](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXXmdh55qN6BUPPJKL:-MNcy-vR5_IinXtRDoHN:bbksos4) ([raw file](https://github.com/pmem/pmemkv/blob/eecfaaf109eae76598df9d66f9d7db5e458a15ba/src/libpmemkv.hpp#L203)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually what I meant was that we should have two branches. If this->is_ok() then we can do `value = other.value`. Otherwise we have to do `new(&value) OkType(other.value);`

Btw, I think we should also have move ctor/assignemnt - iterator class might not have copy but it will certainly have move ctor.
___
*[src/libpmemkv.hpp, line 171 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNcxjVnEGiMPaIbdTrx:-MNcxjVnEGiMPaIbdTry:bkbqoeg) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L171)):*
> ```cpp
> 	bool is_ok() const;
> 
> 	OkType get_value() const;
> ```

I think you can just return a reference to the value here


<!-- Sent from Reviewable.io -->

2020-12-03 18:16 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 268 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdo5pC-8_otDv-NSUJ:-MNdo5pC-8_otDv-NSUK:bhhoqta) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L268)):*
> ```cpp
> /**
>  * Returns status from the result.
>  *
> ```

you can specify that it's an OK status if there's value, and other status (with the appropriate 'error') if there isn't a value
___
*[tests/result/result.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdiAwlA-y0Nrih0GIA:-MNdiAwlA-y0Nrih0GIB:b-wr548u) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L5)):*
> ```cpp
> 
> /*
>  * result.cpp -- test if result returns values/statuses properly.
> ```

I'd say it's more general, than just checks for returning value/status... perhaps just write it tests **result class**, its members and related exception
___
*[tests/result/result.cpp, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdmgwC1EvMKMG4T6gs:-MNdmgwC1EvMKMG4T6gt:b-baaseg) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L17)):*
> ```cpp
> using result = pmem::kv::result<T>;
> 
> static void result_basic_test()
> ```

you can drop "result" in the name of this test/method
___
*[tests/result/result.cpp, line 29 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdiWH82Xn5QeC9ct0Q:-MNdiWH95c6xAurqpqI9:b-nr5f18) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L29)):*
> ```cpp
> 
> 	/* result without value */
> 	for (int i = 1; i < 13; ++i) {
> ```

magic number - at least make it a const on top of the file;
what if we add new status - can we somehow, automagically make this number non-const...?
___
*[tests/result/result.cpp, line 33 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdmwKz0D6f1-3wKBb1:-MNdmwKz0D6f1-3wKBb2:bbl2n7b) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L33)):*
> ```cpp
> 		UT_ASSERT(!res2.is_ok());
> 		UT_ASSERTeq(res2.get_status(), static_cast<pmem::kv::status>(i));
> 		UT_ASSERT(res2 == static_cast<pmem::kv::status>(i));
> ```

I believe you can cover all versions of `==` and `!=` operators
___
*[tests/result/result.cpp, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdnC6872K4CEq-oKaz:-MNdnC6872K4CEq-oKb-:b-2d0z4k) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L84)):*
> ```cpp
> 	destructor_test();
> }
> ```

are all ctors covered by tests?


<!-- Sent from Reviewable.io -->

2020-12-04 12:36 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 16 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 136 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhkCQe65mESSq7G15I:-MNhkCQe65mESSq7G15J:bcu93wg) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L136)):*
> ```cpp
> class bad_result_access : public std::exception {
> public:
> 	const char *what() const noexcept final
> ```

you could also test this function
___
*[src/libpmemkv.hpp, line 181 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhkBBKA7AGYADX_972:-MNhkBBKA7AGYADX_973:b9qje9z) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L181)):*
> ```cpp
>  */
> template <typename OkType>
> result<OkType>::result(const OkType &val) : value(val), s(status::OK)
> ```

this can be noexcept( noexcept(OkType(std::declval<OkType>()))
___
*[src/libpmemkv.hpp, line 191 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhk4tY3VODMrxDsQTg:-MNhk4tY3VODMrxDsQTh:bmti8ei) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L191)):*
> ```cpp
>  */
> template <typename OkType>
> result<OkType>::result(const status &status) : s(status)
> ```

this can be noexcept
___
*[src/libpmemkv.hpp, line 202 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhk2OlB5H0YiyaaTXu:-MNhk2OlB5H0YiyaaTXv:b9qje9z) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L202)):*
> ```cpp
>  */
> template <typename OkType>
> result<OkType>::result(const result &other) : s(other.s)
> ```

this can be noexcept( noexcept(OkType(std::declval<OkType>()))
___
*[src/libpmemkv.hpp, line 224 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhj_EU8Ib1-3MspOQf:-MNhj_EU8Ib1-3MspOQg:b-o9z0nr) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L224)):*
> ```cpp
>  */
> template <typename OkType>
> result<OkType> &result<OkType>::operator=(const result &other)
> ```

this can be noexcept(noexcept(~OkType()) && noexcept(OkType(std::declval<OkType>()))
___
*[src/libpmemkv.hpp, line 243 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhjUw1APssLiOh4EmU:-MNhjUw1APssLiOh4EmV:bmti8ei) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L243)):*
> ```cpp
>  */
> template <typename OkType>
> bool result<OkType>::is_ok() const
> ```

this can be noexcept


<!-- Sent from Reviewable.io -->

2020-12-07 09:50 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/852#-MNXzdVmBUg4rxFVl5sa:-MNw8P5O76HggcNbN8nB:b-896fix) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Also:
https://github.com/mongodb/mongo/blob/master/src/mongo/base/status_with.h
</blockquote></details>

Done.

---
___
*[src/libpmemkv.hpp, line 136 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhkCQe65mESSq7G15I:-MNw9J7PCp8oRkY5YeF_:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L136)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you could also test this function
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 171 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNcxjVnEGiMPaIbdTrx:-MNw3Aiq1y7t2AjDDrLk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L171)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you can just return a reference to the value here
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 181 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhkBBKA7AGYADX_972:-MNw9r0_958wuSl4lLJz:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L181)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can be noexcept( noexcept(OkType(std::declval<OkType>()))
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 191 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhk4tY3VODMrxDsQTg:-MNw9VkRDOTAReAVhG2z:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L191)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can be noexcept
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 202 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhk2OlB5H0YiyaaTXu:-MNw9mHwEdGM6zahu9a5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L202)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can be noexcept( noexcept(OkType(std::declval<OkType>()))
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 224 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhj_EU8Ib1-3MspOQf:-MNwArKAA2k43z7OsWFD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L224)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can be noexcept(noexcept(~OkType()) && noexcept(OkType(std::declval<OkType>()))
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 243 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNhjUw1APssLiOh4EmU:-MNw4um_E0reClq_KQ9I:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L243)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this can be noexcept
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 268 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdo5pC-8_otDv-NSUJ:-MNw4tz_4-km0puEqYjU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L268)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can specify that it's an OK status if there's value, and other status (with the appropriate 'error') if there isn't a value
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdiAwlA-y0Nrih0GIA:-MNw55F-4cicA4w3hGyx:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd say it's more general, than just checks for returning value/status... perhaps just write it tests **result class**, its members and related exception
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdmgwC1EvMKMG4T6gs:-MNw58nk2kPcUAPqP8E3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can drop "result" in the name of this test/method
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 29 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdiWH82Xn5QeC9ct0Q:-MNw6kNKC3_8b48_kMFI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

magic number - at least make it a const on top of the file;
what if we add new status - can we somehow, automagically make this number non-const...?
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 33 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdmwKz0D6f1-3wKBb1:-MNw7K-9AeByVnKBg8TV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can cover all versions of `==` and `!=` operators
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdnC6872K4CEq-oKaz:-MNw8Nq03kDDJ73NQs0S:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are all ctors covered by tests?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-07 13:00 UTC, lukaszstolarczuk requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[src/libpmemkv.hpp, line 268 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdo5pC-8_otDv-NSUJ:-MNx6z942w_NL3fYvMjE:b-zafgbp) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/src/libpmemkv.hpp#L268)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

pls, make it either `if there's no value.` or `if there isn't any value.`
___
*[src/libpmemkv.hpp, line 138 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxE_Gr-FbGHHgP-3G7:-MNxE_Gr-FbGHHgP-3G8:b-udcd26) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/src/libpmemkv.hpp#L138)):*
> ```cpp
> 	const char *what() const noexcept final
> 	{
> 		return "bad_result_access (value doesn't exists)";
> ```

`doesn't exist`
___
*[tests/result/result.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv/852#-MNdiAwlA-y0Nrih0GIA:-MNx7ChLAC_8cJFsgxmQ:b2nid0f) ([raw file](https://github.com/pmem/pmemkv/blob/e2236a7b8a79445071c37567129b7df879434835/tests/result/result.cpp#L5)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[tests/result/result.cpp, line 89 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxEc_t4zNBu9PdSQ3a:-MNxEc_uCpENYTm7GUsf:b-udcd26) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L89)):*
> ```cpp
> 		} catch (pmem::kv::bad_result_access &e) {
> 			UT_ASSERTeq(std::string(e.what()).compare(
> 					    "bad_result_access (value doesn't exists)"),
> ```

`doesn't exist`
___
*[tests/result/result.cpp, line 209 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxGfR99Os8ChsBBh_K:-MNxGfR99Os8ChsBBh_L:b-jrzdz8) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L209)):*
> ```cpp
> 		UT_ASSERTeq(cd_counter::move_cnt, 1);
> 
> 		result<cd_counter> r6(pmem::kv::status::NOT_FOUND);
> ```

didn't you plan to use `r6`?
___
*[tests/result/result.cpp, line 223 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxH6gb1hnNbgKhA6LA:-MNxH6gb1hnNbgKhA6LB:bxki3c3) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L223)):*
> ```cpp
> 		UT_ASSERTeq(cd_counter::move_cnt, 2);
> 	}
> 	/* check if values in r5 and r6 were destroyed */
> ```

r6 seems to have no value


<!-- Sent from Reviewable.io -->

2020-12-08 07:33 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 15 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 138 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxE_Gr-FbGHHgP-3G7:-MO0E7IF2TsVU7zAJZ05:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/src/libpmemkv.hpp#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`doesn't exist`
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 89 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxEc_t4zNBu9PdSQ3a:-MO0F1d90CAsve4X4ops:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`doesn't exist`
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 209 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxGfR99Os8ChsBBh_K:-MO0F-qOE0nVCmphvNPo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L209)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

didn't you plan to use `r6`?
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 223 at r4](https://reviewable.io/reviews/pmem/pmemkv/852#-MNxH6gb1hnNbgKhA6LA:-MO0F2NW7uXDnyarSoZw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3b50915de0f1f829f3baf5eb3b3873a9966c45d2/tests/result/result.cpp#L223)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

r6 seems to have no value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-08 10:41 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852#-:-MO0wGsb01ORJ8ZS0Lb2:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-08 10:53 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[src/libpmemkv.hpp, line 177 at r5](https://reviewable.io/reviews/pmem/pmemkv/852#-MO0ymszAoLoP02SZjAv:-MO0ymszAoLoP02SZjAw:b8jbfy2) ([raw file](https://github.com/pmem/pmemkv/blob/26b1b8eb42ea5b8709798f4137e9f10954243a53/src/libpmemkv.hpp#L177)):*
> ```cpp
> 	bool is_ok() const noexcept;
> 
> 	OkType &get_value();
> ```

Could you also add const version of this func? `const OkType& get_value() const;`


<!-- Sent from Reviewable.io -->

2020-12-08 12:43 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-12-08 15:33 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[src/libpmemkv.hpp, line 178 at r6](https://reviewable.io/reviews/pmem/pmemkv/852#-MO1yz73-qhMTZbhZj2c:-MO1yz73-qhMTZbhZj2d:b-d04eut) ([raw file](https://github.com/pmem/pmemkv/blob/1c2d34cb039ab2164e0e6202af34affdd1b826c2/src/libpmemkv.hpp#L178)):*
> ```cpp
> 	bool is_ok() const noexcept;
> 
> 	const OkType &get_value() const;
> ```

do we have test for this method?


<!-- Sent from Reviewable.io -->

2020-12-09 08:25 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 178 at r6](https://reviewable.io/reviews/pmem/pmemkv/852#-MO1yz73-qhMTZbhZj2c:-MO5akeGEd841UR4NUAO:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/1c2d34cb039ab2164e0e6202af34affdd1b826c2/src/libpmemkv.hpp#L178)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we have test for this method?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-09 09:11 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852#-:-MO5lCO33FOVcA6Mmtg6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-09 11:08 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852#-:-MO6A-cx4IhHmI3VrIkH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-09 12:56 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99)

___
*[src/libpmemkv.hpp, line 134 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6D8s70QluFg_zr8H2:-MO6D8s83wImqECfwxXO:b-9jt849) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L134)):*
> ```cpp
>    result doesn't contain value.
>  */
> class bad_result_access : public std::exception {
> ```

I'd prefer to use runtime_exception for that kind of problem, also we can pass message there: https://en.cppreference.com/w/cpp/error/exception 
One class less
___
*[src/libpmemkv.hpp, line 138 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6BXAYAVd1yJPj7NEB:-MO6BXAYAVd1yJPj7NEC:bc9dpp9) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L138)):*
> ```cpp
> 	const char *what() const noexcept final
> 	{
> 		return "bad_result_access (value doesn't exist)";
> ```

"bad_result_access: value doesn't exist"
___
*[src/libpmemkv.hpp, line 150 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6EkcF9cF1XCZQSlap:-MO6EkcF9cF1XCZQSlaq:b-4szr03) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L150)):*
> ```
> 	If result contains error: is_ok() returns false, get_value() throws
>    bad_result_access, get_status() returns status other than status::OK.
> ```
Methods should have own documentation, here is place for generic class description 
___
*[src/libpmemkv.hpp, line 152 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6JDH8BLihQ74suij9:-MO6JDH8BLihQ74suijA:b3zy9mf) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L152)):*
> ```cpp
>    bad_result_access, get_status() returns status other than status::OK.
>  */
> template <typename OkType>
> ```

Maybe should we change "OkType" to just "T".
OkType looks like a class name, but it is not. 
___
*[src/libpmemkv.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6UIxxDdZp8FZTwFEg:-MO6UIxy44WwfeHgmC_5:b-v78dll) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L153)):*
> ```cpp
>  */
> template <typename OkType>
> class result {
> ```

I'd prefer fabric class instead of construction on my own. E.g. Status class from MongoDB, is very easy to use.
___
*[src/libpmemkv.hpp, line 154 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6J01n57KyNSqRah7A:-MO6J01n57KyNSqRah7B:bqee2c9) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L154)):*
> ```cpp
> template <typename OkType>
> class result {
> 	union {
> ```

Union for one element is the same as having just a class field: OkType value
___
*[src/libpmemkv.hpp, line 161 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6KxN42pC4XbLRoE4k:-MO6KxN42pC4XbLRoE4l:bfo6f8o) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L161)):*
> ```cpp
> 
> public:
> 	result(const OkType &val) noexcept(noexcept(OkType(std::declval<OkType>())));
> ```

Fancy nested noexcept, I don't like it.
noexcept() is operator, not specifier and, I believe, here has no effect.
___
*[src/libpmemkv.hpp, line 191 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6ZWbP1wcOI1SECWOC:-MO6ZWbP1wcOI1SECWOD:b-8tw5lp) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L191)):*
> ```cpp
> result<OkType>::result(const OkType &val) noexcept(
> 	noexcept(OkType(std::declval<OkType>())))
>     : value(val), s(status::OK)
> ```

Fabric. OkType still is enigmatic
___
*[src/libpmemkv.hpp, line 246 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6WhbS1iztCSy1stSP:-MO6WhbT6b6EAKi-_16u:b-e715y3) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L246)):*
> ```cpp
> 
> /**
>  * Default copy assignment operator.
> ```

Default was before you've implemented this operator
___
*[src/libpmemkv.hpp, line 257 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6X2QCEejUl_91g70O:-MO6X2QCEejUl_91g70P:bv4rm1d) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L257)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	if (s == status::OK && other.is_ok())
> 		value = other.value;
> 	else if (other.is_ok())
> 		new (&value) OkType(other.value);
> 	else if (s == status::OK)
> 		value.~OkType();
> ```
</details>

Hardcore logic in simple, I believe it should be, assignment.
I suppose that our responsibility here is to just free value variable, only if it is class, but it can be also trivial type, right? I didn't saw any enable_if or something like this macros.
OkType should be considered here as object which can be "destructible"
https://en.cppreference.com/w/cpp/types/is_destructible
___
*[src/libpmemkv.hpp, line 258 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6XSsOCF80NQcsJYQU:-MO6X-1x0dDDOqt4NC0O:b-8m8iyy) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L258)):*
> ```
> 	new (&value) OkType(other.value);
> ```
What it does? It looks like memory leak.
___
*[src/libpmemkv.hpp, line 268 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6YSp_6a4VCZCufD1m:-MO6YSp_6a4VCZCufD1n:b-wsq53l) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L268)):*
> ```cpp
> 
> /**
>  * Default move assignment operator.
> ```

Not default
___
*[src/libpmemkv.hpp, line 345 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6YchL5NTSEi0Lx6n7:-MO6YchL5NTSEi0Lx6n8:bbouhth) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L345)):*
> ```cpp
> 		return value;
> 	else
> 		throw bad_result_access();
> ```

Okey, I'd prefer to use this one time runtime_error.


<!-- Sent from Reviewable.io -->

2020-12-09 14:33 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[src/libpmemkv.hpp, line 134 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6D8s70QluFg_zr8H2:-MO6qQBW8_Tv_rsiQrMW:br2cmm8) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L134)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'd prefer to use runtime_exception for that kind of problem, also we can pass message there: https://en.cppreference.com/w/cpp/error/exception 
One class less
</blockquote></details>

We can inherit from std::runtime_exception instead of exception but we should have seperate class anyway - to be able to catch specifi errors.
___
*[src/libpmemkv.hpp, line 152 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6JDH8BLihQ74suij9:-MO6qt-HEGM_QT3k8141:bp0dyqb) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L152)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Maybe should we change "OkType" to just "T".
OkType looks like a class name, but it is not. 
</blockquote></details>

It is a type name, using camel case for template params is quite common, but yeah since we no longer have ErrType I guess this could be T as well.
___
*[src/libpmemkv.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6UIxxDdZp8FZTwFEg:-MO6reLg8t9AGCwj2SH2:b-metq55) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L153)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'd prefer fabric class instead of construction on my own. E.g. Status class from MongoDB, is very easy to use.
</blockquote></details>

You mean factory? I guess we can have both. Ctors and the factory method which would just be a syntactic sugar. (We can do that in a separate PR I believe). But from what I see StatusWith does not have anything like this (only Status), do you know why?
___
*[src/libpmemkv.hpp, line 154 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6J01n57KyNSqRah7A:-MO6r5ngE8RGno5DplU-:b-zbxf2x) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L154)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Union for one element is the same as having just a class field: OkType value
</blockquote></details>

No, it's not - with union the value is not constructed by default - you have to do it manually (that's what we want).
___
*[src/libpmemkv.hpp, line 161 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6KxN42pC4XbLRoE4k:-MO6rHdWEfcJ70_k5L16:b-fi69n9) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L161)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Fancy nested noexcept, I don't like it.
noexcept() is operator, not specifier and, I believe, here has no effect.
</blockquote></details>

It is both a specifier and an operator - this syntax is to mark the function as noexcept if and only if OkType copy ctor is noexcept. I agree it;s quite verbose but we designed our C++ API to not thrown exceptions - here it's not so easy since this can be paremetrized with any type - but we should have the function marked as noexcept if only we can.
___
*[src/libpmemkv.hpp, line 191 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6ZWbP1wcOI1SECWOC:-MO6uIDpDl6EkcwGpMWR:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L191)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Fabric. OkType still is enigmatic
</blockquote></details>

.
___
*[src/libpmemkv.hpp, line 246 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6WhbS1iztCSy1stSP:-MO6rs0u802NigQUKJDd:b-jmo26i) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L246)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Default was before you've implemented this operator
</blockquote></details>

In C++ language default ctor is the one which does not accept any args (no matter if it's implicitly defaulted or not ;d) : https://en.cppreference.com/w/cpp/language/default_constructor
___
*[src/libpmemkv.hpp, line 257 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6X2QCEejUl_91g70O:-MO6s1r8BllAl1sPf9Gy:b-leo9qb) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L257)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	if (s == status::OK && other.is_ok())
> 		value = other.value;
> 	else if (other.is_ok())
> 		new (&value) OkType(other.value);
> 	else if (s == status::OK)
> 		value.~OkType();
> ```
Hardcore logic in simple, I believe it should be, assignment.
I suppose that our responsibility here is to just free value variable, only if it is class, but it can be also trivial type, right? I didn't saw any enable_if or something like this macros.
OkType should be considered here as object which can be "destructible"
https://en.cppreference.com/w/cpp/types/is_destructible
</blockquote></details>

It's not necessary to use enable_if, you can safely call ctor of trivial types - it will just do nothing. (it only works in templates, you can't just write a.~int()).

As for complexity, that's the 'beauty' of c++ ;d You can see how std::optional is implemented, it's basically the same: https://github.com/llvm-mirror/libcxx/blob/master/include/optional#L337
___
*[src/libpmemkv.hpp, line 258 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6XSsOCF80NQcsJYQU:-MO6sVyV8zOR4VoqKX3K:b62q059) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L258)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	new (&value) OkType(other.value);
> ```
What it does? It looks like memory leak.
</blockquote></details>

It's placement new - https://en.cppreference.com/w/cpp/language/new
___
*[src/libpmemkv.hpp, line 268 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6YSp_6a4VCZCufD1m:-MO6skyD2N66yt0ptLyo:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L268)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Not default
</blockquote></details>

.
___
*[src/libpmemkv.hpp, line 345 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6YchL5NTSEi0Lx6n7:-MO6snAv0R-2Jv0BRmqn:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L345)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Okey, I'd prefer to use this one time runtime_error.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2020-12-09 14:35 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[src/libpmemkv.hpp, line 257 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6X2QCEejUl_91g70O:-MO6vK6DEGHcInLaUJCd:b-i43aab) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L257)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's not necessary to use enable_if, you can safely call ctor of trivial types - it will just do nothing. (it only works in templates, you can't just write a.~int()).

As for complexity, that's the 'beauty' of c++ ;d You can see how std::optional is implemented, it's basically the same: https://github.com/llvm-mirror/libcxx/blob/master/include/optional#L337
</blockquote></details>

Btw, I think we could have some test with trivial types in result to make sure, that calling those dtors is indeed OK and it compiles.


<!-- Sent from Reviewable.io -->

2020-12-09 14:57 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[src/libpmemkv.hpp, line 150 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6EkcF9cF1XCZQSlap:-MO6zV_E6cQhBkWtP-IP:b-hiyjuk) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L150)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	If result contains error: is_ok() returns false, get_value() throws
>    bad_result_access, get_status() returns status other than status::OK.
> ```
Methods should have own documentation, here is place for generic class description 
</blockquote></details>

I guess it's a good overview how this class works, showing the most commonly used methods and how they behave (in the two allowed usages), I guess - I'd leave it as is.

Hmm.. or maybe we should have an example instead...? (and put a snippet here)


<!-- Sent from Reviewable.io -->

2020-12-09 15:20 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[src/libpmemkv.hpp, line 134 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6D8s70QluFg_zr8H2:-MO6ySm04p3dejQfPN2R:br3rrfq) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L134)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We can inherit from std::runtime_exception instead of exception but we should have seperate class anyway - to be able to catch specifi errors.
</blockquote></details>

Okey, but here we use class type as error message.
I'd prefer add: bad_result_access(const char* what_arg);
and don't store hardcoded values. I believe that context of this exception can vary in the future and then there will be reimplementation.
XOR
With pmemkv 2.0 we will reimplement most of API etc then this change is okey for me.
___
*[src/libpmemkv.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6UIxxDdZp8FZTwFEg:-MO7-_Qg8zXU_Rx6zpaP:bp0xe9k) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L153)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You mean factory? I guess we can have both. Ctors and the factory method which would just be a syntactic sugar. (We can do that in a separate PR I believe). But from what I see StatusWith does not have anything like this (only Status), do you know why?
</blockquote></details>

Factory, my fault. Indeed, StatusWith does not have that kind API.
return Status::OK(); // looks good and clear
___
*[src/libpmemkv.hpp, line 257 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6X2QCEejUl_91g70O:-MO74GiKA1UlQKdBS0uw:b16ytmp) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L257)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Btw, I think we could have some test with trivial types in result to make sure, that calling those dtors is indeed OK and it compiles.
</blockquote></details>

./\/\
(o.O)
Okeeeey.
___
*[src/libpmemkv.hpp, line 258 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6XSsOCF80NQcsJYQU:-MO73yFK3Qf1IfuYUdlD:b7wslfl) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L258)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's placement new - https://en.cppreference.com/w/cpp/language/new
</blockquote></details>

God, kill me.
Done.


<!-- Sent from Reviewable.io -->

2020-12-10 07:50 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/libpmemkv.hpp, line 134 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6D8s70QluFg_zr8H2:-MOAYCxJ64ufUcEZPI5h:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L134)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Okey, but here we use class type as error message.
I'd prefer add: bad_result_access(const char* what_arg);
and don't store hardcoded values. I believe that context of this exception can vary in the future and then there will be reimplementation.
XOR
With pmemkv 2.0 we will reimplement most of API etc then this change is okey for me.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 138 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6BXAYAVd1yJPj7NEB:-MOAYg7y795-qvHsoLJS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L138)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

"bad_result_access: value doesn't exist"
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 152 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6JDH8BLihQ74suij9:-MOAZMY06jWOLZnayqdy:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L152)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It is a type name, using camel case for template params is quite common, but yeah since we no longer have ErrType I guess this could be T as well.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 257 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6X2QCEejUl_91g70O:-MOAbJZT0WbAMgB1dn0s:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L257)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

./\/\
(o.O)
Okeeeey.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 258 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6XSsOCF80NQcsJYQU:-MOAZXD8EQEwGKTrCLVn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L258)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

God, kill me.
Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-10 09:09 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[src/libpmemkv.hpp, line 329 at r8](https://reviewable.io/reviews/pmem/pmemkv/852#-MOAtdScEJ9iWi92Vn9u:-MOAtdScEJ9iWi92Vn9v:bix2hw3) ([raw file](https://github.com/pmem/pmemkv/blob/ebc4f54c07a7824d32ffd6cf6035e9caaef64be1/src/libpmemkv.hpp#L329)):*
> ```cpp
> 		return value;
> 	else
> 		throw bad_result_access("bad_result_access: value doesn't exist");
> ```

do we still need to write first part - `bad_result_access: ` ?


<!-- Sent from Reviewable.io -->

2020-12-10 09:11 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 329 at r8](https://reviewable.io/reviews/pmem/pmemkv/852#-MOAtdScEJ9iWi92Vn9u:-MOAuky80Pw5aPBO41Fl:byq9u75) ([raw file](https://github.com/pmem/pmemkv/blob/ebc4f54c07a7824d32ffd6cf6035e9caaef64be1/src/libpmemkv.hpp#L329)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we still need to write first part - `bad_result_access: ` ?
</blockquote></details>

It's similar to: https://en.cppreference.com/w/cpp/utility/optional/value


<!-- Sent from Reviewable.io -->

2020-12-10 09:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[tests/result/result.cpp, line 74 at r8](https://reviewable.io/reviews/pmem/pmemkv/852#-MOAxft3CXd5lrRRIBCL:-MOAxft3CXd5lrRRIBCM:b-y052a1) ([raw file](https://github.com/pmem/pmemkv/blob/ebc4f54c07a7824d32ffd6cf6035e9caaef64be1/tests/result/result.cpp#L74)):*
> ```cpp
> 	UT_ASSERTeq(str.compare(res1.get_value().begin()), 0);
> 
> 	/* test const get_value() */
> ```

check also const version with no value (especially check for thrown exception)


<!-- Sent from Reviewable.io -->

2020-12-10 09:38 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 150 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6EkcF9cF1XCZQSlap:-MOB-w2D82NPWKAlBJSZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L150)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess it's a good overview how this class works, showing the most commonly used methods and how they behave (in the two allowed usages), I guess - I'd leave it as is.

Hmm.. or maybe we should have an example instead...? (and put a snippet here)
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/pmemkv/852#-MO6UIxxDdZp8FZTwFEg:-MOB-wik1egoX4kCv-a1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/bf6dafe42bdd0ee73007584a83a98fc4c0b288ea/src/libpmemkv.hpp#L153)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Factory, my fault. Indeed, StatusWith does not have that kind API.
return Status::OK(); // looks good and clear

</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 329 at r8](https://reviewable.io/reviews/pmem/pmemkv/852#-MOAtdScEJ9iWi92Vn9u:-MOB-xCt7nzlaryrcjVW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ebc4f54c07a7824d32ffd6cf6035e9caaef64be1/src/libpmemkv.hpp#L329)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's similar to: https://en.cppreference.com/w/cpp/utility/optional/value
</blockquote></details>

Done.
___
*[tests/result/result.cpp, line 74 at r8](https://reviewable.io/reviews/pmem/pmemkv/852#-MOAxft3CXd5lrRRIBCL:-MOB-xql9i-jC5aupbm1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ebc4f54c07a7824d32ffd6cf6035e9caaef64be1/tests/result/result.cpp#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

check also const version with no value (especially check for thrown exception)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-10 09:43 UTC, lukaszstolarczuk approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/852)* status: all files reviewed, 7 unresolved discussions (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-10 10:33 UTC, merged