robinhood engine preview
pmem/pmemkv pull request #881
Opened 2021-01-11 10:56 UTC by JanDorniak99

2021-01-11 13:45 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines-experimental/robinhood.h, line 157 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQlfgCs1wKt8AuM8xqo:-MQlfgCs1wKt8AuM8xqp:b-tzxzl2) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L157)):*
> ```objc
> 	std::vector<mutex_type> mtxs;
> 
> 	mutex_type global_mtx;
> ```

what is this mutex for?
___
*[src/engines-experimental/robinhood.cc, line 635 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQlfxw7-_3IIK8h1i99:-MQlfxw7-_3IIK8h1i9A:b99p02f) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L635)):*
> ```cpp
> }
> 
> status robinhood::put(string_view key, string_view value)
> ```

I'm not sure if we should always require exactly 8 bytes keys - we should discuss that. For now, please at least add some check for the key/value length and if it's not 8 bytes return invalid_argument.


<!-- Sent from Reviewable.io -->

2021-01-12 15:28 UTC, igchor reviewed
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engine.cc, line 146 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQrC4eMAphOGsuia503:-MQrC4eMAphOGsuia504:b3kre) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engine.cc#L146)):*
> ```cpp
> #endif
> 
> 	//#ifdef ENGINE_ROBINHOOD
> ```

?
___
*[src/engines-experimental/robinhood.cc, line 604 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQrCIVjAch9FMW5G9L7:-MQrCIVjAch9FMW5G9L8:bd7th36) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L604)):*
> ```cpp
> 	check_outside_tx();
> 
> 	auto shard = hash(key);
> ```

Is this the same hash function as the one used by the hashmap itself? I'm not sure if it;s the best idea, it can lead to increased collisions within the shard.


<!-- Sent from Reviewable.io -->

2021-01-13 10:11 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines-experimental/robinhood.h, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDNSB8-ug3a40pzzf:-MQvDNSB8-ug3a40pzzg:bpz43wl) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L59)):*
> ```objc
> 
> #ifdef DEBUG
> #define HM_ASSERT(cnd) assert(cnd)
> ```

I think it's not necessary, we just use assert everywhere expliciltly.
___
*[src/engines-experimental/robinhood.h, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDTq_-LwmgmaPAHCU:-MQvDTq_-LwmgmaPAHCV:b-uoopsd) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L85)):*
> ```objc
> 	size_t actv_cnt;
> 
> #ifdef DEBUG
> ```

don't use DEBUG, we don't define this macro, instead use: `#ifndef NDEBUG`. Fix in other places


<!-- Sent from Reviewable.io -->

2021-01-13 10:13 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 352 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDvpn0_WQp7MZeorz:-MQvDvpn0_WQp7MZeos-:bdrc6ro) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L352)):*
> ```cpp
> 
> 	if (TOID_IS_NULL(hashmap_rebuild.entries)) {
> 		fprintf(stderr, "hashmap rebuild failed: %s\n", pmemobj_errormsg());
> ```

Please remove the fprints (all prints). You can replace them with LOG() as in other engines. For now you can define LOG as a nop like everywhere.


<!-- Sent from Reviewable.io -->

2021-01-13 12:09 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engine.cc, line 146 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQrC4eMAphOGsuia503:-MQvdUzs2jY00_uHuIQK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engine.cc#L146)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDNSB8-ug3a40pzzf:-MQvcVIQ5NrpptT6ieku:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it's not necessary, we just use assert everywhere expliciltly.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 157 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQlfgCs1wKt8AuM8xqo:-MQvcnI98D8cLu6heEaD:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L157)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is this mutex for?
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 604 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQrCIVjAch9FMW5G9L7:-MQvcptH24qPbqszGmgP:b-95xnyw) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L604)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this the same hash function as the one used by the hashmap itself? I'm not sure if it;s the best idea, it can lead to increased collisions within the shard.
</blockquote></details>

It's not the same (I've changed name to "shard_hash" now, because the old one was confusing) 
___
*[src/engines-experimental/robinhood.cc, line 635 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQlfxw7-_3IIK8h1i99:-MQvdTeP-IiaEp4wqZpw:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L635)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if we should always require exactly 8 bytes keys - we should discuss that. For now, please at least add some check for the key/value length and if it's not 8 bytes return invalid_argument.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 09:23 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 604 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQrCIVjAch9FMW5G9L7:-MR-9PkG5y2vogcECVkf:bc2is9d) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L604)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

It's not the same (I've changed name to "shard_hash" now, because the old one was confusing) 
</blockquote></details>

OK, I see. I think it could be better to actually use some hashing function in the shard_hash instead of just using the least significant bits of the key. You can take a look at: https://github.com/pmem/vmemcache/blob/41eccb65985165154d50fa9ece9d0679db03ddd9/src/vmemcache_index.c and https://github.com/pmem/vmemcache/blob/5bd6294b2418a079f97916fe75995ce78a211145/src/fast-hash.c We could probably benchmark the code with and without the hashing function inside shard_hash
___
*[src/engines-experimental/robinhood.cc, line 635 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQlfxw7-_3IIK8h1i99:-MR-C89D9TCQo1uOknJ_:b-nlv52u) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L635)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think returning a status would be more in line with our error handling
___
*[src/engines-experimental/robinhood.cc, line 659 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MR-BpP9-H53vLsWLMvs:-MR-BpP9-H53vLsWLMvt:b-ql1e5l) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L659)):*
> ```cpp
> 			pmem::obj::transaction::snapshot(root_oid);
> 
> 			int seed = 0; // ???
> ```

This should probably be changed. You can google for some best practices in C++.


<!-- Sent from Reviewable.io -->

2021-01-18 09:02 UTC, igchor reviewed
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engine.cc, line 8 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJeLa62olKNH_FMAn1:-MRJeLa72aerWisq_a7C:b-nl8163) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engine.cc#L8)):*
> ```cpp
> #include "engines/blackhole.h"
> 
> #include "engines-experimental/robinhood.h"
> ```

I think this line is a duplicate?
___
*[src/engines-experimental/robinhood.cc, line 522 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJfjh33LrpVdzfivLN:-MRJfjh33LrpVdzfivLO:bs2gtph) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L522)):*
> ```cpp
>     : pmemobj_engine_base(cfg, "pmemkv_robinhood"), mtxs(SHARDS)
> {
> 	LOG("Started ok");
> ```

I believe the LOG should be after the recover() completes.
___
*[src/engines-experimental/robinhood.cc, line 572 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJfrO57oJTMbL-lT-1:-MRJfrO66hl7Q0VjInjh:be1pxhz) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L572)):*
> ```cpp
> 	check_outside_tx();
> 
> 	auto k = *((uint64_t *)key.data());
> ```

I think it would be more idiomatic to use reinterpret_casts here (and in other places).
___
*[src/engines-experimental/robinhood.cc, line 623 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJi6ix7SBlgtMP3CZP:-MRJi6ix7SBlgtMP3CZQ:b-ufmm4z) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L623)):*
> ```cpp
> 
> 	if (hm_rp_insert(pmpool.handle(), container[shard], k, v) != 0)
> 		return status::UNKNOWN_ERROR;
> ```

I guess this should be fixed in future. We can extend the C error handling code to pass the actual reason of the failure. Could you create an issue for that?


<!-- Sent from Reviewable.io -->

2021-01-21 12:59 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engine.cc, line 8 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJeLa62olKNH_FMAn1:-MRZy_XYDbAFEd5FccKF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engine.cc#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this line is a duplicate?
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDTq_-LwmgmaPAHCU:-MR_0sE75wKcDUM7aDYP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

don't use DEBUG, we don't define this macro, instead use: `#ifndef NDEBUG`. Fix in other places
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 522 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJfjh33LrpVdzfivLN:-MRZr--HBrNCiohNap-N:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L522)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe the LOG should be after the recover() completes.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 572 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJfrO57oJTMbL-lT-1:-MRZu_fVBIRNJ0ML3OgE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L572)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be more idiomatic to use reinterpret_casts here (and in other places).
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 659 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MR-BpP9-H53vLsWLMvs:-MRZxs4F3lGqxXp_MGGn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L659)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This should probably be changed. You can google for some best practices in C++.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 10:26 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 659 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MR-BpP9-H53vLsWLMvs:-MRdadjcCvThKIU3edid:bn5zu99) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L659)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So, there is no seed now? What I meant was to leave it bu initilize it properly. For C++ there are some known best practices like: https://codereview.stackexchange.com/questions/109260/seed-stdmt19937-from-stdrandom-device

But since we are using C generator here just setting seed to time(NULL) might be OK for now.


<!-- Sent from Reviewable.io -->

2021-01-25 08:24 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 659 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MR-BpP9-H53vLsWLMvs:-MRscMRxBP2j2HwkR8Ya:bo9svid) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L659)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, there is no seed now? What I meant was to leave it bu initilize it properly. For C++ there are some known best practices like: https://codereview.stackexchange.com/questions/109260/seed-stdmt19937-from-stdrandom-device

But since we are using C generator here just setting seed to time(NULL) might be OK for now.
</blockquote></details>

This seed was passed as an argument but unused in hashmap_create. It was probably a mistake in the libpmemobj example.


<!-- Sent from Reviewable.io -->

2021-01-25 09:31 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[src/engines-experimental/robinhood.cc, line 352 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDvpn0_WQp7MZeorz:-MRso8h10i2lNNHny84o:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L352)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please remove the fprints (all prints). You can replace them with LOG() as in other engines. For now you can define LOG as a nop like everywhere.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 623 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MRJi6ix7SBlgtMP3CZP:-MRsqd0wA0D_tlGJxeW3:b-dhmy6r) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L623)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I guess this should be fixed in future. We can extend the C error handling code to pass the actual reason of the failure. Could you create an issue for that?
</blockquote></details>

I will create an issue after merging this PR


<!-- Sent from Reviewable.io -->

2021-01-25 09:52 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 352 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQvDvpn0_WQp7MZeorz:-MRsw-1GCavUvPKr3riE:b-xv6n8l) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.cc#L352)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can leave the LOGs uncommented - just define the LOG macro as in other engines.
___
*[src/engines-experimental/robinhood.cc, line 659 at r2](https://reviewable.io/reviews/pmem/pmemkv/881#-MR-BpP9-H53vLsWLMvs:-MRswbgM4q8jgOFTjYqB:bs5ocwy) ([raw file](https://github.com/pmem/pmemkv/blob/2012c615edaa299b90e7352b7f8c573fd57d3026/src/engines-experimental/robinhood.cc#L659)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

This seed was passed as an argument but unused in hashmap_create. It was probably a mistake in the libpmemobj example.
</blockquote></details>

Ok, you're right.


<!-- Sent from Reviewable.io -->

2021-01-25 15:04 UTC, lukaszstolarczuk requested changes
> Reviewed 5 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 5 of 8 files reviewed, 10 unresolved discussions (waiting on @igchor and @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu0VaK0QqFHrTOyCTv:-MRu0VaK0QqFHrTOyCTw:b-2vthl3) (no related file):*
Please read the Contributing.md file (https://github.com/pmem/pmemkv/blob/master/CONTRIBUTING.md#creating-new-engines)
There's at least docs missing for the new engine.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu33fA5U3lyyjs4e20:-MRu33fA5U3lyyjs4e21:b1fty13) (no related file):*
please update also engines' checks in `run-test-building.sh`

---
___
*[CMakeLists.txt, line 39 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtzVy78IHVbnGEyCZ8:-MRtzVy78IHVbnGEyCZ9:b-3vc96h) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/CMakeLists.txt#L39)):*
> ```CMake
> option(ENGINE_TREE3 "enable experimental tree3 engine" OFF)
> option(ENGINE_RADIX "enable experimental radix engine" OFF)
> option(ENGINE_ROBINHOOD "enable experimental robinhood engine (requires CXX_STANDARD to be set to value >= 14)" OFF)
> ```

hmm actually, what happend with our naming convention - shouldn't it be `crobinhood`? The same applies for `sradix`? ( @igchor ) 
___
*[CMakeLists.txt, line 100 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtz3uR85F7kyFVQ1-1:-MRtz3uR85F7kyFVQ1-2:bwi04rb) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/CMakeLists.txt#L100)):*
> ```CMake
> 	src/iterator.h
> 	src/iterator.cc
> 	src/fast_hash.h
> ```

it's not required for all engines, please put it under if ENGINE_ROBINHOOD
___
*[src/fast_hash.h, line 31 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu0zBb5Lrd4p1CiG2x:-MRu0zBb5Lrd4p1CiG2y:bi2ze11) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L31)):*
> ```objc
> 
> #ifndef FAST_HASH_H
> #define FAST_HASH_H 1
> ```

can't you drop the ` 1` ?
___
*[src/fast_hash.h, line 37 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtzpfnAm6MPwcLcLFC:-MRtzpfo5vCd02wb669q:b-uyg37h) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L37)):*
> ```objc
> uint64_t fast_hash(size_t key_size, const char *key);
> 
> #endif
> ```

pls add a comment `/* FAST_HASH_H */`
___
*[tests/CMakeLists.txt, line 1657 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu222i23PNrtONPKm8:-MRu222i23PNrtONPKm9:b58s8aw) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/tests/CMakeLists.txt#L1657)):*
> ```CMake
> endif(ENGINE_RADIX)
> ################################################################################
> ```

please add here (in this line) and in the bottom of this code block the `####..` line ;)
___
*[utils/docker/run-build.sh, line 3 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu2r-H543qgIW5ge9K:-MRu2r-H543qgIW5ge9L:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/utils/docker/run-build.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2019-2020, Intel Corporation
> ```

-2021


<!-- Sent from Reviewable.io -->

2021-01-26 09:49 UTC, igchor requested changes
> Reviewed 4 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 11 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 39 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtzVy78IHVbnGEyCZ8:-MRxxOsN1U0pO1lahlFT:b-fo1jyg) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/CMakeLists.txt#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm actually, what happend with our naming convention - shouldn't it be `crobinhood`? The same applies for `sradix`? ( @igchor ) 
</blockquote></details>

I'm not sure if we want to keep it for all engines. Let's leave it as it is and we can discuss this if when we decide to productize it.
___
*[src/engines-experimental/robinhood.cc, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxyL0m6z3Bn-p6kj0z:-MRxyL0m6z3Bn-p6kj1-:bwqkr1l) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L20)):*
> ```cpp
> {
> 
> static std::function<std::string(void)> name;
> ```

You can just define the function here, instead of initilizaing this with lambda.
___
*[src/engines-experimental/robinhood.cc, line 660 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxyaxO3-uYDRx_JI9P:-MRxyaxO3-uYDRx_JI9Q:b-hbmrn) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L660)):*
> ```cpp
> 		container = pmem_ptr->map.get();
> 
> 		this->shards_number = pmem_ptr->shards_number;
> ```

This condition means that the database was already created previously. This means that you should not overwrite the shards value but rather read it and compare with the value from env var/the default one. If there's no match you should return an error.
___
*[src/engines-experimental/robinhood.cc, line 685 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxz63W70bH4kwgK-Wk:-MRxz63W70bH4kwgK-Wl:b6m770u) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L685)):*
> ```cpp
> 
> 		for (size_t i = 0; i < shards_number; ++i)
> 			internal::robinhood::hm_rp_create(pmpool.handle(), &container[i]);
> ```

Since this is now outside tx what if there is a failure during this loop execution? On restart we might have only a few shards created.
I think it would be best to just use action API for everything instead of the tx. You would need to do all allocations/assignemnts from this tx using pmemobj_set_value/pmemobj_reserve.

After that we should create all hashmaps as one atomic action. To do that, you need to modify the hm_rp_create function . It should not create an array of actions internally nor should it publish. Instead you can create a big array of actions in the Recover method (4 * shards_number + actions_needed_for_what_is_currently_in_tx) and pass subranges of this array to hm_rp_create. (the first function call gets pointer to the 0th element, the second call to 4th element and so on). Only after all is done, you call a single publish.


<!-- Sent from Reviewable.io -->

2021-01-26 09:50 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 11 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[src/engines-experimental/robinhood.cc, line 685 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxz63W70bH4kwgK-Wk:-MRy5LYL61HGH3kgkb6O:b-h3ba9o) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L685)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Since this is now outside tx what if there is a failure during this loop execution? On restart we might have only a few shards created.
I think it would be best to just use action API for everything instead of the tx. You would need to do all allocations/assignemnts from this tx using pmemobj_set_value/pmemobj_reserve.

After that we should create all hashmaps as one atomic action. To do that, you need to modify the hm_rp_create function . It should not create an array of actions internally nor should it publish. Instead you can create a big array of actions in the Recover method (4 * shards_number + actions_needed_for_what_is_currently_in_tx) and pass subranges of this array to hm_rp_create. (the first function call gets pointer to the 0th element, the second call to 4th element and so on). Only after all is done, you call a single publish.
</blockquote></details>

Btw, it might be a good idea to test the Recovery stage for our engines. Such bug should be catched by our tests


<!-- Sent from Reviewable.io -->

2021-01-28 15:37 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 11 unresolved discussions (waiting on @JanDorniak99)

___
*[src/engines-experimental/robinhood.cc, line 23 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MS8cpM_07GQ5IpkdV26:-MS8cpM_07GQ5IpkdV27:b-q1lsfo) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L23)):*
> ```cpp
> 
> /* Load factor to indicate resize threshold */
> static float load_factor;
> ```

load factor cannot be static variable - it will be the same for all instances of robinhood engine - and we don't want that


<!-- Sent from Reviewable.io -->

2021-02-01 09:41 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 2 of 13 files reviewed, 10 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu33fA5U3lyyjs4e20:-MS1o9q09oxRgxLzePiU:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please update also engines' checks in `run-test-building.sh`
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu0VaK0QqFHrTOyCTv:-MSRsVhE8RzcvsmNVMuu:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please read the Contributing.md file (https://github.com/pmem/pmemkv/blob/master/CONTRIBUTING.md#creating-new-engines)
There's at least docs missing for the new engine.
</blockquote></details>

Done.

---
___
*[CMakeLists.txt, line 100 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtz3uR85F7kyFVQ1-1:-MS1q-pNAOZ1A5HLcDCq:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/CMakeLists.txt#L100)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not required for all engines, please put it under if ENGINE_ROBINHOOD
</blockquote></details>

Done.
___
*[src/fast_hash.h, line 31 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu0zBb5Lrd4p1CiG2x:-MS1q5GT8a4eTDTCg09G:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can't you drop the ` 1` ?
</blockquote></details>

Done.
___
*[src/fast_hash.h, line 37 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRtzpfnAm6MPwcLcLFC:-MS1qAZBAxFKKGH1TbU3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment `/* FAST_HASH_H */`
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxyL0m6z3Bn-p6kj0z:-MS1qvoN-kDfCx8JZNQ5:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can just define the function here, instead of initilizaing this with lambda.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 23 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MS8cpM_07GQ5IpkdV26:-MSRpem09nMc0qWhlAbo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

load factor cannot be static variable - it will be the same for all instances of robinhood engine - and we don't want that
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 660 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRxyaxO3-uYDRx_JI9P:-MS22BpYATeqXqKGM9-f:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/engines-experimental/robinhood.cc#L660)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This condition means that the database was already created previously. This means that you should not overwrite the shards value but rather read it and compare with the value from env var/the default one. If there's no match you should return an error.
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 1657 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu222i23PNrtONPKm8:-MS1sOot-joFPOp76xsB:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/tests/CMakeLists.txt#L1657)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add here (in this line) and in the bottom of this code block the `####..` line ;)
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 3 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MRu2r-H543qgIW5ge9K:-MS1svhB36GHPrciP6OQ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/utils/docker/run-build.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 10:46 UTC, igchor requested changes
> Reviewed 1 of 8 files at r5, 4 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 28 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[src/fast_hash.h, line 27 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXE5pi8DNafiR2r52i:-MSXE5pi8DNafiR2r52j:b-sn3toy) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L27)):*
> ```objc
>  */
> 
> // SPDX-License-Identifier: BSD-3-Clause
> ```

We might also write this file as an exception in: https://github.com/pmem/pmemkv/blob/master/LICENSE
___
*[src/engines-experimental/robinhood.cc, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXIXM0AWfmiFCQWr5F:-MSXIXM0AWfmiFCQWr5G:b-si1ubs) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L101)):*
> ```cpp
>  */
> static void hashmap_create(PMEMobjpool *pop, TOID(struct hashmap_rp) * hashmap_p,
> 			   struct pobj_action *actv)
> ```

Hm, maybe instead of passing pobj_action* you could pass a reference to std::vector<pobj_action> and just call emplace_back() before each pmemobj_action function? It will be much less error-prone.
___
*[src/engines-experimental/robinhood.cc, line 359 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST994x5oV8FoS8NBWW:-MSXJ3h16ckozuOFQhqt:b-yq8lh9) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L359)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Uuuuuu, we should avoid goto in OOP paradigm, especially in library. Examples are smaller and there is less code to deal with.
</blockquote></details>

Sure, we could avoid this if it would be C++ code but it's only C code compiled as C++. I would suggest leaving this as is and fixing it after we decide to rework the implementation in C++. In C, gotos for error handling are fine (when used in consistent manner).
___
*[src/engines-experimental/robinhood.cc, line 386 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXJYS_EgoL4Odjidb6:-MSXJYS_EgoL4Odjidb7:b-t548yj) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L386)):*
> ```cpp
>  */
> int hm_rp_create(PMEMobjpool *pop, TOID(struct hashmap_rp) * map,
> 		 struct pobj_action *actv)
> ```

std vector
___
*[src/engines-experimental/robinhood.cc, line 525 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXJk8R3CbibbFR3G_b:-MSXJk8R3CbibbFR3G_c:begmxro) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L525)):*
> ```cpp
> {
> 	/* for now, shards number can be changed from default by env variable */
> 	auto sn = std::getenv("ENGINE_ROBINHOOD_SHARDS_NUMBER");
> ```

Maybe move this code to Recover() method? It's unspoken rule, but we basically put all the code there - it's more clear what is done on reopen and what on create.
___
*[src/engines-experimental/robinhood.cc, line 527 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXK2Qn5g3woGi641oU:-MSXK2Qn5g3woGi641oV:b-v7np0o) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L527)):*
> ```cpp
> 	auto sn = std::getenv("ENGINE_ROBINHOOD_SHARDS_NUMBER");
> 	if (sn)
> 		sscanf(sn, "%zu", &shards_number);
> ```

I think you can just use std::stoi or something like this
___
*[src/engines-experimental/robinhood.cc, line 529 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXK5msBqFw7iORm8YV:-MSXK5msBqFw7iORm8YW:bm2sh78) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L529)):*
> ```cpp
> 		sscanf(sn, "%zu", &shards_number);
> 	else
> 		shards_number = SHARDS;
> ```

Maybe rename SHARDS to DEFAULT_SHARDS or something?
___
*[src/engines-experimental/robinhood.cc, line 533 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTE3lmE9bBjxo3j36n:-MSXK9kv6ks8wXoxINAI:bjrvwtr) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L533)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

"Engine started successfully"
Will be more clear when debugging
</blockquote></details>

Hm, this is the same as in other engines - @kfilipek could you start some issue with "minor refactoring ideas" and put it there? We might fix all occurences at once in a separate PR.
___
*[src/engines-experimental/robinhood.cc, line 538 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTDljx6--ROyGTyXEE:-MSXKTFZ8rDVRAW8UBGl:bi7jn84) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L538)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You can trigger destructor also when try-catch fails.
try{
create_robinhood
do_something (throws exception)
catch(){
}
You will get:
Started ok
Stopped ok
and it can be not clear.
Maybe something like: "Destructing engine"?
</blockquote></details>

I'm not sure what is not clear with this. Destructed/stopeed seems pretty much the same for me.
___
*[src/engines-experimental/robinhood.cc, line 709 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXKmnr6-gKoaSc3Gvg:-MSXKmnr6-gKoaSc3Gvh:bua4h9l) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L709)):*
> ```cpp
> 		for (size_t i = 0; i < shards_number; ++i) {
> 			for (size_t j = 0; j < 4; ++j)
> 				actv.emplace_back();
> ```

As I said, please move this into rp_create


<!-- Sent from Reviewable.io -->

2021-02-02 10:47 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 29 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXLcoV9qYx3zdKyiV8:-MSXLcoV9qYx3zdKyiV9:bwk4y4z) (no related file):*
There are some lines (and even whole functions) not covered by tests: https://github.com/pmem/pmemkv/pull/881/files#diff-7e891ba5edff52325cffae0dedd3621a30e18bc2def17686a129f04c0b8966b0 Could you take a look?

---


<!-- Sent from Reviewable.io -->

2021-02-03 13:40 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 8 of 16 files reviewed, 29 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXLcoV9qYx3zdKyiV8:-MSc6HMjAkx7lMjNsAyV:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There are some lines (and even whole functions) not covered by tests: https://github.com/pmem/pmemkv/pull/881/files#diff-7e891ba5edff52325cffae0dedd3621a30e18bc2def17686a129f04c0b8966b0 Could you take a look?
</blockquote></details>

Done.

---
___
*[src/fast_hash.h, line 27 at r5](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXE5pi8DNafiR2r52i:-MSYR7eqDFZq2NNx2a4U:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/478916fdf763edd8c0f4d6850f1bdd29dda85363/src/fast_hash.h#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We might also write this file as an exception in: https://github.com/pmem/pmemkv/blob/master/LICENSE
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQq19Rt1rJGgIreVlM1:-MSXnjsO6I2XIfKrs8LF:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L16)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include "../comparator/pmemobj_comparator.h"
> #include "../pmemobj_engine.h"
> #include <libpmemobj++/persistent_ptr.hpp>
> #include <libpmemobj.h>
> #include <mutex>
> #include <shared_mutex>
> #include <stddef.h>
> #include <stdint.h>
> ```
Reorder headers according to:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 70 at r1](https://reviewable.io/reviews/pmem/pmemkv/881#-MQq6BYzAMQZZ1NryzCw:-MSXffXZ17-uIMrlvrKi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d3c9ab7f13386dcea84359a65e85cac9bff31017/src/engines-experimental/robinhood.h#L70)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove empy line
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXIXM0AWfmiFCQWr5F:-MSXlVnDBgJ1WVhcP-N1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L101)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, maybe instead of passing pobj_action* you could pass a reference to std::vector<pobj_action> and just call emplace_back() before each pmemobj_action function? It will be much less error-prone.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 110 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST8mqN1CvaOeH9p5J7:-MSY55doEW-Maqw1aszt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L110)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Please fix other occurences (next issue)
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 128 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST8FJy8zQAVekPLzmN:-MSY4sEzECgl5Mwzss9b:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L128)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

is second constructor needed here?
you will get something like: std::string(text1).operator+(std::string(text2))
instead of
std::string(text).operator+(text2)
There is no need to do that since we have overloaded '+' operator: http://www.cplusplus.com/reference/string/string/operator+/
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 141 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTBW0i5h7OGLB6O9ct:-MSXfxQPEpYFrlBgHpkN:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L141)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

There is no need to use return; on void functions at the end of function body
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 189 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTBIBR7eU319T0aLyc:-MSY6h2w7-YosHZ36NF4:b-3rw0mx) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L189)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

When this occur?
</blockquote></details>

It should be: - 1 if insertion required too many swaps, and occurs when we exceeded maximum number of swaps allowed during single insertion
___
*[src/engines-experimental/robinhood.cc, line 353 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST96Uy-QY9zqnoihI6:-MSY4tYd3BxBT3GdM8D9:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L353)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 386 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXJYS_EgoL4Odjidb6:-MSXlYBU5Zt2QMFHt6Mk:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L386)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

std vector
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 397 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTA116EGQyqWWefl_W:-MSY5mxX-RnX0yd4CfIo:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L397)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

key exists
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 524 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTDURR0BOzvTI3m5OU:-MSXg3e_5hlFwwm8PMoU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L524)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Remove comment. Code below looks clear enough, I believe
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 525 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXJk8R3CbibbFR3G_b:-MSXg3wT9zsNfiPe8jRl:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L525)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe move this code to Recover() method? It's unspoken rule, but we basically put all the code there - it's more clear what is done on reopen and what on create.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 527 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSXK2Qn5g3woGi641oU:-MSXgjuY8_V31xvXgbkU:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L527)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you can just use std::stoi or something li [...]

2021-02-03 15:33 UTC, KFilipek reviewed
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[src/engines-experimental/robinhood.cc, line 189 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTBIBR7eU319T0aLyc:-MScVIml4x9xEMHFRRQz:bigfqy1) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L189)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

It should be: - 1 if insertion required too many swaps, and occurs when we exceeded maximum number of swaps allowed during single insertion
</blockquote></details>

I don't see any point where value 1 can be returned, it's my point
___
*[src/engines-experimental/robinhood.cc, line 359 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST994x5oV8FoS8NBWW:-MSbuPPH6Kw9qt-sJZvm:b-repntq) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L359)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Sure, we could avoid this if it would be C++ code but it's only C code compiled as C++. I would suggest leaving this as is and fixing it after we decide to rework the implementation in C++. In C, gotos for error handling are fine (when used in consistent manner).
</blockquote></details>

Right, because there is no objects, destructors etc. 
___
*[src/engines-experimental/robinhood.cc, line 538 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTDljx6--ROyGTyXEE:-MScW7H13F6_T7cU5PZV:b6re928) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L538)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure what is not clear with this. Destructed/stopeed seems pretty much the same for me.
</blockquote></details>

Let it be.


<!-- Sent from Reviewable.io -->

2021-02-04 09:50 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 15 of 18 files reviewed, 19 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines-experimental/robinhood.cc, line 189 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTBIBR7eU319T0aLyc:-MSgR-RsDOp9f8GJbQDi:br0bg26) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L189)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I don't see any point where value 1 can be returned, it's my point
</blockquote></details>

Yes, you're right. I removed this line.
___
*[src/engines-experimental/robinhood.cc, line 354 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST9kOB8M0tr2r-_STx:-MScXHol3XZUB9ry0RjL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L354)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 359 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MST994x5oV8FoS8NBWW:-MScXH2R-UxFd7mBF72U:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L359)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Right, because there is no objects, destructors etc. 
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 538 at r6](https://reviewable.io/reviews/pmem/pmemkv/881#-MSTDljx6--ROyGTyXEE:-MScXJvi6oQ19Fg5gr3Y:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e74c6f2430f49172113980a4e8e85f0c63ff07bf/src/engines-experimental/robinhood.cc#L538)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Let it be.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 10:14 UTC, KFilipek reviewed
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 16 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[tests/engines/pmemobj_based/pmreorder/recover.cmake, line 20 at r8](https://reviewable.io/reviews/pmem/pmemkv/881#-MSgXJGdBkyvzKvG-QkO:-MSgXJGeEcihM2e3hCH2:b-mypiny) ([raw file](https://github.com/pmem/pmemkv/blob/ee476f2cdb3a9c17b75d393831315087a9936b49/tests/engines/pmemobj_based/pmreorder/recover.cmake#L20)):*
> ```CMake
> pmreorder_execute(true ReorderAccumulative ${PARENT_SRC_DIR}/engines/pmemobj_based/pmreorder/pmreorder.conf ${TEST_EXECUTABLE} ${ENGINE} ${CONFIG} open ${PARAMS})
> 
> finish()
> ```

no EOF


<!-- Sent from Reviewable.io -->

2021-02-04 11:58 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 9 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmreorder/recover.cc, line 14 at r8](https://reviewable.io/reviews/pmem/pmemkv/881#-MSgtaqT0FFvzGDmXU9J:-MSgtaqT0FFvzGDmXU9K:b-92xy18) ([raw file](https://github.com/pmem/pmemkv/blob/ee476f2cdb3a9c17b75d393831315087a9936b49/tests/engine_scenarios/pmreorder/recover.cc#L14)):*
> ```cpp
> 	auto kv = INITIALIZE_KV(engine, CONFIG_FROM_JSON(config));
> 
> 	kv.close();
> ```

Don't call close here, we want to test opening only


<!-- Sent from Reviewable.io -->

2021-02-04 14:27 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmreorder/recover.cc, line 14 at r8](https://reviewable.io/reviews/pmem/pmemkv/881#-MSgtaqT0FFvzGDmXU9J:-MShNUDK9rnvxbJ8ON-T:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ee476f2cdb3a9c17b75d393831315087a9936b49/tests/engine_scenarios/pmreorder/recover.cc#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Don't call close here, we want to test opening only
</blockquote></details>

Done.
___
*[tests/engines/pmemobj_based/pmreorder/recover.cmake, line 20 at r8](https://reviewable.io/reviews/pmem/pmemkv/881#-MSgXJGdBkyvzKvG-QkO:-MShNVbfBWy-k_Fk1tWe:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/ee476f2cdb3a9c17b75d393831315087a9936b49/tests/engines/pmemobj_based/pmreorder/recover.cmake#L20)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

no EOF
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 14:48 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmreorder/recover.cc, line 47 at r9](https://reviewable.io/reviews/pmem/pmemkv/881#-MShVWVw4AI8HEChJiFf:-MShVWVw4AI8HEChJiFg:b-k07m9b) ([raw file](https://github.com/pmem/pmemkv/blob/cfcaa2dd45d5f426691c44376ebe3a9c453582c3/tests/engine_scenarios/pmreorder/recover.cc#L47)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	std::cout << "ARGC: " << argc << std::endl;
> 	for (int i = 0; i < argc; ++i) {
> 		std::cout << "ARGV " << i << " : " << argv[i] << std::endl;
> 	}
> ```
</details>

Remove temp printing


<!-- Sent from Reviewable.io -->

2021-02-05 12:13 UTC, lukaszstolarczuk commented
please add in the last commit message info it fixes the #892

2021-02-05 12:29 UTC, KFilipek reviewed
@luke 
"Closes #892" sounds better when we're talking about issues. Especially when extending tests is not a fixing bug.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881#-:-MSm9UD1-sRLsddOjXc4:b-iqqfb3)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-02-05 13:37 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/engine_scenarios/pmreorder/recover.cc, line 47 at r9](https://reviewable.io/reviews/pmem/pmemkv/881#-MShVWVw4AI8HEChJiFf:-MSmOE-53XbJWI0c8yfV:bjxx0mc) ([raw file](https://github.com/pmem/pmemkv/blob/cfcaa2dd45d5f426691c44376ebe3a9c453582c3/tests/engine_scenarios/pmreorder/recover.cc#L47)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	std::cout << "ARGC: " << argc << std::endl;
> 	for (int i = 0; i < argc; ++i) {
> 		std::cout << "ARGV " << i << " : " << argv[i] << std::endl;
> 	}
> ```
Remove temp printing
</blockquote></details>

We have that print in every pmreorder test. Do you think that it should be removed in every test? Or should I leave this as it is?


<!-- Sent from Reviewable.io -->

2021-02-08 10:34 UTC, lukaszstolarczuk reviewed
> Reviewed 7 of 11 files at r6, 5 of 8 files at r7, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[README.md, line 98 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0-pQN8rMDlVoGfjYz:-MT0-pQN8rMDlVoGfjZ-:baio1yf) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/README.md#L98)):*
> ```Markdown
> 
> ## Contact us
> For more information about **pmemkv**, contact Igor Chorążewicz (igor.chorazewicz@intel.com),
> ```

something went wrong, this change shouldn't be here
___
*[tests/CMakeLists.txt, line 1429 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT02ZUE2TcVuJ8ql4Cy:-MT02ZUE2TcVuJ8ql4Cz:bgbef9s) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/CMakeLists.txt#L1429)):*
> ```CMake
> ###################################### RADIX ###################################
> if(ENGINE_RADIX)
> 	add_engine_test(ENGINE robinhood
> ```

robinhood here?
___
*[tests/engine_scenarios/pmreorder/recover.cc, line 17 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0BHEv8PRZqwPMBfCJ:-MT0BHEv8PRZqwPMBfCK:b-d4qohw) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/engine_scenarios/pmreorder/recover.cc#L17)):*
> ```cpp
> 
> 	ASSERT_STATUS(kv.count_all(cnt), pmem::kv::status::OK);
> 	UT_ASSERT(cnt == 0);
> ```

pls use UT_ASSERTeq (+2 occurrences below)


<!-- Sent from Reviewable.io -->

2021-02-08 14:52 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 8 files at r7, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[src/engines-experimental/robinhood.h, line 133 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT12qzE1l2yN8YDl8r5:-MT12qzE1l2yN8YDl8r6:b-hmglsy) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.h#L133)):*
> ```objc
> 	size_t shard_hash(uint64_t key);
> 
> 	TOID(struct internal::robinhood::hashmap_rp) * container;
> ```

remove space between "*" and "container", I believe
___
*[src/engines-experimental/robinhood.cc, line 10 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT14bBgAoj5GKFIH0BW:-MT14bBh43IVzY0KQcLH:bbh4dsc) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L10)):*
> ```cpp
> 
> #include <unistd.h>
> ```

maybe it'd be nice to have some general description, perhaps with just a link to algorithm description
___
*[src/engines-experimental/robinhood.cc, line 28 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT160GR7F8WH0COf7FQ:-MT160GR7F8WH0COf7FR:b-72lia0) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L28)):*
> ```cpp
> static float get_load_factor()
> {
> 	auto lf = std::getenv("ENGINE_ROBINHOOD_LOAD_FACTOR");
> ```

since this is OS-wide variable, maybe rename to PMEMKV_ROBINHOOD_* (the other one too)

and it's not documented anywhere..(?)
___
*[src/engines-experimental/robinhood.cc, line 75 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0xyJ16DYuBaEJRV1k:-MT0xyJ16DYuBaEJRV1l:b7fxkpu) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L75)):*
> ```cpp
>  * hash -- hash function based on Austin Appleby MurmurHash3 64-bit finalizer.
>  * Returned value is modified to work with special values for unused and
>  * and deleted hashes.
> ```

`and and deleted hashes.`
___
*[src/engines-experimental/robinhood.cc, line 289 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT1-X7PCgCOTNJVtVGf:-MT1-X7PCgCOTNJVtVGg:b-9bxlyc) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L289)):*
> ```cpp
> 
> /*
>  * entries_cache -- cache entries from second argument in entries from first
> ```

"second" and "first" arguments - did you mean `src` and `dest`?
___
*[src/engines-experimental/robinhood.cc, line 408 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT15SH-Bqig7yzi1Vog:-MT15SH-Bqig7yzi1Voh:b-7f58o3) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L408)):*
> ```cpp
>  * returns:
>  * - true if successful,
>  * - false if value didn't exist or if something bad happened
> ```

maybe extend this and return int? we couldn't know the difference calling `kv->remove(key)`
___
*[src/engines-experimental/robinhood.cc, line 486 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT115y58pWz-1uVQPh1:-MT115y61PJgTjZS0Zcl:b-55o7n5) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L486)):*
> ```cpp
> 			continue;
> 
> 		ret = cb(reinterpret_cast<const char *>(&(entry_p->key)), 8,
> ```

8? a magic number
___
*[src/engines-experimental/robinhood.cc, line 509 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT119ZT8IJduTHxRhdC:-MT119ZU1lxF-qAzDGWg:b-8mptj2) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L509)):*
> ```cpp
> size_t robinhood::shard_hash(uint64_t key)
> {
> 	return static_cast<size_t>(fast_hash(8, reinterpret_cast<const char *>(&key)) &
> ```

. (8)
___
*[src/engines-experimental/robinhood.cc, line 565 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT13g2BC6pN4j4JHcUK:-MT13g2BC6pN4j4JHcUL:b-4w3677) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L565)):*
> ```cpp
> 	check_outside_tx();
> 
> 	if (key.size() != 8)
> ```

. (and few more instances, if fixing, pls fix them all)
___
*[src/engines-experimental/robinhood.cc, line 666 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT16uBuC2O1UuPJQOFz:-MT16uBuC2O1UuPJQOG-:b-tjhanb) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L666)):*
> ```cpp
> 			throw internal::invalid_argument(
> 				"Wrong number of shards set: " +
> 				std::to_string(this->shards_number) + "), expected: " +
> ```

`"), e` - drop the `)`


<!-- Sent from Reviewable.io -->

2021-02-08 15:23 UTC, igchor requested changes
> Reviewed 1 of 11 files at r6, 2 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: all files reviewed, 16 unresolved discussions (waiting on @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines-experimental/robinhood.cc, line 28 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT160GR7F8WH0COf7FQ:-MT1DrsX-U8a_zrdNv6l:b32v57) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since this is OS-wide variable, maybe rename to PMEMKV_ROBINHOOD_* (the other one too)

and it's not documented anywhere..(?)
</blockquote></details>

+1
___
*[tests/CMakeLists.txt, line 146 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT1E5ES4B1kfW9d6A2T:-MT1E5ET6NjfDjcsZVZm:bd7iyh2) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/CMakeLists.txt#L146)):*
> ```CMake
> # ----------------------------------------------------------------- #
> # Tests for all engines
> # XXX: Parameterize to work with fixed size keys/values.
> ```

maybe add XXX under robinhood so that we know what needs to be done if we'd like to productize robinhoo
___
*[tests/engines/pmemobj_based/pmreorder/recover.cmake, line 22 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT1DEcJ-jZZmQJBvnYW:-MT1DEcJ-jZZmQJBvnYX:b-ns2816) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/engines/pmemobj_based/pmreorder/recover.cmake#L22)):*
> ```CMake
> 
> pmreorder_create_store_log(${DIR}/testfile ${TEST_EXECUTABLE} ${ENGINE} ${CONFIG} create ${PARAMS})
> pmreorder_execute(true ReorderPartial ${PARENT_SRC_DIR}/engines/pmemobj_based/pmreorder/pmreorder.conf ${TEST_EXECUTABLE} ${ENGINE} ${CONFIG} open ${PARAMS})
> ```

Could you check if the test time would be reasonable for ReorderAccumulative with shorter check_consistency (e.g. just 3 inserts)?


<!-- Sent from Reviewable.io -->

2021-02-09 10:39 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 11 of 18 files reviewed, 15 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[README.md, line 98 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0-pQN8rMDlVoGfjYz:-MT53kSXAtj_LXCfE4Tc:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/README.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

something went wrong, this change shouldn't be here
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.h, line 133 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT12qzE1l2yN8YDl8r5:-MT4vgvWCtDvxhI7DB6u:bg7y1vm) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.h#L133)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remove space between "*" and "container", I believe
</blockquote></details>

make cppformat adds this space automatically
___
*[src/engines-experimental/robinhood.cc, line 10 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT14bBgAoj5GKFIH0BW:-MT58nYi2L8JJbICQukm:buafthd) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe it'd be nice to have some general description, perhaps with just a link to algorithm description
</blockquote></details>

Done, in ENGINES-experimental.md
___
*[src/engines-experimental/robinhood.cc, line 28 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT160GR7F8WH0COf7FQ:-MT58qgRASVDdAFcAJzT:buafthd) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L28)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done, in ENGINES-experimental.md
___
*[src/engines-experimental/robinhood.cc, line 75 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0xyJ16DYuBaEJRV1k:-MT4yfz3BIKICJsi6mmK:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`and and deleted hashes.`
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 289 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT1-X7PCgCOTNJVtVGf:-MT4ygOTCbsqIIIYaOVn:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L289)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"second" and "first" arguments - did you mean `src` and `dest`?
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 408 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT15SH-Bqig7yzi1Vog:-MT4z9gk6P18x22eTybt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L408)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe extend this and return int? we couldn't know the difference calling `kv->remove(key)`
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 486 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT115y58pWz-1uVQPh1:-MT5-b9-3yNR0yNaMcfW:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L486)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

8? a magic number
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 509 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT119ZT8IJduTHxRhdC:-MT5-m3iBFuPRxEc7Tn3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L509)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (8)
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 565 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT13g2BC6pN4j4JHcUK:-MT50oMq4U9WXEBk5q1c:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L565)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (and few more instances, if fixing, pls fix them all)
</blockquote></details>

Done.
___
*[src/engines-experimental/robinhood.cc, line 666 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT16uBuC2O1UuPJQOFz:-MT50vMu98DyxE2nXt7a:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L666)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`"), e` - drop the `)`
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 146 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT1E5ES4B1kfW9d6A2T:-MT519xj27eLeNlpZBEE:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/CMakeLists.txt#L146)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe add XXX under robinhood so that we know what needs to be done if we'd like to productize robinhoo
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 1429 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT02ZUE2TcVuJ8ql4Cy:-MT51ZohCccGQuKSCGYQ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/CMakeLists.txt#L1429)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

robinhood here?
</blockquote></details>

Done.
___
*[tests/engine_scenarios/pmreorder/recover.cc, line 17 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT0BHEv8PRZqwPMBfCJ:-MT51iH6CTKNCPsJg-9z:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/tests/engine_scenarios/pmreorder/recover.cc#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use UT_ASSERTeq (+2 occurrences below)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 10:44 UTC, KFilipek reviewed
> Reviewed 1 of 8 files at r5, 3 of 3 files at r11, 1 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: 12 of 18 files reviewed, 15 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines-experimental/robinhood.cc, line 486 at r11](https://reviewable.io/reviews/pmem/pmemkv/881#-MT115y58pWz-1uVQPh1:-MT5LJkX3-5FkyTauorM:b-8j3ol3) ([raw file](https://github.com/pmem/pmemkv/blob/a088a86f7df017b28c572addecca977e2dc2a2f5/src/engines-experimental/robinhood.cc#L486)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

8? a magic number
</blockquote></details>

42 xD


<!-- Sent from Reviewable.io -->

2021-02-09 11:35 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881#-:-MT5ZdP845mBIXB8EtRC:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-02-09 11:48 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r12, 3 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881#-:-MT5bj6Q9NgwaW-MY3ZA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-02-09 12:06 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881#-:-MT5fUr-50icM01Nu3x6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)



<!-- Sent from Reviewable.io -->

2021-02-09 14:22 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/881)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)



<!-- Sent from Reviewable.io -->

2021-02-09 15:24 UTC, merged