Not supported fix
pmem/pmemkv pull request #904
Opened 2021-02-04 15:15 UTC by karczex

2021-02-04 15:19 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904#-:-MShc--x3CSbjL-H7blT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-02-04 15:20 UTC, igchor reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/CMakeLists.txt, line 1444 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShc5_090oY8bj6DMEc:-MShc5_090oY8bj6DMEd:b8qch0u) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/CMakeLists.txt#L1444)):*
> ```CMake
> 
> 		add_engine_test(ENGINE stree
> 			BINARY transaction_basic
> ```

I think it would be better to have separate test for NOT_SUPPORTED and run it only for engines which do not support transactions.


<!-- Sent from Reviewable.io -->

2021-02-04 15:32 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[src/engine.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShe3A_C4DstYRgTJBP:-MShe3A_C4DstYRgTJBQ:bb6ht36) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/src/engine.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2020, Intel Corporation */
> ```

2021
___
*[src/engine.cc, line 216 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShe3qg5t3x3YX87VdT:-MShe3qg5t3x3YX87VdU:b5i26cn) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/src/engine.cc#L216)):*
> ```cpp
> internal::transaction *engine_base::begin_tx()
> {
> 	throw internal::not_supported("Transactions are not supported");
> ```

if you want to be verbose, make it `.. in this engine`
___
*[tests/CMakeLists.txt, line 133 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MSheXd19dWqnkxtRu7q:-MSheXd19dWqnkxtRu7r:bukw40m) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/CMakeLists.txt#L133)):*
> ```CMake
> add_test_generic(NAME config_cpp TRACERS none memcheck)
> 
> build_test(blackhole_test engines/blackhole/blackhole_test.cc)
> ```

we usually extended blackhole_test for C++ API - it should be added I guess (since blackhole also does not support iter/tx)
___
*[tests/engine_scenarios/transaction/basic.cc, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShf1ZE7iT5fdT8EbCm:-MShf1ZE7iT5fdT8EbCn:b5bv7er) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/engine_scenarios/transaction/basic.cc#L1)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> ```

if you add tests like this for tx, then add it also for iters
___
*[tests/engine_scenarios/transaction/basic.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MSheCyf5zPJT4wvjWun:-MSheCyf5zPJT4wvjWuo:bb6ht36) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/engine_scenarios/transaction/basic.cc#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

2021


<!-- Sent from Reviewable.io -->

2021-02-05 10:20 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/engine.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShe3A_C4DstYRgTJBP:-MShkc_A7MaU66Te_YK3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/src/engine.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[src/engine.cc, line 216 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShe3qg5t3x3YX87VdT:-MShkcrU5FOBISTYBU1J:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/src/engine.cc#L216)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to be verbose, make it `.. in this engine`
</blockquote></details>

Done.
___
*[tests/engine_scenarios/transaction/basic.cc, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MShf1ZE7iT5fdT8EbCm:-MSlh3X8ASfYjbcOqwiS:b3idmfj) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/engine_scenarios/transaction/basic.cc#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you add tests like this for tx, then add it also for iters
</blockquote></details>

Really good catch :). It appeared, there is another bug in iterators. Done. 
___
*[tests/engine_scenarios/transaction/basic.cc, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MSheCyf5zPJT4wvjWun:-MSlh33_0Fs3kgj5brvu:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/engine_scenarios/transaction/basic.cc#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 10:59 UTC, KFilipek reviewed
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-02-05 11:34 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 133 at r1](https://reviewable.io/reviews/pmem/pmemkv/904#-MSheXd19dWqnkxtRu7q:-MSlwr2H6hC_opQP1ZD-:bu7qe6q) ([raw file](https://github.com/pmem/pmemkv/blob/96c2bdfa49be351d78095b30f90ba3ab8672de31/tests/CMakeLists.txt#L133)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we usually extended blackhole_test for C++ API - it should be added I guess (since blackhole also does not support iter/tx)
</blockquote></details>

iterators are implemented for blackhole. Done


<!-- Sent from Reviewable.io -->

2021-02-05 15:23 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904#-:-MSmmgzHBxHGyJC3Nc2-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-02-08 08:30 UTC, igchor requested changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[src/libpmemkv.cc, line 657 at r3](https://reviewable.io/reviews/pmem/pmemkv/904#-MT-kaPT23FsrrbzRsLx:-MT-kaPU9GiAKbBrtr5x:bfpg2p3) ([raw file](https://github.com/pmem/pmemkv/blob/3389de02b87c3fd00373b5e267a05264f699ea6e/src/libpmemkv.cc#L657)):*
> ```cpp
> 		return PMEMKV_STATUS_INVALID_ARGUMENT;
> 
> 	try {
> ```

Could you just use catch_and_return status here instead of manually catching the exceptions? It'll cover more cases (e.g. OUT_OF_MEMORY)
___
*[src/libpmemkv.cc, line 672 at r3](https://reviewable.io/reviews/pmem/pmemkv/904#-MT-kkn2EmDMGXcJvM_f:-MT-kkn2EmDMGXcJvM_g:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/3389de02b87c3fd00373b5e267a05264f699ea6e/src/libpmemkv.cc#L672)):*
> ```cpp
> 		return PMEMKV_STATUS_INVALID_ARGUMENT;
> 
> 	try {
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-08 09:59 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/libpmemkv.cc, line 657 at r3](https://reviewable.io/reviews/pmem/pmemkv/904#-MT-kaPT23FsrrbzRsLx:-MT04897DnN38To-0ftv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3389de02b87c3fd00373b5e267a05264f699ea6e/src/libpmemkv.cc#L657)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you just use catch_and_return status here instead of manually catching the exceptions? It'll cover more cases (e.g. OUT_OF_MEMORY)
</blockquote></details>

Done.
___
*[src/libpmemkv.cc, line 672 at r3](https://reviewable.io/reviews/pmem/pmemkv/904#-MT-kkn2EmDMGXcJvM_f:-MT04BR37uvpR5rB7mPR:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3389de02b87c3fd00373b5e267a05264f699ea6e/src/libpmemkv.cc#L672)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 12:43 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/libpmemkv.cc, line 672 at r3](https://reviewable.io/reviews/pmem/pmemkv/904#-MT-kkn2EmDMGXcJvM_f:-MT0dATZEyBJ3waSp7Xl:b-2nfqr8) ([raw file](https://github.com/pmem/pmemkv/blob/3389de02b87c3fd00373b5e267a05264f699ea6e/src/libpmemkv.cc#L672)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Imo it's better to use existing solutions so I think it might be a little bit easier (and less error-prone) to use unique_ptr instead of this cleanup function. It would just look like this:

```
auto uptr = std::unique_ptr<pmemkv_write_iterator>(new pmemkv_write_iterator());
uptr->iter = iterator_from_internal(...);
*it = uptr.release();
return PMEMKV_STATUS_OK;
```


<!-- Sent from Reviewable.io -->

2021-02-09 12:11 UTC, igchor approved these changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-02-09 12:15 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[src/libpmemkv.cc, line 668 at r4](https://reviewable.io/reviews/pmem/pmemkv/904#-MT5hEuP7E5nJJs0k0Dm:-MT5hEuQ3_4bx9s8oaoP:bbwk7hv) ([raw file](https://github.com/pmem/pmemkv/blob/2ef7661a89f843d7bff14afb68752d3ed11b84bf/src/libpmemkv.cc#L668)):*
> ```cpp
> 		return PMEMKV_STATUS_INVALID_ARGUMENT;
> 
> 	return catch_and_return_status(__func__, [&] {
> ```

__PRETTY_FUNCTION__ also decorate function under GCC. After some preprocessor if's we can get nice error handling
https://www.rowleydownload.co.uk/arm/documentation/gnu/gcc/Function-Names.html


<!-- Sent from Reviewable.io -->

2021-02-09 12:42 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[src/libpmemkv.cc, line 668 at r4](https://reviewable.io/reviews/pmem/pmemkv/904#-MT5hEuP7E5nJJs0k0Dm:-MT5nvLf9ebCHceVEGsw:b2gnw0v) ([raw file](https://github.com/pmem/pmemkv/blob/2ef7661a89f843d7bff14afb68752d3ed11b84bf/src/libpmemkv.cc#L668)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

__PRETTY_FUNCTION__ also decorate function under GCC. After some preprocessor if's we can get nice error handling
https://www.rowleydownload.co.uk/arm/documentation/gnu/gcc/Function-Names.html
</blockquote></details>

I don't think we want PRETTY_FUNCTION. It adds function signature and I think it's not needed. For a use, it;s enough to know the name of a function.


<!-- Sent from Reviewable.io -->

2021-02-09 12:42 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/904)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[src/libpmemkv.cc, line 668 at r4](https://reviewable.io/reviews/pmem/pmemkv/904#-MT5hEuP7E5nJJs0k0Dm:-MT5o63mB28bSW2i6YY3:bime478) ([raw file](https://github.com/pmem/pmemkv/blob/2ef7661a89f843d7bff14afb68752d3ed11b84bf/src/libpmemkv.cc#L668)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't think we want PRETTY_FUNCTION. It adds function signature and I think it's not needed. For a use, it;s enough to know the name of a function.
</blockquote></details>

for a user*


<!-- Sent from Reviewable.io -->

2021-02-09 12:49 UTC, karczex commented
___
*[src/libpmemkv.cc, line 668 at r4](https://reviewable.io/reviews/pmem/pmemkv/904#-MT5hEuP7E5nJJs0k0Dm:-MT5p-prCAKn3C73OtA2:bye9r4i) ([raw file](https://github.com/pmem/pmemkv/blob/2ef7661a89f843d7bff14afb68752d3ed11b84bf/src/libpmemkv.cc#L668)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

for a user*
</blockquote></details>

We use PRETTY_FUNCTION in [tests](https://github.com/pmem/pmemkv/blob/ee78f8e1acc80c2ba4a44bf277662befbd27379b/tests/common/unittest.hpp#L43), as it's a pleace where it matters.


<!-- Sent from Reviewable.io -->

2021-02-09 13:05 UTC, merged