Extend open/create config's options
pmem/pmemkv pull request #944
Opened 2021-02-19 13:42 UTC by lukaszstolarczuk

- [x] replace `force_create` with `error_if_exists`
- [ ] add new config option `create_if_missing`
- [ ] fix and extend documentation
- [ ] extend examples
- [ ] extend tests and add some new

2021-02-22 10:16 UTC, igchor reviewed
> Reviewed 2 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 2 of 21 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-26 13:27 UTC, KFilipek reviewed
> Reviewed 13 of 21 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 16 of 21 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-02 13:20 UTC, KFilipek reviewed
> Reviewed 3 of 21 files at r1, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/config/deprecated_config_cpp.cc, line 8 at r3](https://reviewable.io/reviews/pmem/pmemkv/944#-MUn4XPX-X2EquhmT3S4:-MUn4XPY6jXKUKbRKb6-:bwtthou) ([raw file](https://github.com/pmem/pmemkv/blob/3ae6b298fbc308d6cb1b7a9ca1986214132fbc87/tests/config/deprecated_config_cpp.cc#L8)):*
> ```cpp
> #include <string>
> #include <vector>
> ```

no new line


<!-- Sent from Reviewable.io -->

2021-03-03 12:21 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 5 of 28 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[tests/config/deprecated_config_cpp.cc, line 8 at r3](https://reviewable.io/reviews/pmem/pmemkv/944#-MUn4XPX-X2EquhmT3S4:-MUry5L01VaRhBV2h8F0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/3ae6b298fbc308d6cb1b7a9ca1986214132fbc87/tests/config/deprecated_config_cpp.cc#L8)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

no new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 13:10 UTC, KFilipek reviewed
> Reviewed 23 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/libpmemkv.hpp, line 1532 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs43e69XXtj84mVkmy:-MUs43e75mlB7svKm2TM:bm916o2) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1532)):*
> ```cpp
> inline status config::put_error_if_exists(bool value) noexcept
> {
> 	return put_uint64("error_if_exists", value ? 1 : 0);
> ```

logic here is not necessary: (uint64_t)value
___
*[src/libpmemkv.hpp, line 1549 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs3kdQ4qyCTBX2LB9q:-MUs3kdQ4qyCTBX2LB9r:bm916o2) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1549)):*
> ```cpp
> {
> 	return put_uint64("create_if_missing", value ? 1 : 0);
> }
> ```

logic here is not necessary: (uint64_t)value
___
*[src/libpmemkv.cc, line 225 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs46BL5Xi-10PNK7hl:-MUs46BM3LGZxE6rMb6k:bm916o2) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.cc#L225)):*
> ```cpp
> int pmemkv_config_put_create_if_missing(pmemkv_config *config, bool value)
> {
> 	return pmemkv_config_put_uint64(config, "create_if_missing", value ? 1 : 0);
> ```

logic here is not necessary: (uint64_t)value


<!-- Sent from Reviewable.io -->

2021-03-04 10:19 UTC, KFilipek reviewed
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-03-08 16:00 UTC, igchor requested changes
> Reviewed 1 of 23 files at r4, 4 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 25 of 32 files reviewed, 11 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[ChangeLog, line 13 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGlHlB6xhXzrzBkbWU:-MVGlHlB6xhXzrzBkbWV:bjravob) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/ChangeLog#L13)):*
> ```
> 	Other changes:
> 	- Deprecate config's flag 'force_create' and add an alias: 'error_if_exists' (#576)
> 		The old flag can still be used and it behaves with no difference. It's
> ```

No mention about create_if_missing?
___
*[doc/ENGINES-experimental.md, line 22 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGla-VBcpeeoSetwrS:-MVGla-VBcpeeoSetwrT:b-vaerh2) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L22)):*
> ```Markdown
> 	+ type: string
> * **create_if_missing** -- If 1, pmemkv tries to create the file and when that doesn't succeed it tries to open it.
> 	If 0, pmemkv uses **error_if_exists** flag to create/open the file.
> ```

Hm, shouldn't the default behavior be the same as it is right now? That is, tries to open the database and fails if there is no such pool.
___
*[doc/ENGINES-experimental.md, line 25 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGlr_-1PUj_lEdWAbS:-MVGlr_-1PUj_lEdWAbT:bogt619) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L25)):*
> ```Markdown
> 	+ type: uint64_t
> 	+ default value: 0
> * **error_if_exists** -- If 1, pmemkv creates the file (but it will fail if path exists),
> ```

Can we set both of those flags to 1? What will happen?
___
*[doc/libpmemkv.7.md, line 71 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGm-uZD78Ycfi9bQmO:-MVGm-uZD78Ycfi9bQmP:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/libpmemkv.7.md#L71)):*
> ```Markdown
> 	+ type: string
> * **create_if_missing** -- If 1, pmemkv tries to create the file and when that doesn't succeed it tries to open it.
> 	If 0, pmemkv uses **error_if_exists** flag to create/open the file.
> ```

.
___
*[doc/libpmemkv_config.3.md.in, line 39 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGutpT54LriaeDQssM:-MVGutpT54LriaeDQssN:bpb7cwy) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/libpmemkv_config.3.md.in#L39)):*
> ```
> int **deprecated** pmemkv_config_put_force_create(pmemkv_config *config,
> 							   bool value);
> int pmemkv_config_put_error_if_exists(pmemkv_config *config, bool value);
> ```

what about create_if_missing?
___
*[src/libpmemkv.hpp, line 1519 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGvvgu-kJHin8tMm1h:-MVGvvgu-kJHin8tMm1i:b-nsd0n4) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1519)):*
> ```cpp
> /**
>  * Puts error_if_exists parameter to a config. This flag has lower priority than
>  * **create_if_missing** (see config::put_create_if_missing), setting them both makes no
> ```

so maybe disallow setting both?
___
*[src/libpmemkv.hpp, line 1522 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGw06B4bn2kYVU7SI1:-MVGw06B4bn2kYVU7SI2:b-7iwyeb) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1522)):*
> ```cpp
>  *sense. Works only with engines supporting this flag and it means: If true: pmemkv
>  *creates the file, unless it exists - than it fails. If false: pmemkv opens the file
>  *specified by 'path' (see config::put_path), unless the path does not exist - than it
> ```

then?
___
*[src/libpmemkv.hpp, line 1534 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGw6W70MJvvntIeZAS:-MVGw6W70MJvvntIeZAT:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1534)):*
> ```cpp
> /**
>  * Puts create_if_missing parameter to a config. This flag is prioritized before
>  * **error_if_exists** (see config::put_error_if_exists) and is encouraged to use.
> ```

.


<!-- Sent from Reviewable.io -->

2021-03-08 16:43 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 25 of 32 files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[ChangeLog, line 13 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGlHlB6xhXzrzBkbWU:-MVHgkfR2u_vMBMEJmnB:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/ChangeLog#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

No mention about create_if_missing?
</blockquote></details>

Done.
___
*[doc/ENGINES-experimental.md, line 22 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGla-VBcpeeoSetwrS:-MVHgrNs8o2eW8S-EYtb:b25u2og) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, shouldn't the default behavior be the same as it is right now? That is, tries to open the database and fails if there is no such pool.
</blockquote></details>

the default stays the same, since we set the new flag to 0 by default
___
*[doc/ENGINES-experimental.md, line 25 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGlr_-1PUj_lEdWAbS:-MVHgxtBCSZNNRHI4rA8:b-ueli4c) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L25)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can we set both of those flags to 1? What will happen?
</blockquote></details>

discussed below (int other issue)
___
*[doc/libpmemkv.7.md, line 71 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGm-uZD78Ycfi9bQmO:-MVHh-xR1NbR-byn4EPf:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/libpmemkv.7.md#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[doc/libpmemkv_config.3.md.in, line 39 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGutpT54LriaeDQssM:-MVHhCasEWro-XpQORYV:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/libpmemkv_config.3.md.in#L39)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what about create_if_missing?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1532 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs43e69XXtj84mVkmy:-MVHhphp1UBJKYe5AaTI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1532)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

logic here is not necessary: (uint64_t)value
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1549 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs3kdQ4qyCTBX2LB9q:-MVHhtbZByFZefIT_KOg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1549)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

logic here is not necessary: (uint64_t)value
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1519 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGvvgu-kJHin8tMm1h:-MVHhG8qDoy1UN6G6gvg:bhh19ms) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1519)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

so maybe disallow setting both?
</blockquote></details>

I'm not sure. Per se, it's not an issue if someone sets them both up to true. On the other hand someone may be confused what's going on (if they set error_if_missing and it has no effect)...
___
*[src/libpmemkv.hpp, line 1522 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGw06B4bn2kYVU7SI1:-MVHhoJO7-UMdeFBS7hv:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1522)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

then?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1534 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGw6W70MJvvntIeZAS:-MVHhslKE8krqnoRlo9i:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1534)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[src/libpmemkv.cc, line 225 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs46BL5Xi-10PNK7hl:-MVHhuoBBAfST-yOs9Tz:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.cc#L225)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

logic here is not necessary: (uint64_t)value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-09 09:03 UTC, igchor requested changes
> Reviewed 1 of 12 files at r6, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 26 of 32 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[doc/ENGINES-experimental.md, line 22 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGla-VBcpeeoSetwrS:-MVLBtDL8On8qLCv-ZxF:b-nsmovc) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the default stays the same, since we set the new flag to 0 by default
</blockquote></details>

OK, but here you write "If 0, pmemkv uses **error_if_exists** flag to create/open the file." which is not the default behavior - using error_if_exists means creating the file, not opening it, right?
___
*[src/libpmemkv.hpp, line 1532 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs43e69XXtj84mVkmy:-MVLDE142HOjKFzlgI9W:b-ba3nca) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1532)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: static_cast
___
*[src/libpmemkv.hpp, line 1549 at r4](https://reviewable.io/reviews/pmem/pmemkv/944#-MUs3kdQ4qyCTBX2LB9q:-MVLDIw_96z5fvi7T7rI:b3kqx) ([raw file](https://github.com/pmem/pmemkv/blob/44f36dfec621f86f5a308b66550bf85918505fa2/src/libpmemkv.hpp#L1549)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[src/libpmemkv.hpp, line 1519 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGvvgu-kJHin8tMm1h:-MVLCdET89mzQtZkKgva:btpsfdt) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1519)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure. Per se, it's not an issue if someone sets them both up to true. On the other hand someone may be confused what's going on (if they set error_if_missing and it has no effect)...
</blockquote></details>

Hm, actually, I just looked more closely at the RocksDB API and it seems like the **require** setting both of those fields to create or fail if exists. We obviously cannot do the same thing since this would break compatibility so I'm thinking if it wouldn't be better to stay with force_create after all... (this way there would be no misuderstandings - using the same name as RocksDB with slighly different behavior might be misleading).

If we'd leave force_create then we could actually disallow using both flatgs at the same thime.


<!-- Sent from Reviewable.io -->

2021-03-09 13:31 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 27 of 32 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[doc/ENGINES-experimental.md, line 22 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGla-VBcpeeoSetwrS:-MVMASt37g8Opd26whJc:b-cgmkc2) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

OK, but here you write "If 0, pmemkv uses **error_if_exists** flag to create/open the file." which is not the default behavior - using error_if_exists means creating the file, not opening it, right?
</blockquote></details>

Maybe the sentence was unfortunate - I re-wrote it a little (only in one place for now) - pls see in libpmemkv.hpp if the wording is correct now. If it's ok - I'll copy it to other docs.
___
*[src/libpmemkv.hpp, line 1519 at r6](https://reviewable.io/reviews/pmem/pmemkv/944#-MVGvvgu-kJHin8tMm1h:-MVLxBXE8-a-cIiXIoOy:bwexbcw) ([raw file](https://github.com/pmem/pmemkv/blob/e5ed8c68e42e670259e6c4a054c49e0c26599e69/src/libpmemkv.hpp#L1519)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Or actually... Maybe we can do it in the same way as RockDB? We could just say that you **have** to specify both options to get force_create behavior?
</blockquote></details>

for now, only renamed the new flag to 'create_or_error_if_exists'


<!-- Sent from Reviewable.io -->

2021-03-15 15:08 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[ChangeLog, line 12 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVqPqmW9t01AszUFREz:-MVqPqmW9t01AszUFRF-:bu3ukpl) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/ChangeLog#L12)):*
> ```
> 
> 	Other changes:
> 	- Deprecate config's flag 'force_create' and add an alias: 'create_or_error_if_exists' (#576)
> ```

are the flags mutually exlusive?
btw, I wouldn't start a changelog entry that adds a new feature with the word "deprecate".
___
*[tests/engine_scenarios/all/open.cc, line 9 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVqQGff5XwK6X44N6ts:-MVqQGff5XwK6X44N6tt:b5zam3b) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/tests/engine_scenarios/all/open.cc#L9)):*
> ```cpp
>  * Tests for config flags.
>  * Setting both of them to control kv.open() should not fail in any engine.
>  * If engine supports them, one of them should be prioritzed, and the second one should be
> ```

does this mean that the behavior of setting both flags is essentially "random"?
This behavior should be defined explicitly.


<!-- Sent from Reviewable.io -->

2021-03-16 07:54 UTC, igchor requested changes
> Reviewed 5 of 23 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MVu-8qL0UuaygIURUtq:bqk9noj) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
> ```Markdown
> 	+ type: string
> * **create_if_missing** -- If 1, pmemkv tries to create the file and when that doesn't succeed it tries to open it.
> 	If 0, pmemkv uses **create_or_error_if_exists** flag to create/open the file.
> ```

Hm, this sentence is not entirely true. Maybe we should not write about `0` case here but just have one sentence after both flags are introduces which would say: "If both flags are 0 then pmemkv tries to open the file".?
___
*[doc/libpmemkv.7.md, line 70 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu0XkU3K41mlOGZkuu:-MVu0XkU3K41mlOGZkuv:b-dspoh0) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/libpmemkv.7.md#L70)):*
> ```Markdown
> * **path** -- Path to a database file or to a poolset file (see **poolset**(5) for details). Note that when using poolset file, size should be 0
> 	+ type: string
> * **create_if_missing** -- If 1, pmemkv tries to create the file and when that doesn't succeed it tries to open it.
> ```

Isn't the order (open and then create) reversed in the code?
___
*[src/libpmemkv.hpp, line 1518 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVtzO5S8_LOvH-x6KYV:-MVtzO5S8_LOvH-x6KYW:bkijq07) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/src/libpmemkv.hpp#L1518)):*
> ```cpp
> 
> /**
>  * Puts create_or_error_if_exists parameter to a config. This flag has lower priority than
> ```

Still, I think it would be simpler to just disallow setting both flags to `true`. You don;t need to write about priority then.
___
*[src/libpmemkv.hpp, line 1522 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVtzemm4wSqsG9_0O8r:-MVtzemm4wSqsG9_0O8s:bhljs8h) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/src/libpmemkv.hpp#L1522)):*
> ```cpp
>  * sense. It uses 'path' (as specified by e.g. config::put_path).
>  * Works only with engines supporting this flag and it means:
>  * If true: pmemkv creates the file, unless it exists - then it fails.
> ```

Should we use `pool` or something similar instead of a `file`? I think we use `pool` in some other places in the documentation.


<!-- Sent from Reviewable.io -->

2021-03-18 09:13 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MW3aZuR6a_qyP1Y2sNo:b-ygsx86) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, this sentence is not entirely true. Maybe we should not write about `0` case here but just have one sentence after both flags are introduces which would say: "If both flags are 0 then pmemkv tries to open the file".?
</blockquote></details>

Why not try to open the file first? And only if open is fail try to create if missing?


<!-- Sent from Reviewable.io -->

2021-03-19 13:35 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @vinser52)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MW9fdAFA1iJ8LFkBgMv:b-8cx1og) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why not try to open the file first? And only if open is fail try to create if missing?
</blockquote></details>

I think that's what happening in the code right now, my comment was that to make it consistent in the docs.


<!-- Sent from Reviewable.io -->

2021-03-25 11:56 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 20 of 32 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, @pbalcer, and @vinser52)

___
*[ChangeLog, line 12 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVqPqmW9t01AszUFREz:-MWZyO6E3rrnCpA5mXoG:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/ChangeLog#L12)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

are the flags mutually exlusive?
btw, I wouldn't start a changelog entry that adds a new feature with the word "deprecate".
</blockquote></details>

Done.
___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MW_p22t2h8KpH8k1GbA:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that's what happening in the code right now, my comment was that to make it consistent in the docs.
</blockquote></details>

Done.
___
*[doc/libpmemkv.7.md, line 70 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu0XkU3K41mlOGZkuu:-MW_irPRAIfzcMtF3qYi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/libpmemkv.7.md#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Isn't the order (open and then create) reversed in the code?
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1518 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVtzO5S8_LOvH-x6KYV:-MW_YE0N1qSRHrs0Js96:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/src/libpmemkv.hpp#L1518)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still, I think it would be simpler to just disallow setting both flags to `true`. You don;t need to write about priority then.
</blockquote></details>

Done.
___
*[src/libpmemkv.hpp, line 1522 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVtzemm4wSqsG9_0O8r:-MWZ2BQ9AtHBsJ18Yvlt:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/src/libpmemkv.hpp#L1522)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Should we use `pool` or something similar instead of a `file`? I think we use `pool` in some other places in the documentation.
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/open.cc, line 9 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVqQGff5XwK6X44N6ts:-MW_s-ur9Agtn1rJUxor:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/tests/engine_scenarios/all/open.cc#L9)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

does this mean that the behavior of setting both flags is essentially "random"?
This behavior should be defined explicitly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 12:12 UTC, igchor requested changes
> Reviewed 1 of 23 files at r4, 12 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @vinser52)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MWdF7ga4-AJcCDkObsM:b-fsst1e) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still I think this is not entierly true, if it's 0 then i either opens the pool or returns an error (if create_or_error_if_exists is set). I think having a sentence below saying that pmemkv opens the pool only when both of those flags are not set (set to false) would be more clear
___
*[tests/engine_scenarios/all/open.cc, line 14 at r9](https://reviewable.io/reviews/pmem/pmemkv/944#-MWdHlN3A2hApvzoPJe8:-MWdHlN45jhLDO1gC4_f:b-mhmqcj) ([raw file](https://github.com/pmem/pmemkv/blob/566a0ff523b92d82d04879ad45955bc46230e84a/tests/engine_scenarios/all/open.cc#L14)):*
> ```cpp
>  */
> 
> static void OpenWithCreateIfMissing(std::string path, std::string engine, size_t size,
> ```

I gues this test should be run for both existing pool and not existing one. Is this the case?
___
*[tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc, line 52 at r9](https://reviewable.io/reviews/pmem/pmemkv/944#-MWdI6snDEVkvD9cRI6W:-MWdI6snDEVkvD9cRI6X:b-kapdkr) ([raw file](https://github.com/pmem/pmemkv/blob/566a0ff523b92d82d04879ad45955bc46230e84a/tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc#L52)):*
> ```cpp
> 	ASSERT_STATUS(s, pmem::kv::status::OK);
> }
> ```

Is there a test for positive case? (creating not-existent pool with create_or_error_if_exists)


<!-- Sent from Reviewable.io -->

2021-03-25 13:05 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 30 of 32 files reviewed, 5 unresolved discussions (waiting on @igchor and @pbalcer)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MWdO_0ZEu_USBxiH6Pg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Still I think this is not entierly true, if it's 0 then i either opens the pool or returns an error (if create_or_error_if_exists is set). I think having a sentence below saying that pmemkv opens the pool only when both of those flags are not set (set to false) would be more clear
</blockquote></details>

Done.
___
*[tests/engine_scenarios/all/open.cc, line 14 at r9](https://reviewable.io/reviews/pmem/pmemkv/944#-MWdHlN3A2hApvzoPJe8:-MWdK_Jd3wFcYQxDXSQp:b-90yanz) ([raw file](https://github.com/pmem/pmemkv/blob/566a0ff523b92d82d04879ad45955bc46230e84a/tests/engine_scenarios/all/open.cc#L14)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I gues this test should be run for both existing pool and not existing one. Is this the case?
</blockquote></details>

See answer below for creating new pools.

For opening existing pool - it's tested in scenarios `all/open.cc`
___
*[tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc, line 52 at r9](https://reviewable.io/reviews/pmem/pmemkv/944#-MWdI6snDEVkvD9cRI6W:-MWdJP_FCmyNGkuLwl7d:b-5oee88) ([raw file](https://github.com/pmem/pmemkv/blob/566a0ff523b92d82d04879ad45955bc46230e84a/tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is there a test for positive case? (creating not-existent pool with create_or_error_if_exists)
</blockquote></details>

yes and no - we use both flags to create database for other tests, see:

- tests/engines/pmemobj_based/pmemobj/create_if_missing.cmake,
- tests/engines/pmemobj_based/pmemobj/put_get_std_map_create_or_error_if_exists.cmake

I was thinking this may be enough - it's not a unit test per se, but it is used. Pls let me know what you think.


<!-- Sent from Reviewable.io -->

2021-03-25 14:17 UTC, igchor requested changes
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @igchor, @pbalcer, and @vinser52)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MWdiVlpETfHmJi7uWkz:b-hymnyd) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is the same issue for create_or_error_if_missing I belive. However, I'm not sure if we want to add circular dependency ;d
___
*[tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc, line 52 at r9](https://reviewable.io/reviews/pmem/pmemkv/944#-MWdI6snDEVkvD9cRI6W:-MWdje3fCqki56f3A0b3:b-yrps1j) ([raw file](https://github.com/pmem/pmemkv/blob/566a0ff523b92d82d04879ad45955bc46230e84a/tests/engine_scenarios/pmemobj/create_or_error_if_exists.cc#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yes and no - we use both flags to create database for other tests, see:

- tests/engines/pmemobj_based/pmemobj/create_if_missing.cmake,
- tests/engines/pmemobj_based/pmemobj/put_get_std_map_create_or_error_if_exists.cmake

I was thinking this may be enough - it's not a unit test per se, but it is used. Pls let me know what you think.
</blockquote></details>

Ok, I think it's fine


<!-- Sent from Reviewable.io -->

2021-03-25 15:07 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: 30 of 32 files reviewed, 3 unresolved discussions (waiting on @igchor and @pbalcer)

___
*[doc/ENGINES-experimental.md, line 22 at r8](https://reviewable.io/reviews/pmem/pmemkv/944#-MVu-8qL0UuaygIURUtp:-MWdupdIBwm3fxq3bkZ-:bw8fw6h) ([raw file](https://github.com/pmem/pmemkv/blob/a7097e827618fa0b5408d77b7bc39b40e3d8f2dd/doc/ENGINES-experimental.md#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There is the same issue for create_or_error_if_missing I belive. However, I'm not sure if we want to add circular dependency ;d
</blockquote></details>

Hah, you're right. I was reading this top-to-bottom... Anyway, I've added another sentence, plus we have the extra description under the table in the manpage.


<!-- Sent from Reviewable.io -->

2021-03-26 12:00 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944#-:-MWiP1fS87K_WemxJHUx:bnfp4nl)* status: 30 of 32 files reviewed, 2 unresolved discussions (waiting on @igchor and @pbalcer)



<!-- Sent from Reviewable.io -->

2021-03-26 12:14 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[doc/ENGINES-experimental.md, line 125 at r11](https://reviewable.io/reviews/pmem/pmemkv/944#-MWiNrVhC0XPiPUBDOhk:-MWiNrViCcQLIkO4fAI_:b-7jzc99) ([raw file](https://github.com/pmem/pmemkv/blob/d7358b0bc2e1e28e026d6efc064653f4c329a292/doc/ENGINES-experimental.md#L125)):*
> ```Markdown
> 	+ type: string
> * **create_if_missing** -- If 1, pmemkv tries to open the pool and if that doesn't succeed, it creates it.
> 	If 0, pmemkv will rely on **create_or_error_if_exists** flag setting.
> ```

without "setting" sounds also good IMO, but it doesn't matter


<!-- Sent from Reviewable.io -->

2021-03-26 12:15 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/944#-:-MWiSOmJ-wLgKBOmegMJ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)



<!-- Sent from Reviewable.io -->

2021-03-29 11:10 UTC, merged