[Feature] Auto-registering engine factories
pmem/pmemkv pull request #980
Opened 2021-03-25 14:43 UTC by KFilipek

Previous registering mechanism forced developer to do changes in many places.
Auto-registering factory gives flexibility and the only developer's responsibility
is to implement factory interface and register in StorageEngineFactory.

2021-03-25 15:20 UTC, igchor reviewed
Looks good, I understand why you wanted to use the factory now. Having just a function instead of factory (std::function<unique_ptr<engine_base>(unique_ptr<config>)> would still be ok imo but this way is probably more readable.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980#-:-MWdxVaL0Ia0f6YPal28:b9sdpc4)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek)

___
*[src/engine.h, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWduLRc3ukNjDhKaDqH:-MWduLRc3ukNjDhKaDqI:bbxw0c1) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.h#L68)):*
> ```objc
>     public:
>         virtual std::unique_ptr<engine_base> create(std::unique_ptr<internal::config>) = 0;
>         virtual std::string getCanonicalName() = 0;
> ```

please name methods and classes with existing convention (snake_case)
___
*[src/engine.cc, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdunrl7jSargYghIxY:-MWdunrl7jSargYghIxZ:byak8e) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.cc#L26)):*
> ```cpp
> }
> 
> bool StorageEngineFactory::Register(const std::string name, StorageEngineFactory::TCreateMethod factory) {
> ```

you can implement this function in a simpler way:

```
return pairs.emplace(name, std::move(factory)).second;
```
___
*[src/engine.cc, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWduwK24hgpV_va9WYa:-MWduwK24hgpV_va9WYb:b-ldpocg) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.cc#L26)):*
> ```cpp
> }
> 
> bool StorageEngineFactory::Register(const std::string name, StorageEngineFactory::TCreateMethod factory) {
> ```

`const std::string& name`?
___
*[src/engines/blackhole.h, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdv5E18UXtLgfA0yR0:-MWdv5E18UXtLgfA0yR1:b-pk35aa) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L51)):*
> ```objc
> 
> private:
> 	static bool is_registered;
> ```

what is this needed for?
___
*[src/engines/blackhole.h, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdvftc6t4mdnXBcEPJ:-MWdvftc6t4mdnXBcEPK:b-gp9j3r) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L68)):*
> ```objc
> class BlackholeFactory : public engine_base::IFactory {
> public:
> 	virtual std::unique_ptr<engine_base> create(std::unique_ptr<internal::config> cfg) {
> ```

please replace `virtual` with `final` or `override` - this way compiler can tell you if you have some mispell in the name for example: https://en.cppreference.com/w/cpp/language/override 
___
*[src/engines/blackhole.h, line 71 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdvSo7-kiAzrE0seeg:-MWdvSo7-kiAzrE0seeh:b-idx9bi) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L71)):*
> ```objc
> 		return std::unique_ptr<engine_base>(new blackhole(std::move(cfg)));
> 	};
> 	virtual std::string getCanonicalName() {
> ```

is this used anywhere?


<!-- Sent from Reviewable.io -->

2021-03-26 10:41 UTC, KFilipek reviewed
> Reviewed 24 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[src/engine.h, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWduLRc3ukNjDhKaDqH:-MWhuW5gDmSTy8Sv5EfT:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.h#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please name methods and classes with existing convention (snake_case)
</blockquote></details>

Done.
___
*[src/engine.cc, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdunrl7jSargYghIxY:-MWi5lrP1STLXITzBBR9:bfnk0da) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.cc#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you can implement this function in a simpler way:

```
return pairs.emplace(name, std::move(factory)).second;
```
</blockquote></details>

Done. Good point, thanks!
___
*[src/engine.cc, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWduwK24hgpV_va9WYa:-MWi5p3s5F3VoqpPVYEK:bwymhq5) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engine.cc#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const std::string& name`?
</blockquote></details>

Not necessary
___
*[src/engines/blackhole.h, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdv5E18UXtLgfA0yR0:-MWi5rEo6OcCXicXgWFW:b-bl27w9) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L51)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is this needed for?
</blockquote></details>

To avoid optimization global object that is not used anywhere (while registering engine)
___
*[src/engines/blackhole.h, line 68 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdvftc6t4mdnXBcEPJ:-MWi60W1D1yNFbFTBEqL:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please replace `virtual` with `final` or `override` - this way compiler can tell you if you have some mispell in the name for example: https://en.cppreference.com/w/cpp/language/override 
</blockquote></details>

Done.
___
*[src/engines/blackhole.h, line 71 at r1](https://reviewable.io/reviews/pmem/pmemkv/980#-MWdvSo7-kiAzrE0seeg:-MWi6s8K54LVpYMlEypZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/f73d67beddbc88167b38d130c13359b542fb31db/src/engines/blackhole.h#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

is this used anywhere?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 12:13 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 3 of 24 files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQoyz3zdyYGqlRno-:-MWiQoyz3zdyYGqlRno0:b-nxzfhq) (no related file):*
pls update CONTRIBUTING.md

---
___
*[src/engine.h, line 7 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQVEC7zSK2uXIhzRC:-MWiQVEC7zSK2uXIhzRD:btdc0t4) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.h#L7)):*
> ```objc
> #define LIBPMEMKV_ENGINE_H
> 
> #include <functional>
> ```

do we need this header?
___
*[src/engine.h, line 79 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQ_BQBmTXaODHI2D4:-MWiQ_BQBmTXaODHI2D5:b-x4xtn9) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.h#L79)):*
> ```objc
> 
> 	storage_engine_factory() = delete;
> 	static bool Register(factory_object factory);
> ```

`register` and `create` (lowercase)
___
*[src/engine.cc, line 6 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQdE85W1y2OJ72pKG:-MWiQdE85W1y2OJ72pKH:bb7dsoj) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L6)):*
> ```cpp
> #include "engine.h"
> 
> // #include "engines/blackhole.h"
> ```

boop
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWiRTYjAQUvnk4gLHX2:bau12mg) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
> ```cpp
> 
> std::unique_ptr<engine_base>
> storage_engine_factory::Create(const std::string &name,
> ```

perhaps make `name` the second parameter, if we (someday) want to move engine name into config; this way we could make `name` a default param.. I guess...?


<!-- Sent from Reviewable.io -->

2021-03-26 13:12 UTC, KFilipek reviewed
> Reviewed 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 21 of 25 files reviewed, 11 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQoyz3zdyYGqlRno-:-MWieQVrD4kdRDAU4v2M:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update CONTRIBUTING.md
</blockquote></details>

Done.

---
___
*[src/engine.h, line 7 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQVEC7zSK2uXIhzRC:-MWibIP90k0ph9O4woJ0:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.h#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this header?
</blockquote></details>

Done.
___
*[src/engine.h, line 79 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQ_BQBmTXaODHI2D4:-MWibK4d-9-aOOlSMjDK:bx73vcn) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.h#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`register` and `create` (lowercase)
</blockquote></details>

It's not possible in C++, register is a keyword.
___
*[src/engine.cc, line 6 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQdE85W1y2OJ72pKG:-MWic34a7--p1Egye6ti:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

boop
</blockquote></details>

Done.
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWibZyS3CjhSjeVPn9O:b-i1f047) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make `name` the second parameter, if we (someday) want to move engine name into config; this way we could make `name` a default param.. I guess...?
</blockquote></details>

Then it will be changed as part of the PR


<!-- Sent from Reviewable.io -->

2021-03-26 15:19 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 11 of 25 files reviewed, 10 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[CONTRIBUTING.md, line 131 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj4EAU4evozq-XKYO_:-MWj4EAVCeHRZHBHUZ7I:b-gk5vwg) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/CONTRIBUTING.md#L131)):*
> ```Markdown
> * Use `pmem::kv` namespace defined by the header
> * implement engine interface with its factory
> * register engine factory (e.g. look at the blackhole)
> ```

I'd say you could be more specific:
- either put here exactly what to do,
- or add a short comment within blackhole engine what has to be done, to register engine factory
___
*[CONTRIBUTING.md, line 152 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj3DyA0m1dbyR3PZQc:-MWj3DyA0m1dbyR3PZQd:bl0e4ne) ([raw file](https://github.com/pmem/pmemkv/blob/d68886399e6a7dc0738ad18afe9a60e35d5b9c6a/CONTRIBUTING.md#L152)):*
> ```Markdown
>     * Add a build option for a new engine with a name like `ENGINE_MYTREE`
>     and use it to ifdef all includes, dependencies and linking you may add
>     * Add definition of the new option, like `-DENGINE_MYTREE`, so it can
> ```

if you believe we don't need these definitions, then pls remove them (for current engines) from the top-level CMake
___
*[CONTRIBUTING.md, line 182 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj3nzv18TNjWRQaPdX:-MWj3nzv18TNjWRQaPdY:b-3rghuu) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/CONTRIBUTING.md#L182)):*
> ```Markdown
> experimental source files should be placed.
> 
> Whole engine-specific code (located in common source files) should be ifdef'd out using
> ```

rm this as well
___
*[src/engine.h, line 79 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiQ_BQBmTXaODHI2D4:-MWj5XUd7SDvmad85G7f:b-8fx2u7) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.h#L79)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's not possible in C++, register is a keyword.
</blockquote></details>

:+1: 
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWj5olK575kziV56r-Q:b3xmdbt) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Then it will be changed as part of the PR
</blockquote></details>

but, you'll have more changes to do then (you'll have to update all future engines, we'll add) ;)


<!-- Sent from Reviewable.io -->

2021-03-26 17:30 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 11 of 25 files reviewed, 11 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/engine.h, line 63 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjJf311EHwX8LsYDGB:-MWjJf311EHwX8LsYDGC:bwj4whu) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/src/engine.h#L63)):*
> ```objc
> 	virtual iterator *new_const_iterator();
> 
> 	class factory_base {
> ```

You would probably hate me for this, but... ;)

Probably engine_base::factory_base may be a template.
so instead of creating this boilerplate class in every engine you may just: 

```
using cmap_factory = engine_base::factory_base<cmap>
```
and register it the same way, as currently 

Optionally with second template parameter `check_config_null' by default set to true.  

```
using blackhole_factory = engine_base_factory_base<blackhole, false>
```

Template implementation of `get_name()` would be something like:
```
std::string get_name()
{
       return typeid(T).name();
}
```

https://en.cppreference.com/w/cpp/language/typeid
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWjEpj--ejpcW64VjOp:btbmdc0) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but, you'll have more changes to do then (you'll have to update all future engines, we'll add) ;)
</blockquote></details>

I agree with @kfilipek. Mostly, because I don't believe we move engine name to config :) 


<!-- Sent from Reviewable.io -->

2021-03-26 18:46 UTC, KFilipek reviewed
> Reviewed 14 of 14 files at r4, 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 15 of 26 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 131 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj4EAU4evozq-XKYO_:-MWjTh_T1_Dh63lIp6Bi:bxf6gzf) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/CONTRIBUTING.md#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd say you could be more specific:
- either put here exactly what to do,
- or add a short comment within blackhole engine what has to be done, to register engine factory
</blockquote></details>

I'd always prefer code documentation and I will follow this way, so I choose the second option. I've added short commentary for meaningful classes/interfaces.
___
*[CONTRIBUTING.md, line 152 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj3DyA0m1dbyR3PZQc:-MWjXIkd8VTbtuThfQmP:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d68886399e6a7dc0738ad18afe9a60e35d5b9c6a/CONTRIBUTING.md#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you believe we don't need these definitions, then pls remove them (for current engines) from the top-level CMake
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 182 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWj3nzv18TNjWRQaPdX:-MWjmbtrANW8jb54Nlqi:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/CONTRIBUTING.md#L182)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rm this as well
</blockquote></details>

Done.
___
*[src/engine.h, line 63 at r4](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjJf311EHwX8LsYDGB:-MWjmqwEEpHq-3YIh1Py:bu80sha) ([raw file](https://github.com/pmem/pmemkv/blob/a4d4d632e4823e1a7065d951a07b93c5fdca7f8d/src/engine.h#L63)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You would probably hate me for this, but... ;)

Probably engine_base::factory_base may be a template.
so instead of creating this boilerplate class in every engine you may just: 

```
using cmap_factory = engine_base::factory_base<cmap>
```
and register it the same way, as currently 

Optionally with second template parameter `check_config_null' by default set to true.  

```
using blackhole_factory = engine_base_factory_base<blackhole, false>
```

Template implementation of `get_name()` would be something like:
```
std::string get_name()
{
       return typeid(T).name();
}
```

https://en.cppreference.com/w/cpp/language/typeid

</blockquote></details>

No hate here, it's a good point, but factory can handle additional specific logic before trying to create engine object. I'm not sure that typeid(T).name() will work for templated engines (vsmap?). 
Also this will generate additional numbers when you're using polymorphism.
"using" is just sugar:

```
class UnknownClass {
};

using AnotherClass = UnknownClass;

int main() {
    std::cout << typeid(UnknownClass).name() << std::endl;
    std::cout << typeid(AnotherClass).name() << std::endl;
}
```
will produce following output:
```
12UnknownClass
12UnknownClass
```
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWjqjQqBQ5LqpC0rDmu:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I agree with @kfilipek. Mostly, because I don't believe we move engine name to config :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 19:19 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 15 of 26 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWjwIuw3jiMHdM9h-p2:b-irljcw) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
> ```CMake
> # ----------------------------------------------------------------- #
> if(ENGINE_CMAP)
> 	add_definitions(-DENGINE_CMAP)
> ```

and what about these two definitions? :D

and pls update the "name" of this section (the comment above)
___
*[src/engine.h, line 87 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjyDzuAm3qfXHwXXR7:-MWjyDzvE-tvwZXy3GsD:b2aak5n) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.h#L87)):*
> ```objc
> /**
>  * storage_engine_factory is a class for handling auto-registering factories.
>  * Provides simply in use mechanism for factory registration without creating
> ```

`simple to use`
___
*[src/engine.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv/980#-MWiRTYjAQUvnk4gLHX1:-MWjxbyWBzQWMzL_RORC:b-3eu5wg) ([raw file](https://github.com/pmem/pmemkv/blob/6dd8a649cc8cd507f6ff4e4cc22ad4e5cc1f8520/src/engine.cc#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

just hold my beer for a moment... :D


<!-- Sent from Reviewable.io -->

2021-03-29 10:38 UTC, igchor requested changes
> Reviewed 3 of 14 files at r4, 11 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 16 of 24 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[CMakeLists.txt, line 179 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxWbCJ3TfkABfPUyvc:-MWxWbCJ3TfkABfPUyvd:b-fvor7f) ([raw file](https://github.com/pmem/pmemkv/blob/d68886399e6a7dc0738ad18afe9a60e35d5b9c6a/CMakeLists.txt#L179)):*
> ```CMake
> endif()
> if(ENGINE_VCMAP)
> 	add_definitions(-DENGINE_VCMAP)
> ```

those definitions are also used in tests/wrong_engine_name_test.cc, if you want to remove those, we would need to somehow change that test
___
*[src/engine.h, line 92 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxUHQS0Mfuw_EAynTI:-MWxUHQTBz_OrcKW7oHo:b78uvr6) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.h#L92)):*
> ```objc
> class storage_engine_factory {
> public:
> 	using factory_object = std::unique_ptr<engine_base::factory_base>;
> ```

it's more common to name type names with _type suffix, e.g. `factory_type = ...`, Using `object` in type name is a bit misleading.
___
*[src/engine.h, line 104 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxYxya5QIV0_6AHWRt:-MWxYxya5QIV0_6AHWRu:b-qp8dkx) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.h#L104)):*
> ```objc
> };
> 
> class factory_registerer {
> ```

Please add comment with info from C++ standard why registering engines this way (as static variables) is safe.
___
*[src/engine.cc, line 12 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxYQos-2WP9miIqwnA:-MWxYQotCQQofPeN5xhN:bwn7pew) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.cc#L12)):*
> ```cpp
> 
> std::map<std::string, storage_engine_factory::factory_object> &
> storage_engine_factory::get_pairs()
> ```

The name of this function is too generic imo. Maybe something like `get_engine_factories`?
___
*[src/engine.cc, line 44 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxVeJMANn1IQeWGDDY:-MWxVeJMANn1IQeWGDDZ:b-s1w4an) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.cc#L44)):*
> ```cpp
> 		result += entry.first + separator;
> 	}
> 	return result.erase(result.rfind(separator), separator.length());
> ```

will this work if there are no engines? (if not, maybe add some assert?)
___
*[src/engines/cmap.h, line 97 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxV1PvBV1mZVmFZaXE:-MWxV1PvBV1mZVmFZaXF:b3kre) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engines/cmap.h#L97)):*
> ```objc
> private:
> 	void Recover();
>     internal::cmap::map_t *container;
> ```

?


<!-- Sent from Reviewable.io -->

2021-03-29 10:38 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 16 of 24 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWxYkv2E6flS69UoLjz:bqy1b6w) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and what about these two definitions? :D

and pls update the "name" of this section (the comment above)
</blockquote></details>

One thing I missed, this definitions are only used in tests, I will try to remove some of them if it's possible. E.g. wrong_engine_name_test.cc will be easy to change.


<!-- Sent from Reviewable.io -->

2021-03-29 12:00 UTC, KFilipek reviewed
> Reviewed 1 of 12 files at r5, 9 of 10 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[src/engine.h, line 87 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjyDzuAm3qfXHwXXR7:-MWxaIEnCB6hPa8z4bGq:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.h#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`simple to use`
</blockquote></details>

Done.
___
*[src/engine.h, line 104 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxYxya5QIV0_6AHWRt:-MWxox4s2KINaFPJBhgh:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.h#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add comment with info from C++ standard why registering engines this way (as static variables) is safe.
</blockquote></details>

Done.
___
*[src/engine.cc, line 12 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxYQos-2WP9miIqwnA:-MWxpZJ79dWQ3amy5MZS:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.cc#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The name of this function is too generic imo. Maybe something like `get_engine_factories`?
</blockquote></details>

Done.
___
*[src/engine.cc, line 44 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxVeJMANn1IQeWGDDY:-MWxqP6W-PqlX-pD44P3:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engine.cc#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

will this work if there are no engines? (if not, maybe add some assert?)
</blockquote></details>

Done.
___
*[src/engines/cmap.h, line 97 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxV1PvBV1mZVmFZaXE:-MWxqYfzAHeKs0UcIr7S:bgftf8n) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engines/cmap.h#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Nie rozumiem pytania


<!-- Sent from Reviewable.io -->

2021-03-29 12:29 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines/cmap.h, line 97 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxV1PvBV1mZVmFZaXE:-MWxwnaf7wrJGQEuEEji:beq3ccp) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engines/cmap.h#L97)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Nie rozumiem pytania
</blockquote></details>

Why this line was changed?


<!-- Sent from Reviewable.io -->

2021-03-29 12:30 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWxxYHGAV6JmqY9Svup:b-ec4djr) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

One thing I missed, this definitions are only used in tests, I will try to remove some of them if it's possible. E.g. wrong_engine_name_test.cc will be easy to change.
</blockquote></details>

ok, pls do


<!-- Sent from Reviewable.io -->

2021-03-29 12:43 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWy-UFj7_OsGUnwv5hP:baft9go) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, pls do
</blockquote></details>

Done. I've discussed with Igor that this change will be quite tricky and will be estimated separately.
___
*[src/engines/cmap.h, line 97 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWxV1PvBV1mZVmFZaXE:-MWy-g7g2zDJcQp6zdOp:b-vuyktq) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/src/engines/cmap.h#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why this line was changed?
</blockquote></details>

Changed to original, formatting issues.


<!-- Sent from Reviewable.io -->

2021-03-29 13:11 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWy65RJ9rYfo7bDQHeQ:byf4qmx) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. I've discussed with Igor that this change will be quite tricky and will be estimated separately.
</blockquote></details>

then update CONTRIBUTING.md pls


<!-- Sent from Reviewable.io -->

2021-03-29 13:13 UTC, KFilipek commented
Why? New engine can be written without macros, but purpose of future
changes is to adjust current code to the new behavior.

On Mon, Mar 29, 2021, 15:12 Łukasz Stolarczuk ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> *Reviewable <https://reviewable.io/reviews/pmem/pmemkv/980>* status: all
> files reviewed, 2 unresolved discussions (waiting on @karczex
> <https://github.com/karczex> and @KFilipek <https://github.com/KFilipek>)
>
> ------------------------------
>
> *CMakeLists.txt, line 163 at r5
> <https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWy65RJ9rYfo7bDQHeQ:byf4qmx>
> (raw file
> <https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163>):*
> *Previously, KFilipek (Krzysztof Filipek) wrote…*
>
> Done. I've discussed with Igor that this change will be quite tricky and
> will be estimated separately.
>
> then update CONTRIBUTING.md pls
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pmem/pmemkv/pull/980#pullrequestreview-623210937>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3DKKCDWK3RFMD4EQ2BMFLTGCDDPANCNFSM4ZZP2TXQ>
> .
>

2021-03-29 14:06 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-29 15:45 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWydDrw6JDW8CfIRlwF:b-9j9x91) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
> Why? New engine can be written without macros, but purpose of future changes is to adjust current code to the new behavior.

I'll answer you the same you did to me - then it will be changed in the new PR ;)

Right now we require these macros for tests to work.


<!-- Sent from Reviewable.io -->

2021-03-29 16:35 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MWyp8ZBALe3SGGXkPGZ:bel2sbl) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> Why? New engine can be written without macros, but purpose of future changes is to adjust current code to the new behavior.

I'll answer you the same you did to me - then it will be changed in the new PR ;)

Right now we require these macros for tests to work.
</blockquote></details>

Please review latest changes


<!-- Sent from Reviewable.io -->

2021-03-30 06:38 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MX0qVxU71J9mZiwzELs:b-qzjz89) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Please review latest changes
</blockquote></details>

hmm either you forgot to push some changes or Reviewable is messing with us ;)


<!-- Sent from Reviewable.io -->

2021-03-30 11:31 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MX1tYEVEW9SpiPD01yF:bbdqfbe) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm either you forgot to push some changes or Reviewable is messing with us ;)
</blockquote></details>

Done. I've reverted change in CONTRIBUTING.md, but I've removed part related with engine.cc which we currently don't touch :)


<!-- Sent from Reviewable.io -->

2021-03-30 11:33 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-03-30 15:12 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 21 files at r3, 11 of 14 files at r4, 1 of 12 files at r5, 8 of 10 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[CMakeLists.txt, line 163 at r5](https://reviewable.io/reviews/pmem/pmemkv/980#-MWjwIuvC5D0oCmmX0gA:-MX2RQwB3zBgN4zMXeHR:b-tzy9em) ([raw file](https://github.com/pmem/pmemkv/blob/d39247df783f12e43c656848af729c0f0b5a6f46/CMakeLists.txt#L163)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. I've reverted change in CONTRIBUTING.md, but I've removed part related with engine.cc which we currently don't touch :)
</blockquote></details>

looks good, thx
___
*[src/engine.h, line 108 at r8](https://reviewable.io/reviews/pmem/pmemkv/980#-MX2VuhIEIyeBk-OqD4E:-MX2VuhIEIyeBk-OqD4F:b-rxqmsy) ([raw file](https://github.com/pmem/pmemkv/blob/95fe534a667eb14fcd273fed7d3e15d9cd1dfece/src/engine.h#L108)):*
> ```objc
>  * despite optimization level due to [basic.stc.static]:
>  * "If a variable with static storage duration has initialization or a destructor
>  * with side effects, it shall not beeliminated even if it appears to be unused".
> ```

`be eliminated`


<!-- Sent from Reviewable.io -->

2021-03-30 21:47 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/engine.h, line 108 at r8](https://reviewable.io/reviews/pmem/pmemkv/980#-MX2VuhIEIyeBk-OqD4E:-MX45iF3EdKm3E4fzv_c:b4erz3z) ([raw file](https://github.com/pmem/pmemkv/blob/95fe534a667eb14fcd273fed7d3e15d9cd1dfece/src/engine.h#L108)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`be eliminated`
</blockquote></details>

Done. Thanks, I missed it somehow


<!-- Sent from Reviewable.io -->

2021-03-31 11:47 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/980#-:-MX75vfDBQg1Di7aY9ZE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-31 11:53 UTC, merged