Remove duplicate code from engine implementation
pmem/pmemkv pull request #982
Opened 2021-03-30 13:29 UTC by KFilipek

- Remove duplicated code in engine implementation
- Small code fixes: unused variables, unnecessary virtual inheritance

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv/982)

2021-03-30 15:33 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[src/engine.cc, line 261 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2hbgh6_J_yJptooxy:-MX2hbgh6_J_yJptooxz:b-6livst) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engine.cc#L261)):*
> ```cpp
> namespace internal
> {
> std::string get_path(internal::config &cfg)
> ```

perhaps we could also use these methods in pmemobj_engine...?
___
*[src/engines/vsmap.cc, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2kpe80rqbO9X376BV:-MX2kpe80rqbO9X376BW:b-4b7a1f) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engines/vsmap.cc#L23)):*
> ```cpp
> 
> /**
>  * XXX(kfilipek): when C++14 bump then change definition to:
> ```

this comment and fix definition of the function was added in the wrong commit (in the second one, instead of the first one, see: https://github.com/pmem/pmemkv/commit/a36c25d6b040f0ac78e299e9dfad773a1db674c1#diff-204b2e3b93ca274f4ebbf33c02d95d8991770bf0be43533e68a891b33e749e4a)
___
*[src/engines/vsmap.cc, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2jk5j4BrmjyxHn8P2:-MX2jk5k3eHlGAVfIkRZ:b-gixt9s) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engines/vsmap.cc#L27)):*
> ```cpp
>  */
> template <typename T, typename T2>
> std::size_t count_iterations(T it, T2 end)
> ```

T2 == T ?


<!-- Sent from Reviewable.io -->

2021-03-30 21:44 UTC, KFilipek reviewed
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[src/engine.cc, line 261 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2hbgh6_J_yJptooxy:-MX44AfD71ZEWjPeUy9I:b-j58r08) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engine.cc#L261)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps we could also use these methods in pmemobj_engine...?
</blockquote></details>

Path is splitted around implementation, so it would require more changes. I tried to change is_size+size to simplify a bit.
If you have idea how change it I'm open for your suggestion.
___
*[src/engines/vsmap.cc, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2kpe80rqbO9X376BV:-MX3lMQw04VHKyIOYIVN:b-px1vv5) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engines/vsmap.cc#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this comment and fix definition of the function was added in the wrong commit (in the second one, instead of the first one, see: https://github.com/pmem/pmemkv/commit/a36c25d6b040f0ac78e299e9dfad773a1db674c1#diff-204b2e3b93ca274f4ebbf33c02d95d8991770bf0be43533e68a891b33e749e4a)
</blockquote></details>

Done. Now should be ok
___
*[src/engines/vsmap.cc, line 27 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2jk5j4BrmjyxHn8P2:-MX3kgIA6rnrz2GfEVmj:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engines/vsmap.cc#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

T2 == T ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 08:44 UTC, igchor requested changes
> Reviewed 3 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[src/engine.h, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6NzIa9isdPPiDM-FP:-MX6NzIa9isdPPiDM-FQ:b-5msf58) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engine.h#L71)):*
> ```objc
> namespace internal
> {
> uint64_t get_size(internal::config &cfg);
> ```

Why not just move those functions to config class (and maybe rename them to something like get_size_or_fail)?

Alternatively, we could also make those functions a bit more generic. Maybe instead of having specialized get_size/get_path functions we could just create a new method within config class (a wrapper around get_*())?


```
void get_string_or_fail(const std::string& name) {
	const char *val;
	if (!cfg.get_string(name, &val))
		throw internal::invalid_argument(
			"Config does not contain item with key:  " + name);
	return std::string(val);
}

...
```
___
*[src/pmemobj_engine.h, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6OQM313pDASKG8iiX:-MX6OQM313pDASKG8iiY:b-f4s5gw) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/pmemobj_engine.h#L84)):*
> ```objc
> 			}
> 
> 			root_oid = static_cast<pmem::obj::pool<Root>>(pmpool)
> ```

this cast is not necessary
___
*[src/engines/vsmap.cc, line 23 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6QmgC3VO7Yg3Havf1:-MX6QmgC3VO7Yg3Havf2:b-uv58zm) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L23)):*
> ```cpp
> 
> /**
>  * XXX(kfilipek): when C++14 bump then change definition to:
> ```

why you want to make count_iterations a lambda?
___
*[src/engines/vsmap.cc, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6Q5-HCfWuQl5cmaH5:-MX6Q5-HCfWuQl5cmaH6:b-wu2zdw) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L27)):*
> ```cpp
>  */
> template <typename T>
> std::size_t count_iterations(T &it, T &end)
> ```

Maybe also use this in another places not to duplicate code, e.g. instead of this: https://github.com/pmem/pmemkv/blob/master/src/engines-experimental/radix.cc#L86 and https://github.com/pmem/pmemkv/blob/master/src/engines-experimental/csmap.cc#L39. Or the other way around, use size() from radix_tree instead of count_iterations.


<!-- Sent from Reviewable.io -->

2021-03-31 09:12 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek)

___
*[src/engine.cc, line 261 at r1](https://reviewable.io/reviews/pmem/pmemkv/982#-MX2hbgh6_J_yJptooxy:-MX6XAXbDs8B6y0w_3Kz:b-heceim) ([raw file](https://github.com/pmem/pmemkv/blob/a36c25d6b040f0ac78e299e9dfad773a1db674c1/src/engine.cc#L261)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Path is splitted around implementation, so it would require more changes. I tried to change is_size+size to simplify a bit.
If you have idea how change it I'm open for your suggestion.
</blockquote></details>

yeah, right, we can't easily/cleanly use this for path, I guess...

beside that, I like the change, thx


<!-- Sent from Reviewable.io -->

2021-03-31 13:33 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[src/engine.h, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6NzIa9isdPPiDM-FP:-MX7EQ1d409_3wE0smKW:bxuvp29) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engine.h#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why not just move those functions to config class (and maybe rename them to something like get_size_or_fail)?

Alternatively, we could also make those functions a bit more generic. Maybe instead of having specialized get_size/get_path functions we could just create a new method within config class (a wrapper around get_*())?


```
void get_string_or_fail(const std::string& name) {
	const char *val;
	if (!cfg.get_string(name, &val))
		throw internal::invalid_argument(
			"Config does not contain item with key:  " + name);
	return std::string(val);
}

...
```
</blockquote></details>

Done. As we talked earlier, we should discuss more deeply together.
___
*[src/pmemobj_engine.h, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6OQM313pDASKG8iiX:-MX6ijjX-GZ6n7cIW4qj:bekkrfw) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/pmemobj_engine.h#L84)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this cast is not necessary
</blockquote></details>

Done. It's necessary, pool_base doesn't have root() method, so I need to cast to proper class<Root> and then access this method
___
*[src/engines/vsmap.cc, line 23 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6QmgC3VO7Yg3Havf1:-MX6u2fX2Tdp3KqH7Wf-:b-yi9tf4) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why you want to make count_iterations a lambda?
</blockquote></details>

You cannot define explicit following function:
```
auto fun(auto number) {
    return number * 2;
}
```
I know, template<typename T> does the job, but auto in lambda IMO is more readable.


<!-- Sent from Reviewable.io -->

2021-04-01 07:00 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r3, 1 of 2 files at r5, 7 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/config.h, line 166 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXB8GblC3hlpcIS9kqx:-MXB8GbmCzUds-ndcWU8:b-esfdns) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/config.h#L166)):*
> ```objc
> 	 * @throw pmem::kv::internal::error if item does not exist
> 	 */
> 	void remove(const char *key)
> ```

are we using this method anywhere? perhaps it should be removed
___
*[src/engines/blackhole.cc, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBCrNO5v8A5zDZqe4F:-MXBCrNPEzXYmjHD0MjZ:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/engines/blackhole.cc#L5)):*
> ```cpp
> 
> #include "blackhole.h"
> ```

redundant empty line
___
*[src/engines/vsmap.cc, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6Q5-HCfWuQl5cmaH5:-MXBDkHJ78Vw6mmzpqOW:bg48r99) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe also use this in another places not to duplicate code, e.g. instead of this: https://github.com/pmem/pmemkv/blob/master/src/engines-experimental/radix.cc#L86 and https://github.com/pmem/pmemkv/blob/master/src/engines-experimental/csmap.cc#L39. Or the other way around, use size() from radix_tree instead of count_iterations.
</blockquote></details>

and what about these?


<!-- Sent from Reviewable.io -->

2021-04-01 07:17 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/engine.h, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6NzIa9isdPPiDM-FP:-MXBHL3rCOeNmSG0D-xK:b1f3ull) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engine.h#L71)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. As we talked earlier, we should discuss more deeply together.
</blockquote></details>

Didn't we agree to move those functions to config class?
___
*[src/engines/vsmap.cc, line 23 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6QmgC3VO7Yg3Havf1:-MXBHT6NDQsYFOeM6OF5:btg286s) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L23)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You cannot define explicit following function:
```
auto fun(auto number) {
    return number * 2;
}
```
I know, template<typename T> does the job, but auto in lambda IMO is more readable.
</blockquote></details>

Imho it's better to use templated functions at the global/namespace level. One reason is that you cannot overload lambdas (for example, some iterators might have some more optimal implementation.


<!-- Sent from Reviewable.io -->

2021-04-01 10:25 UTC, igchor requested changes
> Reviewed 1 of 2 files at r5, 1 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines/cmap.h, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBxoEQ-mIaWKHrIspl:-MXBxoER8OAjxklyAMVA:bt9kwim) ([raw file](https://github.com/pmem/pmemkv/blob/63948c0ef2b1cd9c39341be3968b049974f8f5a9/src/engines/cmap.h#L101)):*
> ```objc
> 
> template <>
> class cmap::cmap_iterator<true> : virtual public internal::iterator_base {
> ```

You can apply the same fix for experimental engines


<!-- Sent from Reviewable.io -->

2021-04-01 14:15 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r5, 5 of 9 files at r6, 8 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[src/config.h, line 166 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXB8GblC3hlpcIS9kqx:-MXBMcfE1tmLzPMu-Zx1:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/config.h#L166)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are we using this method anywhere? perhaps it should be removed
</blockquote></details>

Done.
___
*[src/engine.h, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6NzIa9isdPPiDM-FP:-MXBQbBT5qWD5U_HOyyZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engine.h#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Didn't we agree to move those functions to config class?
</blockquote></details>

Done.
___
*[src/engines/blackhole.cc, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBCrNO5v8A5zDZqe4F:-MXCmEyp-cxfh95KUxGk:b-b3v5ts) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/engines/blackhole.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done. Right, thanks
___
*[src/engines/vsmap.cc, line 23 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6QmgC3VO7Yg3Havf1:-MXBQsMX7xzjzPLYR1lE:b-9yy7en) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Imho it's better to use templated functions at the global/namespace level. One reason is that you cannot overload lambdas (for example, some iterators might have some more optimal implementation.
</blockquote></details>

Right, done.
___
*[src/engines/vsmap.cc, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6Q5-HCfWuQl5cmaH5:-MXCm1-G6raW21GQnN3P:b-xa4agp) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and what about these?
</blockquote></details>

Done. I left it for today and it's finally works


<!-- Sent from Reviewable.io -->

2021-04-02 07:54 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 9 files at r7, 4 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 14 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGZ8UzC5i4kmTi6PFK:-MXGZ8UzC5i4kmTi6PFL:bhg1dtn) (no related file):*
you'll hate this, but commits are a bit messy now (except for the last one)

e.g.
`pmemobj_engine: code duplication remove and cleanup` commit touches config file as well
get_* methods are touched in commit no. 1 and no. 3
etc.

I believe you could start from scratch, remove all commits and add changes line by line (`git commit -p` if I remember correctly) 

---
___
*[src/config.h, line 166 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXB8GblC3hlpcIS9kqx:-MXGQ-ft22hk2tNtUUdK:b-hndcz9) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/config.h#L166)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done?
___
*[src/iterator.h, line 4 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUcKjElatm6mWYpjM:-MXGUcKjElatm6mWYpjN:b-6rnrpk) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L4)):*
> ```objc
> /* Copyright 2020-2021, Intel Corporation */
> 
> #pragma once
> ```

why these changes from guard headers to pragma? If there's some advantage of pragma over guards, then perhaps we should update it everywhere
___
*[src/iterator.h, line 57 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGS1vq0fYSnU2IOA5_:-MXGS1vq0fYSnU2IOA5a:bit088o) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L57)):*
> ```objc
> 
> template <typename It>
> status iterate_through_pairs(It first, It last, get_kv_callback *callback, void *arg)
> ```

pls add a short description for this method
___
*[src/engines/blackhole.cc, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBCrNO5v8A5zDZqe4F:-MXGRmEWC1yZ4FqSvEXQ:b-hndcz9) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/engines/blackhole.cc#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. Right, thanks
</blockquote></details>

not done?
___
*[src/engines/vsmap.cc, line 183 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUJPrBpKqqvulbcIQ:-MXGUJPs1GhESCAl7nq3:bj3j6ck) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines/vsmap.cc#L183)):*
> ```cpp
> 			key_type(key2.data(), key2.size(), kv_allocator));
> 		auto ret = internal::iterate_through_pairs(it, end, callback, arg);
> 		if (ret != status::OK)
> ```

why here this check? shouldn't it be here like it is in other methods?
___
*[src/engines-experimental/csmap.cc, line 6 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGVU1q1NJshUbMYUvb:-MXGVU1q1NJshUbMYUvc:bw2nu0e) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines-experimental/csmap.cc#L6)):*
> ```cpp
> #include "csmap.h"
> #include "../out.h"
> ```

shouldn't we now include iterator.h here?


<!-- Sent from Reviewable.io -->

2021-04-02 09:20 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 13 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGZ8UzC5i4kmTi6PFK:-MXGryiWDIc6lYM_3MTW:b-gmmkrn) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you'll hate this, but commits are a bit messy now (except for the last one)

e.g.
`pmemobj_engine: code duplication remove and cleanup` commit touches config file as well
get_* methods are touched in commit no. 1 and no. 3
etc.

I believe you could start from scratch, remove all commits and add changes line by line (`git commit -p` if I remember correctly) 
</blockquote></details>

I agree, hold your thumbs :D

---
___
*[src/engines/blackhole.cc, line 5 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBCrNO5v8A5zDZqe4F:-MXGoMIC6X0rhqT_hX4l:b-xaxfmk) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/engines/blackhole.cc#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

Previously was 2 lines below your comment and I removed it xD 
I separated .h -> .cc inclusion, it's used in most coding styles to indicates that this source file has related own header file.
If you still want I can remove this separation
___
*[src/engines/vsmap.cc, line 183 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUJPrBpKqqvulbcIQ:-MXGoxOKCE3HzIxXRKEx:b-39tja1) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines/vsmap.cc#L183)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why here this check? shouldn't it be here like it is in other methods?
</blockquote></details>

Indeed, thanks


<!-- Sent from Reviewable.io -->

2021-04-02 12:19 UTC, KFilipek reviewed
> Reviewed 3 of 5 files at r8, 5 of 6 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[src/config.h, line 166 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXB8GblC3hlpcIS9kqx:-MXHUd9NCOfLyVBTTymW:bd9k7o) ([raw file](https://github.com/pmem/pmemkv/blob/2457cd59e4178f1b939d5c1e3a139747e67948b8/src/config.h#L166)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

I missed it
___
*[src/iterator.h, line 4 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUcKjElatm6mWYpjM:-MXHUmZ422N6K8xW7kRo:b9vwzzf) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why these changes from guard headers to pragma? If there's some advantage of pragma over guards, then perhaps we should update it everywhere
</blockquote></details>

I moved to #ifndef combination, later we will consider best approach
___
*[src/iterator.h, line 57 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGS1vq0fYSnU2IOA5_:-MXHVhlB13A62kVzUf5b:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short description for this method
</blockquote></details>

Done.
___
*[src/engines/cmap.h, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBxoEQ-mIaWKHrIspl:-MXHVr4N9IbdZ4BAH2g3:b1fouok) ([raw file](https://github.com/pmem/pmemkv/blob/63948c0ef2b1cd9c39341be3968b049974f8f5a9/src/engines/cmap.h#L101)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can apply the same fix for experimental engines
</blockquote></details>

I'm not sure what fix, I believe this happen in latest patch :D
___
*[src/engines-experimental/csmap.cc, line 6 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGVU1q1NJshUbMYUvb:-MXHWRjM1OhzUcey8LPn:bnw0q0f) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines-experimental/csmap.cc#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we now include iterator.h here?
</blockquote></details>

csmap has own csmap::iterator due to specific key-value (different type) and calls other methods.


<!-- Sent from Reviewable.io -->

2021-04-06 14:38 UTC, karczex commented
___
*[src/iterator.h, line 54 at r10](https://reviewable.io/reviews/pmem/pmemkv/982#-MXbZHbb15txw34V-E6z:-MXbZHbb15txw34V-E7-:bqx98c2) ([raw file](https://github.com/pmem/pmemkv/blob/0f08b8b67780ac53b0f8130a5b58ef5cab5a42e1/src/iterator.h#L54)):*
> ```objc
> 	auto dist = std::distance(first, last);
> 	assert(dist >= 0);
> 	return static_cast<std::size_t>(dist);
> ```

This may be true for some particular engines implementations (probably), and may be implemented the same way in many engines, but as general case (I believe general case is what you want to address)  
`std::distance()` return value may be negative. probably, you should return absolute value instead of cast. 



 


<!-- Sent from Reviewable.io -->

2021-04-06 14:45 UTC, karczex commented
___
*[src/iterator.h, line 4 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUcKjElatm6mWYpjM:-MXbcgyY-gWr1CWtmiUS:bsj3mnj) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I moved to #ifndef combination, later we will consider best approach
</blockquote></details>

#pragma once seems to be less error prone. 


<!-- Sent from Reviewable.io -->

2021-04-07 11:12 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 6 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/iterator.h, line 54 at r10](https://reviewable.io/reviews/pmem/pmemkv/982#-MXbZHbb15txw34V-E6z:-MXg-D1aAUSjCn09T0Mb:b-l2w3ou) ([raw file](https://github.com/pmem/pmemkv/blob/0f08b8b67780ac53b0f8130a5b58ef5cab5a42e1/src/iterator.h#L54)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This may be true for some particular engines implementations (probably), and may be implemented the same way in many engines, but as general case (I believe general case is what you want to address)  
`std::distance()` return value may be negative. probably, you should return absolute value instead of cast. 



 
</blockquote></details>

hmm we rather don't count backwards, we do counts from begin to some value or from some value to end... for now there's check `dist>=0`.. so it should be fine, right...?
___
*[src/engines/cmap.h, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBxoEQ-mIaWKHrIspl:-MXg0htWEpMrIbCKs7Wy:b-dlanmx) ([raw file](https://github.com/pmem/pmemkv/blob/63948c0ef2b1cd9c39341be3968b049974f8f5a9/src/engines/cmap.h#L101)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'm not sure what fix, I believe this happen in latest patch :D
</blockquote></details>

I think he meant `virtual` in iterators (in other engines' headers) 
___
*[src/engines/vsmap.cc, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6Q5-HCfWuQl5cmaH5:-MXg0zhQ6fkfn7Rj7XRl:b-1z9cq) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L27)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. I left it for today and it's finally works
</blockquote></details>

do we need this method, yet?
___
*[src/engines-experimental/csmap.cc, line 6 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGVU1q1NJshUbMYUvb:-MXfpU8n6CVpm479suAH:bl2d4ja) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines-experimental/csmap.cc#L6)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

csmap has own csmap::iterator due to specific key-value (different type) and calls other methods.
</blockquote></details>

but we use `internal::distance` in cout_* methods - isn't it from iterator.h file?


<!-- Sent from Reviewable.io -->

2021-04-08 10:31 UTC, KFilipek reviewed
> Reviewed 2 of 9 files at r6, 3 of 4 files at r11, 2 of 10 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 11 of 19 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/iterator.h, line 4 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGUcKjElatm6mWYpjM:-MXkj1duBPDmiBGfsu7I:b-ht2iqg) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/iterator.h#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

#pragma once seems to be less error prone. 
</blockquote></details>

```#iagree```, but:  1.3.4 Once-Only Include Files in [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-2.95.3/cpp_1.html#SEC8
) is mentioned that ```#pragma once``` is obsolete and there is nothing for a [newer documentation (for GCC 10.2)](https://gcc.gnu.org/onlinedocs/gcc-10.2.0/cpp/Once-Only-Headers.html#Once-Only-Headers) about ```#pragma once``` :-1: 
___
*[src/iterator.h, line 54 at r10](https://reviewable.io/reviews/pmem/pmemkv/982#-MXbZHbb15txw34V-E6z:-MXkoE5_-FJMlRJGdp2e:bn585b6) ([raw file](https://github.com/pmem/pmemkv/blob/0f08b8b67780ac53b0f8130a5b58ef5cab5a42e1/src/iterator.h#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm we rather don't count backwards, we do counts from begin to some value or from some value to end... for now there's check `dist>=0`.. so it should be fine, right...?
</blockquote></details>

Generally, in this case we want to be sure that iteration from ```first``` to ```last``` will happen, when you start from ```last``` iterations will run out causes SEGFAULT.
___
*[src/engines/cmap.h, line 101 at r6](https://reviewable.io/reviews/pmem/pmemkv/982#-MXBxoEQ-mIaWKHrIspl:-MXl1Apx2Ru1ubvRCsuA:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/63948c0ef2b1cd9c39341be3968b049974f8f5a9/src/engines/cmap.h#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think he meant `virtual` in iterators (in other engines' headers) 
</blockquote></details>

Done.
___
*[src/engines/vsmap.cc, line 27 at r3](https://reviewable.io/reviews/pmem/pmemkv/982#-MX6Q5-HCfWuQl5cmaH5:-MXkwk3f144be6n14o5s:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/d82ebfcfe62f571a2677b54525262d64c379d86a/src/engines/vsmap.cc#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need this method, yet?
</blockquote></details>

Done.
___
*[src/engines-experimental/csmap.cc, line 6 at r8](https://reviewable.io/reviews/pmem/pmemkv/982#-MXGVU1q1NJshUbMYUvb:-MXl0452E2sM6lMYAgkg:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/81528dea17467ae49c9dec5a461d7abba218e4e8/src/engines-experimental/csmap.cc#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but we use `internal::distance` in cout_* methods - isn't it from iterator.h file?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-09 10:58 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r11, 10 of 10 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFyUL0D_u1AMIXhbg:-MXqFyUL0D_u1AMIXhbh:bseiwis) (no related file):*
there's still some work to do in commits area:
- commit `pmemobj_engine_base: logic simplification` includes changes not only in pmemobj_engine.h
- why do you have separate commit for removing `virtual` in experimental engines, while you have `virtual`s remove in commit `Remove duplicated code around pmemkv` for other engines...?
- why do you have separate commit for removing `count_iterations` method, since you add it in your first commit (`Remove duplicated code around pmemkv`) ? :smile: 

---
___
*[src/engines/vsmap.cc, line 65 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFcvBDEV56vCpmvwl:-MXqFcvBDEV56vCpmvwm:bg89ydr) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L65)):*
> ```cpp
> 	auto end = pmem_kv_container.end();
> 
> 	cnt = static_cast<std::size_t>(std::distance(it, end));
> ```

hmm.. why not `internal::distance` ?
___
*[src/engines-experimental/tree3.h, line 226 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFXFD4eHcjvm0PZCs:-MXqFXFD4eHcjvm0PZCt:b-w7q49b) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines-experimental/tree3.h#L226)):*
> ```objc
> class tree3_factory : public engine_base::factory_base {
> public:
> 	std::unique_ptr<engine_base>
> ```

I guess these `std`'s are also not required, then


<!-- Sent from Reviewable.io -->

2021-04-13 14:33 UTC, igchor requested changes
> Reviewed 1 of 9 files at r6, 2 of 9 files at r7, 2 of 5 files at r8, 2 of 6 files at r9, 1 of 1 files at r10, 1 of 4 files at r11, 9 of 10 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[src/engines/vsmap.cc, line 53 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MYAdEk03QyhErMkEYwD:-MYAdEk03QyhErMkEYwE:bspw9ep) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L53)):*
> ```cpp
> 	auto end = pmem_kv_container.end();
> 
> 	cnt = static_cast<std::size_t>(std::distance(it, end));
> ```

shouldn't you use our distance instead of std one?


<!-- Sent from Reviewable.io -->

2021-04-19 16:24 UTC, KFilipek reviewed
> Reviewed 8 of 10 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFyUL0D_u1AMIXhbg:-MYemvSkEs0qjGj4sW_s:b-r2pfxb) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's still some work to do in commits area:
- commit `pmemobj_engine_base: logic simplification` includes changes not only in pmemobj_engine.h
- why do you have separate commit for removing `virtual` in experimental engines, while you have `virtual`s remove in commit `Remove duplicated code around pmemkv` for other engines...?
- why do you have separate commit for removing `count_iterations` method, since you add it in your first commit (`Remove duplicated code around pmemkv`) ? :smile: 
</blockquote></details>

1. I know
2. Change was made for non-experimental engines also with other changes, separate commit is only for experimental engines
3. I extracted this changes for easy modification, always combining is easier than dividing.

---
___
*[src/engines/vsmap.cc, line 53 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MYAdEk03QyhErMkEYwD:-MYetwvC1SAtjU-UuOv_:b-6gucys) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't you use our distance instead of std one?
</blockquote></details>

Previous implementation was:
```
template <typename T>
std::size_t count_iterations(T &it, T &end)
{
       std::size_t result = 0;
       for (; it != end; it++)
               result++;
       return result;
}
```
so I believe std::distance is more accurate with its naming and purpose.
___
*[src/engines/vsmap.cc, line 65 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFcvBDEV56vCpmvwl:-MYeuRv_4X8GeAxx6F-v:b-nt2ab8) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. why not `internal::distance` ?
</blockquote></details>

I replied to the same question above
___
*[src/engines-experimental/tree3.h, line 226 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFXFD4eHcjvm0PZCs:-MYewORt9gIfjvRhfCpu:b-dleiuc) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines-experimental/tree3.h#L226)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess these `std`'s are also not required, then
</blockquote></details>

Done.
Indeed, thanks!


<!-- Sent from Reviewable.io -->

2021-04-20 07:08 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFyUL0D_u1AMIXhbg:-MYi4uoX-8s9qn2Y7wGh:bmz8qhd) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

1. I know
2. Change was made for non-experimental engines also with other changes, separate commit is only for experimental engines
3. I extracted this changes for easy modification, always combining is easier than dividing.
</blockquote></details>

1. soo...? I believe you should either drop 'pmemobj_engine_base' in the commit message or move the other code to the first (general code cleanup) commit
2. let's say you'd like to revert the change for using 'virtual' - you'd have to do this manually now, instead of just reverting a single commit covering this one change
3. but in the first commit you created the `count_iterations` method, as well as `internal::distance` (which I believe should be used instead of `count_iterations`)

---
___
*[src/engines/vsmap.cc, line 53 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MYAdEk03QyhErMkEYwD:-MYi3dL59tb6sLGAGnfj:bk6mxbx) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L53)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Previous implementation was:
```
template <typename T>
std::size_t count_iterations(T &it, T &end)
{
       std::size_t result = 0;
       for (; it != end; it++)
               result++;
       return result;
}
```
so I believe std::distance is more accurate with its naming and purpose.
</blockquote></details>

hmm.. then why do we even have the internal::distance? ;)


<!-- Sent from Reviewable.io -->

2021-04-21 07:53 UTC, igchor requested changes
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[src/engines/vsmap.cc, line 53 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MYAdEk03QyhErMkEYwD:-MYnPXBK5dyryANNw3F1:b-ybpwcv) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. then why do we even have the internal::distance? ;)
</blockquote></details>

since we have our internal distance, we should use it everywhere imo


<!-- Sent from Reviewable.io -->

2021-04-21 09:04 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: 19 of 21 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFyUL0D_u1AMIXhbg:-MYndxgO9ApG4Zi5_lI-:b-604hlh) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. soo...? I believe you should either drop 'pmemobj_engine_base' in the commit message or move the other code to the first (general code cleanup) commit
2. let's say you'd like to revert the change for using 'virtual' - you'd have to do this manually now, instead of just reverting a single commit covering this one change
3. but in the first commit you created the `count_iterations` method, as well as `internal::distance` (which I believe should be used instead of `count_iterations`)
</blockquote></details>

1. I've renamed the commit message according to your suggestions
2. Generally, changes in "Remove virtual inheritance" are not related with redundancy etc, so it should stay separated
3. I've removed last commit and changed all references to count_iterations to internal::distance

---
___
*[src/engines/vsmap.cc, line 53 at r13](https://reviewable.io/reviews/pmem/pmemkv/982#-MYAdEk03QyhErMkEYwD:-MYneT2XECnLLC6m_0qI:b-896fix) ([raw file](https://github.com/pmem/pmemkv/blob/886cecfb951467587272e7b15bd2cbc6f7398a40/src/engines/vsmap.cc#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

since we have our internal distance, we should use it everywhere imo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-21 09:05 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-04-21 09:29 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-04-22 08:53 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/982#-:-MYsmFeM7JD5-eZuUhyn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv/982#-MXqFyUL0D_u1AMIXhbg:-MYsmDUY965b_zViQFeK:b-ucfknh) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

1. I've renamed the commit message according to your suggestions
2. Generally, changes in "Remove virtual inheritance" are not related with redundancy etc, so it should stay separated
3. I've removed last commit and changed all references to count_iterations to internal::distance
</blockquote></details>

Thanks!

---


<!-- Sent from Reviewable.io -->

2021-04-22 08:57 UTC, merged